### ISSUE TITLE
🐛 [Bug] Cuda Runtime bug when using PTQ 

### ISSUE THREAD

**Issue by Scikud** [pytorch/TensorRT#1025]
##  Bug Description

When attempting to use TRT to PTQ quantize a 2B parameter GPT-neo model. I keep encountering the following error message
`[executionContext.cpp::commonEmitDebugTensor::1269] Error Code 1: Cuda Runtime (invalid argument)`
Oddly enough, the model will actually finish compiling but then when one tries to load the model with `torch.jit.load(model_path)` the following error  message appears. 
`RuntimeError: Unknown opcode for unpickling at 0xffffffffffffffe5: 229`
 A much smaller 125M parameter version of the same model compiles using PTQ and loads without any such error message on the same hardware. 

Debug logs are long but relevant sections appear to be 

> **ERROR: [Torch-TensorRT TorchScript Conversion Context] - 1: [executionContext.cpp::commonEmitDebugTensor::1269] Error Code 1: Cuda Runtime (invalid argument)**
> INFO: [Torch-TensorRT TorchScript Conversion Context] -   Calibrated batch 0 in 14.5893 seconds.
> **ERROR: [Torch-TensorRT TorchScript Conversion Context] - 1: [executionContext.cpp::commonEmitDebugTensor::1269] Error Code 1: Cuda Runtime (invalid argument)**
> INFO: [Torch-TensorRT TorchScript Conversion Context] -   Calibrated batch 1 in 14.6863 seconds.
> INFO: [Torch-TensorRT TorchScript Conversion Context] -   Post Processing Calibration data in 0.0198819 seconds.

adding the final part of the logs in case it's useful

> DEBUG: [Torch-TensorRT] - Allocated activation device memory of size 2516582400
> INFO: [Torch-TensorRT] - [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +2400, now: CPU 0, GPU 13183 (MiB)
> DEBUG: [Torch-TensorRT] - graph(%self_1 : __torch__.parallel_models.quant_gptneo.QuantParallelGPTNeoModel_trt,
>       %input_0 : Tensor):
>   %__torch___parallel_models_quant_gptneo_QuantParallelGPTNeoModel_trt_engine_ : __torch__.torch.classes.tensorrt.Engine = prim::GetAttr[name="__torch___parallel_models_quant_gptneo_QuantParallelGPTNeoModel_trt_engine_"](%self_1)
>   %3 : Tensor[] = prim::ListConstruct(%input_0)
>   %4 : Tensor[] = tensorrt::execute_engine(%3, %__torch___parallel_models_quant_gptneo_QuantParallelGPTNeoModel_trt_engine_)
>   %5 : Tensor = prim::ListUnpack(%4)
>   return (%5)
> (AddEngineToGraph)

DEBUG: [Torch-TensorRT] - Serialized Device Info: 0%8%0%0%NVIDIA A100-SXM4-80GB

## Environment

Using torch-tensorRT (v1.0.0) docker image built on top of the NGC pytorch container 22.04-py3.
Hardware : Compiling on 1  NVIDIA A100-SXM4-80GB

**Comment by narendasan** [comment]
The full log would be helpful if you can share, the fact its dependent on the size of the model would lead me to start by looking at TRT itself. @peri044 can you take a look?

**Comment by Scikud** [comment]
[run_logs_2b.txt](https://github.com/NVIDIA/Torch-TensorRT/files/8653844/run_logs_2b.txt)
Thanks :) here are the logs.

**Comment by Scikud** [comment]
@peri044 any insights :) ?
