### ISSUE TITLE
✨[Feature] Move `torchtrtc` to using new atol + rtol tolerance measure

### ISSUE THREAD

**Issue by narendasan** [pytorch/TensorRT#1030]
**Is your feature request related to a problem? Please describe.**

Enhancement

**Describe the solution you'd like**

`torchtrtc` should use the new metric for tolerance

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by andi4191** [comment]
Closing this feature request. Change is already merged in to the master branch.
