### ISSUE TITLE
torch_tensorrt.compile  dynamic input shape failed

### ISSUE THREAD

**Issue by f291400** [pytorch/TensorRT#1034]
## dynamic input shape failed

![image](https://user-images.githubusercontent.com/13358476/167369566-faabca74-ba4d-453c-a7b8-ef55aa6fc500.png)

![image](https://user-images.githubusercontent.com/13358476/167369373-9980b51f-330b-4905-a0c8-7e1ea529fbc7.png)

if set min_shape=[1,3,h, h] and op_shape= [1,3, h, h] and max_shape = [1,3, h, h] , which h is 32 or 512 or 1024,  it works. but if set
min_shape = [1, 3, 32, 32] and op_shape=[1,3,512,512] and max_shape = [1, 3, 1024, 1024], it is failed .

## Environment
![image](https://user-images.githubusercontent.com/13358476/167370248-ad9ff570-fdfa-4b6b-af2a-3b05d063820d.png)

**Comment by narendasan** [comment]
Can you add 

```py
with torch_tensorrt.logging.debug():
    torch_tensorrt.compile(....)
```

and provide the logs to us?

**Comment by f291400** [comment]
I use torch-tensorrt which is v1.0.0 version, how can I add debug?
