### ISSUE TITLE
🐛 [Bug] Torch-TensorRT failed test cases with TensorRT 8.4

### ISSUE THREAD

**Issue by bowang007** [pytorch/TensorRT#1040]
##  Bug Description

When the TensorRT is upgraded from 8.2 to 8.4, some test cases in test suite failed. 
There are around 28 test cases failed.
Here are the test cases that failed with 8.4 while fine with 8.2.4:
test_cast,
test_activation,
test_elementwise,
test_interpolate,
test_linear, 
test_pooling, 
test_select, 
test_conv1d_pass, 
test_conditionals, 
test_example_tensors,
test_serialization, 

Almost all of these cases failed with the similar error messages as:
`building seralized network failed inTensorRT
` 

## To Reproduce
Upgrade TensorRT to 8.4

## Expected behavior

Might need to sync up with TensorRT.

**Comment by narendasan** [comment]
Did you file an NVBug for this @bowang007?

**Comment by narendasan** [comment]
Yeah Nick wanted to make sure TRT knew what broke due to the version upgrade

**Comment by bowang007** [comment]
can be closed now.
