### ISSUE TITLE
🐛 [Bug] Encountered bug when using Torch-TensorRT-1.1.0

### ISSUE THREAD

**Issue by f291400** [pytorch/TensorRT#1050]
##  Bug Description

import torch_tensorrt caused error
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/13358476/167665297-4dca4afb-624c-420f-b160-f940c39806db.png">
ImportError: /data/home/ttsyliu/softwares/miniconda3/envs/torch_tensorrt_1.1.0/lib/python3.9/site-packages/torch_tensorrt/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev

compile script :

pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
conda install cudnn
pip install nvidia-tensorrt==8.2.4.2
pip install torch-tensorrt -f https://github.com/NVIDIA/Torch-TensorRT/releases

## Environment
<img width="394" alt="image" src="https://user-images.githubusercontent.com/13358476/167664961-e8449969-3708-410d-b455-c4c263025b61.png">

**Comment by mjack3** [comment]
I suggest you to install tensorRT from tar file instead pip

**Comment by narendasan** [comment]
Some cases of `aten::Int` are supported but not all due to TensorRT limitations. We will progressively add support for more use cases as we can

**Comment by f291400** [comment]
subgraph is like:
class PA(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.pa_conv = nn.Conv2d(dim,
                                 dim,
                                 kernel_size=3,
                                 padding=1,
                                 groups=dim)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return x * self.sigmoid(self.pa_conv(x))

class PatchEmbed(nn.Module):
    """ Image to Patch Embedding"""

    def __init__(self,
                 patch_size=16,
                 in_ch=3,
                 out_ch=768,
                 with_pos=False,
                 sampler=(2, 1)):
        super().__init__()
        self.patch_size = sampler
        self.conv = nn.Conv2d(in_ch,
                              out_ch,
                              kernel_size=patch_size + 1,
                              stride=sampler,
                              padding=patch_size // 2)
        self.norm = nn.BatchNorm2d(out_ch)

        self.with_pos = with_pos
        if self.with_pos:
            self.pos = PA(out_ch)

    def forward(self, x):
        B, C, H, W = x.shape
        x = self.conv(x)
        x = self.norm(x)
        if self.with_pos:
            x = self.pos(x)
        x = x.flatten(2).transpose(1, 2)
        H, W = H // self.patch_size[0], W // self.patch_size[1]  
        return x, (H, W)    // this line occured error!

I found 'return x,(H, W)' will change type from 'tensor' to 'int', like H,W. 
![image](https://user-images.githubusercontent.com/13358476/167768339-22a0f723-3d37-436b-9a25-d786c3019931.png)

when I add 'int()', like 'H, W = int(H) // self.patch_size[0], int(W) // self.patch_size[1]', it will occured another problem like this:
![image](https://user-images.githubusercontent.com/13358476/167769059-0256b745-fba5-4c31-9189-8c652c056e41.png)

**Comment by narendasan** [comment]
```py
import torch
from torch import nn
import torch_tensorrt

class PA(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.pa_conv = nn.Conv2d(dim,
                                 dim,
                                 kernel_size=3,
                                 padding=1,
                                 groups=dim)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return x * self.sigmoid(self.pa_conv(x))

class PatchEmbed(nn.Module):
    def __init__(self,
                 patch_size=16,
                 in_ch=3,
                 out_ch=768,
                 with_pos=False,
                 sampler=(2, 1)):
        super().__init__()
        self.patch_size = sampler
        self.conv = nn.Conv2d(in_ch,
                              out_ch,
                              kernel_size=patch_size + 1,
                              stride=sampler,
                              padding=patch_size // 2)
        self.norm = nn.BatchNorm2d(out_ch)

        self.with_pos = with_pos
        if self.with_pos:
            self.pos = PA(out_ch)

    def forward(self, x):
        B, C, H, W = x.shape
        x = self.conv(x)
        x = self.norm(x)
        if self.with_pos:
            x = self.pos(x)
        x = x.flatten(2).transpose(1, 2)
        H, W = H // self.patch_size[0], W // self.patch_size[1]
        return x, (H, W)    # this line occured error!


model = PatchEmbed(with_pos=True)
model = model.eval().cuda()
ts_model = torch.jit.script(model)

torch_tensorrt.compile(
    ts_model, 
    inputs=[torch_tensorrt.Input((1,3,32,32))], 
    require_full_compilation=True)
```

I was able to run the above script using master, hopefully that unblocks you. Leaving this bug open however because I found an issue with partitioning when `require_full_compilation` is `False`

**Comment by IamExperimenting** [comment]
@narendasan why you're not giving the exact installation process? it would be really helpful if you give the installation requirements, 
- Python version 
- Cuda version
- support packages version
- tensorrt version
- torch_tensorrt version

Its becoming challenging for me and everyone to install torch_tensorrt and use it.

**Comment by IamExperimenting** [comment]
@narendasan  I'm getting the following error, could you please provide the proper installation steps for ubuntu
![Screenshot from 2022-11-17 23-28-00](https://user-images.githubusercontent.com/74839416/202581690-1a2ea081-2781-49fb-aa26-844218412c3e.png)

**Comment by IamExperimenting** [comment]
@
![Screenshot from 2022-11-17 23-33-39](https://user-images.githubusercontent.com/74839416/202582418-88961cd8-f64c-461a-b7e5-037481e22123.png)
narendasan I'm getting another new error. Could you please provide me with the proper installation step for ubuntu 20.04

**Comment by mjack3** [comment]
Try to import TensorRT. If you cannot that's the problem
