### ISSUE TITLE
🐛 [Bug] Wrong version of TensorRT in engine plan

### ISSUE THREAD

**Issue by vvekic** [pytorch/TensorRT#1059]
##  Bug Description

Building an engine using the official pytorch:22.04 image results in a plan file that doesn't run with tritonserver:22.04.
Not entirely sure where to post this issue, but let this be the first stop.

## To Reproduce

1. Convert a compatible torch jit trace to a serialized TensorRT engine using pytorch:22.04 (that has TensorRT 8.2.4.2)
1. Configure and run the engine in Triton using tritonserver:22.04 (that has TensorRT 8.2.4.2)
2. 
`The engine plan file is not compatible with this version of TensorRT, expecting library version 8.2.4 got 8.2.3, please rebuild.`

## Expected behavior

One would expect compatible engines, but it seems that although torch_tensorrt is being run in an image containing TensorRT 8.2.4.2, the resulting plan file is of version 8.2.3. Everything works fine when using the older tritonserver:22.03 image that uses TensorRT 8.2.3.
It's unclear to me how torch_tensort is able to produce an older version of the plan file when the version of the TensorRT library are correct.

## Environment

pytorch:22.04

```
dpkg -l | grep nvinfer
ii  libnvinfer-bin                  8.2.4-1+cuda11.4                  amd64        TensorRT binaries
ii  libnvinfer-dev                  8.2.4-1+cuda11.4                  amd64        TensorRT development libraries and headers
ii  libnvinfer-plugin-dev           8.2.4-1+cuda11.4                  amd64        TensorRT plugin libraries and headers
ii  libnvinfer-plugin8              8.2.4-1+cuda11.4                  amd64        TensorRT plugin library
ii  libnvinfer8                     8.2.4-1+cuda11.4                  amd64        TensorRT runtime libraries
```

tritonserver:22.04

```
dpkg -l | grep nvinfer
ii  libnvinfer-bin                  8.2.4-1+cuda11.4                  amd64        TensorRT binaries
ii  libnvinfer-dev                  8.2.4-1+cuda11.4                  amd64        TensorRT development libraries and headers
ii  libnvinfer-plugin-dev           8.2.4-1+cuda11.4                  amd64        TensorRT plugin libraries and headers
ii  libnvinfer-plugin8              8.2.4-1+cuda11.4                  amd64        TensorRT plugin library
ii  libnvinfer8                     8.2.4-1+cuda11.4                  amd64        TensorRT runtime libraries
```

tritonserver:22.03

```
dpkg -l | grep nvinfer
ii  libnvinfer-bin                  8.2.3-1+cuda11.4                  amd64        TensorRT binaries
ii  libnvinfer-dev                  8.2.3-1+cuda11.4                  amd64        TensorRT development libraries and headers
ii  libnvinfer-plugin-dev           8.2.3-1+cuda11.4                  amd64        TensorRT plugin libraries and headers
ii  libnvinfer-plugin8              8.2.3-1+cuda11.4                  amd64        TensorRT plugin library
ii  libnvinfer8                     8.2.3-1+cuda11.4                  amd64        TensorRT runtime libraries
```

**Comment by andi4191** [comment]
Hi @vvekic,

I haven't been able to reproduce this issue.
It seems to be an environment issue.

Can you try running the engine file you generated with trtexec inside the ngc 22.04 (same) container using following command:
`/opt/tensorrt/bin/trtexec --loadEngine=<your serialized TRT engine file>`

For generating a model I just tried one of the test cases here:

```
@@ -26,6 +26,9 @@ class TestPyTorchToTRTEngine(ModelTestCase):
         }
 
         trt_engine = torchtrt.ts.convert_method_to_trt_engine(self.ts_model, "forward", **compile_spec)
+        with open('trt_engine.trt', 'wb') as f:
+            f.write(trt_engine)
+
 
         TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
         with trt.Runtime(TRT_LOGGER) as rt:
```

**Comment by vvekic** [comment]
I've tried running the plan with `trtexec` in pytorch:22.04, and indeed it works. But that's no surprise since the plan was created using that same container.
The issue is that the plan doesn't load up in Triton Server container tritonserver:22.04 (server version 2.21.0), but loads up in previous version 22.03.
@andi4191 Have you successfully done that? use tritonserver:22.04 to load a plan created in pytorch:22.04?

**Comment by andi4191** [comment]
@vvekic :
As I said before, I was not able to reproduce the issue.
Yes, I have tried running the same engine inside tritonserver container. It runs fine on my end:

I used following tritonserver image:
`nvcr.io/nvidia/tritonserver:22.04-py3`

from here: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver/tags

If you are able to build using TRT-8.2.4.2 successfully, you should be able to run it using trtexec on (same container) and tritonserver:22.04.

**Comment by vvekic** [comment]
I never mentioned that loading with `trtexec` failed. The issue is about the Triton Server not being able to load the plan.
So, yes, running `trtexec` inside Triton container works, but loading the plan in Triton itself doesn't. That's the issue.

I'm sorry if I've been unclear or maybe this issue belongs in Triton somewhere.

**Comment by vvekic** [comment]
Everything works as expected with `22.05` images, so I'm closing this one.
