### ISSUE TITLE
✨[Feature] change branch name

### ISSUE THREAD

**Issue by frank-wei** [pytorch/TensorRT#1065]
@ncomly-nvidia @narendasan , this issue is opened for discussing our request for setting up the branches. I have list the request 1 to follow the Meta policy with reasons and action items. If you agree, I will make the name change after we cleared the cautions. Request 2 is for our previous discussion too.

Request 1: Change master branch name to main branch

WHY ARE WE DOING THIS?
The software community is moving away from terms that reference slavery. Continuing to use such terms is insensitive, uninclusive, and highlights the systemic inequities present in our industry. To date, companies such as [GitHub](https://l.workplace.com/l.php?u=https%3A%2F%2Fwww.zdnet.com%2Farticle%2Fgithub-to-replace-master-with-main-starting-next-month%2F&h=AT0TDsmxIa8bD7hEwGw9G6tjG9WpWmrMRXUJZOXela4fN6M7kh2eGRvqyhMEgkBcd0w7xblpXtEtpd-1EXPauixzuKK4tQAC4G543bWRoxUhv-_wD46QPxFMveustr0Q85mOSE_0VPhq5DOa8gq9u3dcyja6hzxvv-EL&__tn__=-UK-R&c[0]=AT1iNoPGJ4aKBNqdhCDtjbgM4LEaZwf13VDkFget-obRRfwhdYmI2lz-x2XQ0J6F9eNcBYSthHmRcsIPNIB41Sf953SppwCV1lryJQgmKL5Z3wMmCwaYzjFtXFYi9mqSYzraty0ANkYuJ1dfBs93ojYWP4lpwdA0L3ReBmvXEWJBP0ilNpj_9JPxtsLgrSWWyWL2), [Microsoft](https://l.workplace.com/l.php?u=https%3A%2F%2Fdevblogs.microsoft.com%2Fdevops%2Fazure-repos-default-branch-name%2F&h=AT1ZOhyO8Ym_c8AOfPVt6hdEa5lIWhpmiAPwm6KD75KybsDJrt06teWXih_s8m84NgsS0sVKPJJdJqPZ52XJiNQ6lTXn66eoOFv3uaCsvjrE-MS9p1mziSqzwXtIAFGPQwFTENUc34TfvBHwPV5Uyz1xdf63M_SBxhRP&__tn__=-UK-R&c[0]=AT1iNoPGJ4aKBNqdhCDtjbgM4LEaZwf13VDkFget-obRRfwhdYmI2lz-x2XQ0J6F9eNcBYSthHmRcsIPNIB41Sf953SppwCV1lryJQgmKL5Z3wMmCwaYzjFtXFYi9mqSYzraty0ANkYuJ1dfBs93ojYWP4lpwdA0L3ReBmvXEWJBP0ilNpj_9JPxtsLgrSWWyWL2), [Twitter](https://l.workplace.com/l.php?u=https%3A%2F%2Ftwitter.com%2FTwitterEng%2Fstatus%2F1278733305190342656&h=AT1x5DLK79-191EV7OkhQqalG2-xL7fuvREO3SBTJpTYc2_3dVOOpUR21iBBlR4D3--1g9UseVzh0s6z18T7mdX7VDiqpzT--oiWqLCVHFbTaDML_VPJGeZT6QMAHlPZQqBpEJecrLlFgPfOHGrM-DIv7Z937mZHy1MA&__tn__=-UK-R&c[0]=AT1iNoPGJ4aKBNqdhCDtjbgM4LEaZwf13VDkFget-obRRfwhdYmI2lz-x2XQ0J6F9eNcBYSthHmRcsIPNIB41Sf953SppwCV1lryJQgmKL5Z3wMmCwaYzjFtXFYi9mqSYzraty0ANkYuJ1dfBs93ojYWP4lpwdA0L3ReBmvXEWJBP0ilNpj_9JPxtsLgrSWWyWL2), and [RedHat](https://l.workplace.com/l.php?u=https%3A%2F%2Fwww.redhat.com%2Fen%2Fblog%2Fmaking-open-source-more-inclusive-eradicating-problematic-language&h=AT1xD50W8JDNY2cTGtrYC9y_aQDwWr6ap5SxsJ2M48FSO7Ni_nNarN7o8tz6jfimBegS19HFb_BsSFbs9jCU5OjagkDhjfP8YSCoGpz24L-Mebwhyj7paP-Kjm0yN4kt2adyUSpj-SyRAR_BenRxovqwj-yE1yDxhDYK&__tn__=-UK-R&c[0]=AT1iNoPGJ4aKBNqdhCDtjbgM4LEaZwf13VDkFget-obRRfwhdYmI2lz-x2XQ0J6F9eNcBYSthHmRcsIPNIB41Sf953SppwCV1lryJQgmKL5Z3wMmCwaYzjFtXFYi9mqSYzraty0ANkYuJ1dfBs93ojYWP4lpwdA0L3ReBmvXEWJBP0ilNpj_9JPxtsLgrSWWyWL2) have renamed many of their repositories' primary branches away from “master,” and such changes have been an [ongoing effort](https://fb.workplace.com/groups/e/permalink/3320810064641820/) within Facebook. Projects like React, React Native, and Docusaurus have made this migration already. This is an incremental step in the right direction as we work towards an inclusive Open Source environment.

IS THERE ANYTHING ELSE I NEED TO WATCH OUT FOR?
Look for references to masterin documentation.
Update any relevant instructions in CONTRIBUTING.md (if you have one).
Update OSS Continuous Integration configs (GitHub Actions, CircleCI, etc.)
Update any release/builds scripts, as applicable.
Update any code in FB internal systems that depends on the default branch name.
This might be things like the script that imports the code from GitHub.
GitHub forks and local repos will not be updated automatically. Open PRs will be updated automatically.
This change may trigger new CI jobs on open pull requests.
You may not be able to re-open closed PRs.

Request 2: We will create another branch named "stable"(pls suggest other names) for landing any PRs that passed Jetson/edge devices and expected the PRs will be merged back to main branch

**Comment by narendasan** [comment]
For request 2: `stable` or `pre-release` would be good options.

**Comment by ncomly-nvidia** [comment]
@frank-wei @narendasan any update on this? Seems we solidified on Request 1 at the least

**Comment by ncomly-nvidia** [comment]
@frank-wei I don't have access rights to change the branch name. Seems we've solidified on a workflow already, are we OK to change the name to main?

Are you have to do so?

**Comment by ncomly-nvidia** [comment]
@frank-wei can you please change the branch name.

**Comment by frank-wei** [comment]
Done for changing the branch name.
