### ISSUE TITLE
🐛 [Bug] Encountered bug when using Torch-TensorRT in C++

### ISSUE THREAD

**Issue by f291400** [pytorch/TensorRT#1068]
##  Bug Description

use torch-tensorrt in C++ occurred.
Error occurred before running into main  function.
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/13358476/168430078-230d3d96-5da3-4411-bc13-d0fef81132c4.png">

CMakeLists.txt:
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/13358476/168430160-2d57185c-e00e-475f-bb3c-f2d60bef5e83.png">

part of code:
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/13358476/168430140-228e9a22-69ae-4b3c-8866-edee77debfdf.png">

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version : 1.1.0 
 - LibTorch Version : 1.11.0(compiled  by myself)
 - CPU Architecture: x86
 - OS (e.g., Linux): Linux
 - How you installed LibTorch : Source 
 - Build command you used (if compiling from source): TORCH_CUDA_ARCH_LIST="3.5;5.0;5.2;6.0;6.1;7.0;7.5;7.5;8.0;8.6;8.6+PTX" ONNX_NAMESPACE="torch_tmp" USE_NUMPY=0 USE_DISTRIBUTED=OFF USE_NCCL=OFF _GLIBCXX_USE_CXX11_ABI=0 python setup.py install
 - CUDA version: 11.3
 - Tensorrt Version: 8.2.4.2
 - Gcc: 7.5.0

**Comment by narendasan** [comment]
Likely this is caused because you are linking both libtorchtrt and libtorchtrt_runtime, you only need one or the other depending on if you are compiling as part of your application (you need the full libtorchtrt) or you are using a precompiled module and just performing inference (you only need libtorchtrt_runtime)

**Comment by narendasan** [comment]
Going to close this, reopen if you are still having trouble
