### ISSUE TITLE
🐛 [Bug] Using TensorRT v1.0.0 I am getting different dtypes depending of the installation method

### ISSUE THREAD

**Issue by mjack3** [pytorch/TensorRT#1081]
##  Bug Description

Using TensorRTv1.0.0 to optimize a model in TensorRT16, the output tensor return 
- torch.float32 if is installed with pip (using a desk computer).
- torch.float16 if is installed from source (using a Jetson system)

In both system I have installed
torch v1.10.0
torchvision v0.11.0
torch_tensorRT v1.0.0

## To Reproduce

Use any model, and convert it to TensorRT16 using

```
your_model = ...
torchscript_model = torch.jit.trace(your_model, torch.rand((1, 3, 224, 224), device=gpu_device))
tensorrt = torch_tensorrt.compile(torchscript_model,
                                  inputs=[torch_tensorrt.Input((1, 3, 224, 224), dtype=torch.half)],
                                  enabled_precisions=torch.half)
...
output_tensor = model(input)
```

## Expected behavior

The output tensor should be the same dtype without matter the installation method

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.0.0 (computer) and 1.0.0 (Jetson)
 - PyTorch Version: 1.10.0
 - CPU Architecture: Computer and Jetson with JetPack 4.6
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): via pip (computer) and source (jetson)
 - Python version: 3.6 (jetson) and 3.8 (computer)
 - CUDA version: 10.2 (jetson) 11.6 (computer)
 - GPU models and configuration: RTX3090 (computer)

**Comment by mjack3** [comment]
That's a good point.

This is the which I do the conversion

```
# TorchScript conversion
torchscript_model = torch.jit.trace(model, torch.rand((1, 3, 224, 224), device=gpu_device))
tensorrt = torch_tensorrt.compile(torchscript_model,
                                  inputs=[torch_tensorrt.Input((1, 3, 224, 224), dtype=torch.half)],
                                  enabled_precisions=torch.half)

input_data = torch.randn(1, 3, 224, 224).cuda()
 with torch.no_grad():
        embedding = model(input_data)
```
And then, testing the output of the model (which is a Wide_resnet50)

- In a computer with Ubuntu 24.04 the model return a fp32 type
- In a Jetson NX jet JetPack 4.6 the model return fp16 type

**Comment by mjack3** [comment]
Any news?

**Comment by IamExperimenting** [comment]
@mjack3 , I see you have installed torch_tensorrt , could you please provide me an article or blog to install it?

or could you please by a step by step procedure to install in ubuntu 20.04

**Comment by mjack3** [comment]
Sure. That is because your torch version is not supported by the torch_tensorrt you have installed.

Check in the releases notes that you have the correct one :)
