### ISSUE TITLE
I wonder if torch_tensorrt support mixed precisions for different layer

### ISSUE THREAD

**Issue by pupumao** [pytorch/TensorRT#1089]
**Is your feature request related to a problem? Please describe.**
I write a converter and plugin, but plugin only support fp32, then if I convert with enabled_precisions: torch.int8, then error happend

**Describe the solution you'd like**
if different layer can use different precisions, i can use fp32 this plugin layer and int8 other layers

**Comment by narendasan** [comment]
TensorRT supports mixed precision by default. You can follow this guide to properly set up your plugin to declare its output type. https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending

**Comment by pupumao** [comment]
> TensorRT supports mixed precision by default. You can follow this guide to properly set up your plugin to declare its output type. https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending

I got it, thank you for reply
