### ISSUE TITLE
🐛 [Bug] Typo in documentation and hyperlink broken

### ISSUE THREAD

**Issue by andi4191** [pytorch/TensorRT#1097]
##  Bug Description

It appears from the documentation that there are typos [here](https://pytorch.org/TensorRT/_notebooks/dynamic-shapes.html?highlight=dynamic%20shapes#) and the links are broken.

If the hyper links are supposed to be directed to the same section on the same page then simply remove the hyperlinks.

## To Reproduce
Go to following URL:
https://pytorch.org/TensorRT/_notebooks/dynamic-shapes.html?highlight=dynamic%20shapes#

## Expected behavior

1. Typo should be corrected
2. Links should be working

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 
 - PyTorch Version (e.g. 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by tanayvarshney** [comment]
Fixed with: https://github.com/pytorch/TensorRT/pull/1098
