### ISSUE TITLE
How can i compile CUDA C in this project❓ [Question] How do you ....? 

### ISSUE THREAD

**Issue by p517332051** [pytorch/TensorRT#1114]
## ❓ Question

I want compile tensorrt plugin in this project. But I do not know how to use bazel to compile the cuda c.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by narendasan** [comment]
You can refer to this issue https://github.com/pytorch/TensorRT/issues/987

**Comment by narendasan** [comment]
Closing as duplicate
