### ISSUE TITLE
🐛 [Bug] Encountered bug when using Torch-TensorRT

### ISSUE THREAD

**Issue by QiusongYang** [pytorch/TensorRT#1127]
##  Bug Description

torch.max to tensorrt operator failure

## To Reproduce

1. `batch_max_used_token_hidden_states.max(dim=1)[0]`

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.1.0
 - PyTorch Version (e.g. 1.0): 1.12.0
 - CPU Architecture:
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pytorch official docker 22.05
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version: 11.3
 - GPU models and configuration: tsal p40
 - Any other relevant information:

**Comment by narendasan** [comment]
Please provide a complete reproducing script

**Comment by ncomly-nvidia** [comment]
Hi @QiusongYang can you please provide your python script where you are seeing this failure? Without knowing the specific failure we won't be able to help debug with you.

**Comment by QiusongYang** [comment]
> Hi @QiusongYang can you please provide your python script where you are seeing this failure? Without knowing the specific failure we won't be able to help debug with you.

actually, you can write any network and torch::max function, could you convert to tensorrt model?
