### ISSUE TITLE
❓ [Question] unable to save the model in TorchScript format? 

### ISSUE THREAD

**Issue by IamExperimenting** [pytorch/TensorRT#1136]
## ❓ Question
I'm trying to save my model as TorchScript format, unfortunately getting error.

## What you have already tried
```torch.jit.script(model)```

## Environment
python
> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0):1.11.0+cu113
 - CPU Architecture:
 - OS (e.g., Linux): ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:3.9.7
 - CUDA version:11.7
 - GPU models and configuration: RTX GEFORCE 2060
 - Any other relevant information:

## Additional context

could you please help me save the model in TorchScript format
@dignakov @narendasan @peri044 
![Screenshot from 2022-06-20 11-29-31](https://user-images.githubusercontent.com/74839416/174584985-ca331c70-5a45-4811-860d-157878aa322b.png)

**Comment by narendasan** [comment]
Can you provide an minimal example of what you are doing? Have you already compiled the model with Torch-TensorRT or is this before hand?

**Comment by IamExperimenting** [comment]
I have built the custom model and I'm trying to save the model inTorchScript format.

basically, when I run this line ``` torch.jit.script(model)``` I get this error.

**Comment by narendasan** [comment]
If that is where you are hitting the issue then likely it is a problem with TorchScript and asking in https://github.com/pytorch/pytorch would probably be the best next step.
