### ISSUE TITLE
🐛 [Bug] Convert x3d model from pytorchvideo

### ISSUE THREAD

**Issue by hongsamvo** [pytorch/TensorRT#1160]
##  Bug Description

I am trying to convert x3d model from pytorchvideo and got this error "ValueError: Unknown type annotation: '<class 'torch.nn.modules.module.Module'>' at". 
The problem happened when I use torch_tensorrt.compile() or by "ts_model = torch.jit.script(model)"
I think the error due to the model's definition by pytorchvideo. I got error on both torch 1.11 and torch 1.12. I hope to receive some suggestion. 
Thanks!!!

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version : 1.1.0
 - PyTorch Version (e.g. 1.0): 1.11 (install by conda) and 1.12 (install by [Nvidia forum](https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-11-now-available/72048))
 - OS (e.g., Linux):Linux
 - Python version:aarch64linilin 3.8
 - CUDA version: 11.4
 - GPU models and configuration: 2080TI and jetson NX with Jetpack 5.0
 - Any other relevant information:

**Comment by peri044** [comment]
Could you provide more details about the model or the model itself ? This looks like a torchscripting issue. Maybe torchscript compiler is unable to understand the types  in the model.

**Comment by hongsamvo** [comment]
Hi, I called x3d-m model from [pytorchvideo](https://github.com/facebookresearch/pytorchvideo), the model is definded in this [file](https://github.com/facebookresearch/pytorchvideo/blob/main/pytorchvideo/models/x3d.py).

**Comment by ncomly-nvidia** [comment]
@hongsamvo so the x3d-m model fails to be scripted, even before Torch-TRT `.comiple()`? ie. the following fails:
```
# <download x3d-m_model from pytorchvideo>
...
torch.jit.script(x3d-m_model) # model directly from pytorchvideo
```

If so, then this is a torchscript issue. We recommend you creating an issue on pytorchvideo to get help with torchscripting.

**Comment by hongsamvo** [comment]
@ncomly-nvidia yes, I haved problem when converted to torch script first, thank you for your recommend.
