### ISSUE TITLE
❓ [Question] How to run Torch-Tensorrt on JETSON AGX ORIN?

### ISSUE THREAD

**Issue by krmayankb** [pytorch/TensorRT#1166]
## ❓ Question
**Not able to run Torch-Tensorrt on Jetson AGX ORIN**
As per the [release note](https://github.com/pytorch/TensorRT/discussions/1043), it is mentioned that current release doesn't have support for Jetpack 5.0DP but ORIN only supports Jetpack 5.0DP (I might be wrong but inferring from this [Jetpack Archives.](https://developer.nvidia.com/embedded/jetpack-archive). **Is there a way to run Torch-Tensort on ORIN?** if not what's the possible timeline for new release with this support? 

## What you have already tried

I did tried building for python, as suggested in the repo, it enables `import torch_tensorrt` but doesn't supports any attributes.  

## Environment
 - PyTorch Version (e.g., 1.0): 1.11 
 - CPU Architecture: arm64
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): tried both, wheels provided [here ](https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-11-now-available/72048) and building from source(instruction from [here](https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-11-now-available/72048)). 
 - Build command you used (if compiling from source): python3 setup.py --use_cxx11_abi (however, this refers to jetpack 4.6 by default) 
 - Python version: 3.8
 - CUDA version: 11.4
 - GPU models and configuration: Jetson ORIN 
 - Any other relevant information:

**Comment by peri044** [comment]
We are currently working on that and plan to release a version compatible with Jetpack 5.0 soon. Here is a working PR you can try https://github.com/pytorch/TensorRT/pull/1158

**Comment by bharatsshinde** [comment]
@krmayankb you can build Torch-TensorRT from source on the Orin. I used v1.1.0.

**Comment by gemm4** [comment]
@krmayankb You can build Torch-TensorRT from source on the Jetson AGX ORIN. I used v1.1.0.

**Comment by krmayankb** [comment]
> @krmayankb Were you able to run torch_tensorrt on Orin successfully?

@haichuanwang001 No, I couldn't. I stop trying based on feedback received. 

Currently, I am working with the Python API of TensorRT. It's a bit of work to wrap your head around but it works. Let me know if you need more info about this.

**Comment by narendasan** [comment]
torch-tensorrt 1.1.1 was released with Orin support https://github.com/pytorch/TensorRT/releases/tag/v1.1.1 

Follow the instructions here to install https://pytorch.org/TensorRT/tutorials/installation.html
