### ISSUE TITLE
❓ [Question] Python Package for V1.1.1 Release? 

### ISSUE THREAD

**Issue by haichuanwang001** [pytorch/TensorRT#1186]
## ❓ Question

Does the latest release include the python package for supporting JP5.0 too?

 - PyTorch Version (e.g., 1.0): 1.11
 - CPU Architecture: Arm64
 - Python version: 3.8
 - CUDA version: 11.4

**Comment by narendasan** [comment]
There is no precompiled python package for this release as it is targeted at Jetson specifically where we expect users to build from source.

**Comment by haichuanwang001** [comment]
> There is no precompiled python package for this release as it is targeted at Jetson specifically where we expect users to build from source.

I am compiling from source with the guidelines from the provided link. The setup.py file in the py folder doesn’t seem to support JP5.0 (still 4.5 and 4.6). Do I need to do something else?
