### ISSUE TITLE
❓ [Question] cmake do not find torchtrt?

### ISSUE THREAD

**Issue by gxxyongzhe** [pytorch/TensorRT#1207]
## ❓ Question

Hi, im trying to compile from source and test with c++.

I built using locally installed cuda 10.2 , tensort 8.2 and libtorch cxx11 abi, compile using `bazel build //:libtorchtrt -c opt` 
It looks like the installation was successful.
```
INFO: Analyzed target //:libtorchtrt (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:libtorchtrt up-to-date:
  bazel-bin/libtorchtrt.tar.gz
INFO: Elapsed time: 248.908s, Critical Path: 35.38s
INFO: 217 processes: 2 internal, 215 linux-sandbox.
INFO: Build completed successfully, 217 total actions

```

But when i test with c++, the cmake can not find torchtrt, seems like the installation was not correctly？？？
Is there anyone who can tell me what do i miss???   thank u.

this is my cmakelist file, it works without  `find_package(torchtrt REQUIRED)`

```
project(example)
cmake_minimum_required(VERSION 3.0)

set(CMAKE_CXX_STANDARD 14)

set(Torch_DIR /home/xs/libtorch/share/cmake/Torch)  
find_package(Torch REQUIRED)
find_package(torchtrt REQUIRED)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")

add_executable(example main.cpp)
target_link_libraries(example "${TORCH_LIBRARIES}")
```
Errors:
```
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "Findtorchtrt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "torchtrt",
  but CMake did not find one.

  Could not find a package configuration file provided by "torchtrt" with any
  of the following names:

    torchtrtConfig.cmake
    torchtrt-config.cmake

  Add the installation prefix of "torchtrt" to CMAKE_PREFIX_PATH or set
  "torchtrt_DIR" to a directory containing one of the above files.  If
  "torchtrt" provides a separate development package or SDK, be sure it has
  been installed.
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0):  1.11.0
 - CPU Architecture: x86-64
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip whl file from PyTorch.org
 - Build command you used (if compiling from source):  compiling from source
 - Are you using local sources or building from archives: local sources
 - Python version: 3.7.0
 - CUDA version: 10.2
 - GPU models and configuration: gtx 1050ti
 - Any other relevant information:

**Comment by yokosyun** [comment]
maybe you have to add 
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path-to/trtorch/lib
```
https://github.com/pytorch/TensorRT/issues/632#issuecomment-927095884

**Comment by gxxyongzhe** [comment]
> maybe you have to add
> 
> ```
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path-to/trtorch/lib
> ```
> 
> [#632 (comment)](https://github.com/pytorch/TensorRT/issues/632#issuecomment-927095884)

Thanks, but there is no /opt/trtorch/lib/libtrtorch.so and directory /opt/trtorch/,  only can find libtorchtrt.so in /home/xs/TensorRT/bazel-bin/cpp/lib

i tried to add this address in cmakelist like,  It still doesn't work. 
`set(torchtrt_DIR /home/xs/TensorRT/bazel-bin/cpp/lib)  
find_package(torchtrt REQUIRED)`

**Comment by gxxyongzhe** [comment]
solved

**Comment by galAcarteav** [comment]
Hey, facing in same issue..
can you please share your solution please?

**Comment by galAcarteav** [comment]
@gxxyongzhe

**Comment by janblumenkamp** [comment]
Same problem here.
