### ISSUE TITLE
❓ [Question] How do you install an older TensorRT package?

### ISSUE THREAD

**Issue by JinLi711** [pytorch/TensorRT#1209]
## ❓ Question

How do you install an older TensorRT package? I'm using Pytorch 1.8 and TensorRT version 0.3.0 matches that Pytorch version.

## What you have already tried

I tried:

```
pip3 install torch-tensorrt==v0.3.0 -f https://github.com/pytorch/TensorRT/releases
Looking in links: https://github.com/pytorch/TensorRT/releases
ERROR: Could not find a version that satisfies the requirement torch-tensorrt==v0.3.0 (from versions: 0.0.0, 0.0.0.post1, 1.0.0, 1.1.0)
ERROR: No matching distribution found for torch-tensorrt==v0.3.0
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by sph1n3x** [comment]
Afaik the package name was changed at some point.
Maybe try:
`pip3 install trtorch==v0.3.0 -f https://github.com/pytorch/TensorRT/releases`

**Comment by ncomly-nvidia** [comment]
The package name changed from `trtorch` to `torch-tensorrt` in v1.0. @JinLi711 is there a reason you're looking for v0.3?
