### ISSUE TITLE
❓ [Question] How do you debug errors in the compilation step? 

### ISSUE THREAD

**Issue by Mark-M2L** [pytorch/TensorRT#1235]
## ❓ Question

Hello all, 

After training a model, I decided to use torch_tensorrt to test and hopefully increase inference speed. When compiling the custom model, I get the following error: `RuntimeError: Trying to create tensor with negative dimension -1: [-1, 3, 600, 400]`. This did not occur when doing inference in regular PyTorch. Further the following warning was issued (before receiving the error):
```WARNING: [Torch-TensorRT] - For input x.1, found user specified input dtype as Float16, however when inspecting the graph, the input type expected was inferred to be Float
The compiler is going to use the user setting Float16
This conflict may cause an error at runtime due to partial compilation being enabled and therefore
compatibility with PyTorch's data type convention is required.
If you do indeed see errors at runtime either:
- Remove the dtype spec for x.1
- Disable partial compilation by setting require_full_compilation to True```

The code to compile is as follows:
```inputs = [torch_tensorrt.Input(
            min_shape=[2, 3, 600, 400],
            opt_shape=[4, 3, 600, 400],
            max_shape=[8, 3, 600, 400],
            dtype=torch.half,
        )]
enabled_precisions = {torch.float, torch.half}
trt_ts_module = torch_tensorrt.compile(model, inputs=inputs, enabled_precisions=enabled_precisions)
```

My question is: what can I do to properly debug this error?

## What you have already tried
- Use `mobilenet_v2`, as specified in the example https://pytorch.org/TensorRT/tutorials/use_from_pytorch.html#use-from-pytorch. This model compiles successfully.
- Change the input size (change the batch size, i.e. the first dimension, use shapes of >= 100). This gave the same error.
- Set `require_full_compilation` to True, which was not fruitful either.

## Environment
 - PyTorch Version (e.g., 1.0): 1.11.0+cu113
 - Torch-TensorRT version: 1.1.0
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Ubuntu 20.04 (kernel: 5.4.0-122-generic)
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): `pip`, from within a virtual environment (`pyenv`)
 - Are you using local sources or building from archives:
 - Python version: 3.8.13
 - CUDA version: 11.4.4 (Driver: 470.82.01)
 - GPU models and configuration: Nvidia RTX A2000
 - Any other relevant information: TensorRT has been installed via pip, to install torch_tensorrt (and getting it to import in Python), I followed the answer in the following issue: https://github.com/pytorch/TensorRT/issues/1026#issuecomment-1119561746

Looking forwards to your answer, thanks in advance.

**Comment by narendasan** [comment]
This error is due to trying to use dynamic shape with partial compilation enabled. Currently there is a limitation in Torch-TensorRT where you cannot use these features together. For further debugging usually the first thing I do is enable the debug logs: 

```py

inputs = [torch_tensorrt.Input(
            min_shape=[2, 3, 600, 400],
            opt_shape=[4, 3, 600, 400],
            max_shape=[8, 3, 600, 400],
            dtype=torch.half,
        )]
enabled_precisions = {torch.float, torch.half}

with torch_tensorrt.logging.debug():
    trt_ts_module = torch_tensorrt.compile(model, inputs=inputs, enabled_precisions=enabled_precisions)

```

This gives you more information about the internal state of the compiler including what symbols have already been parsed and translated
