### ISSUE TITLE
🐛 [Bug] Error on build with CMAKE, win11

### ISSUE THREAD

**Issue by zsef123** [pytorch/TensorRT#1245]
##  Bug Description

C2487 error on `Input Constructor`
```
Error	C2487
'torch_tensorrt::Input::{ctor}': member of dll interface class may not be declared with dll interface	D:\projects\tensorrt\CMakeLists.txt
D:\projects\tensorrt\cpp\include\torch_tensorrt\torch_tensorrt.h	511	
```

`TORCHTRT_API Input(std::vector<int64_t> shape, TensorFormat format = TensorFormat::kContiguous);
` 
like this codes

## To Reproduce
Use Visual Studio 2019 with CMake, Build > Install tab

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): master
 - PyTorch Version (e.g. 1.0): 1.12
 - CPU Architecture: Ryzen 2700
 - OS (e.g., Linux): Win 11
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): libtorch
 - Build command you used (if compiling from source): 
 - Are you using local sources or building from archives:
 - Python version: 3.8
 - CUDA version: 11.4
 - GPU models and configuration: RTX3070
 - Any other relevant information:

**Comment by narendasan** [comment]
@andi4191 Do you have access to a Windows machine to repro? I wont for a few weeks

**Comment by andi4191** [comment]
I need to check.

**Comment by narendasan** [comment]
The graph input fix for cmake was merged last night, so maybe try that out and see if it helps

**Comment by zsef123** [comment]
> That error causes missing new file in CMakelists( fine in Bazel) I thinks this srcs to handle with glob
> 
> And I still got other linking errors related the Compile spec or GraphInputs
> 

I fused problems.
missing file is related with GraphInputs ( above comments)

And still got error about Input or Compilepsecs

**Comment by centerzong** [comment]
I meet the same problem on windows10.i need help.

**Comment by andi4191** [comment]
@centerzong: Can you please try the master branch and confirm if it fixes your issue?

**Comment by zsef123** [comment]
@andi4191 working fine 👍
