### ISSUE TITLE
🐛 [Bug] Warning thrown when exporting model

### ISSUE THREAD

**Issue by domef** [pytorch/TensorRT#1248]
##  Bug Description

An unexpected warning is thrown when I try to export a simple model with `torch_tensorrt`.

## To Reproduce

This is the code I used:

```python
import torch
import torch_tensorrt

class DummyModel(torch.nn.Module):
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, C, H, W = x.shape
        eye = torch.eye(H, W, dtype=x.dtype, device=x.device).unsqueeze(0).unsqueeze(0)
        result = x * eye
        return result

dummy_input = torch.rand((1, 1, 32, 64), dtype=torch.float, device="cuda")
model = DummyModel().eval().cuda()
model_script = torch.jit.script(model)
model_trace = torch.jit.trace(model, dummy_input)



model_script_trt = torch_tensorrt.ts.compile(
    model_script,
    inputs=[torch_tensorrt.Input(dummy_input.shape, dtype=dummy_input.dtype)],
    device={
        "device_type": torch_tensorrt.DeviceType.GPU,
        "gpu_id": 0,
        "dla_core": 0,
        "allow_gpu_fallback": True,
    },
    truncate_long_and_double=True,
)

model_trace_trt = torch_tensorrt.ts.compile(
    model_trace,
    inputs=[torch_tensorrt.Input(dummy_input.shape, dtype=dummy_input.dtype)],
    device={
        "device_type": torch_tensorrt.DeviceType.GPU,
        "gpu_id": 0,
        "dla_core": 0,
        "allow_gpu_fallback": True,
    },
    truncate_long_and_double=True,
)
```

The output is:

```
WARNING: [Torch-TensorRT TorchScript Conversion Context] - The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
WARNING: [Torch-TensorRT TorchScript Conversion Context] - The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
WARNING: [Torch-TensorRT TorchScript Conversion Context] - The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
WARNING: [Torch-TensorRT TorchScript Conversion Context] - The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
```

The same warning is thrown with this equivalent model:

```python
class DummyModel(torch.nn.Module):
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        eye = torch.eye(x.shape[2], x.shape[3], dtype=x.dtype, device=x.device).unsqueeze(0).unsqueeze(0)
        result = x * eye
        return result
```

## Environment

I' m using the container nvcr.io/nvidia/pytorch:22.07-py3.
To give more information about the environment I'm using, I used the script provided by PyTorch Bug Report on GitHub https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py.

PyTorch version: 1.13.0a0+08820cb
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.23.2
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.7.99
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 510.85.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.13.0a0+08820cb
[pip3] torch-tensorrt==1.2.0a0
[pip3] torchtext==0.13.0a0
[pip3] torchvision==0.14.0a0
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-include               2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.22.4           py38h99721a1_0    conda-forge
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.13.0a0+08820cb          pypi_0    pypi
[conda] torch-tensorrt            1.2.0a0                  pypi_0    pypi
[conda] torchtext                 0.13.0a0                 pypi_0    pypi
[conda] torchvision               0.14.0a0                 pypi_0    pypi

**Comment by narendasan** [comment]
I don't think there is a call to this method from anything in Torch-TRT but this warning fundamentally comes from TensorRT itself. My guess is that there is some legacy TRT code calling this API producing the error but in our case it can safely be ignored.

**Comment by ncomly-nvidia** [comment]
Closing based on https://github.com/pytorch/TensorRT/issues/1248#issuecomment-1210982509
