### ISSUE TITLE
🐛 [Bug] Conversion works in v1.0.0 (desktop pc) but not in v1.0.0+55c3bab4 (Jetson)

### ISSUE THREAD

**Issue by mjack3** [pytorch/TensorRT#1260]
##  Bug Description

TorchScript to TensorRT works correctly in v1.0.0 (desktop computer) but fail in 1.0.0+55c3bab4 (Jetson+JetPack4.6)

## To Reproduce

The code it is the same in my desktop and Jetson, but failling in the second device

1. I trace model 
2. Then, I convert the model to TensorRT32 engine

```
traced_model = torch.jit.trace(model, torch.empty(1, 3, 224, 224, requires_grad=False, device=torch.device('cuda')))
trt_model = ttrt.compile(traced_model, "default",
                          [ttrt.Input((1, 3, 224, 224), dtype=torch.float)],
                          torch.float, truncate_long_and_double=True)
```

`WARNING: [Torch-TensorRT] - Dilation not used in Max pooling converter
Traceback (most recent call last):
  File "eval_time.py", line 57, in <module>
    torch.float, truncate_long_and_double=True)
  File "/home/minitkh/.local/lib/python3.6/site-packages/torch_tensorrt/_compile.py", line 97, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
  File "/home/minitkh/.local/lib/python3.6/site-packages/torch_tensorrt/ts/_compiler.py", line 119, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/conversion/var/Var.cpp:128] Expected isITensor() to be true but got false
Requested ITensor from Var, however Var type is c10::IValue
`

## Expected behavior

In my desktop computer I am using python3.6, pytorch==1.10.0 and torch_tensorrt==1.0.0. So the expected behaviour is  to work without errors. 

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.0.0
 - PyTorch Version (e.g. 1.0): 1.10.0
 - CPU Architecture: Jetson
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Python version: 3.6
 - CUDA version: 10.2
 - GPU models and configuration: Jetson NX

**Comment by narendasan** [comment]
Can you provide the debug logs for both desktop and jetson? You can do this with:

```py
ttrt.logging.set_reportable_log_level(ttrt.logging.Level.Debug)
trt_model = ttrt.compile(traced_model, "default",
                          [ttrt.Input((1, 3, 224, 224), dtype=torch.float)],
                          torch.float, truncate_long_and_double=True)
```

Since this is an issue with 1.0.0, the best advice I have is to upgrade. If it is not possible to upgrade your Jetpack (seems like you are on 4.6) you can backport v1.1.0 to base on PyTorch 1.10.0

**Comment by mjack3** [comment]
Hello, I'll next tuesday.

By the way, as far as I know, torch_tensorrt v1.1.0 does not work in Jetson (NX) with JetPack 4.6. I tried two days ago with Pytorch v1.10.0.

Could you confirm?

Thanks

**Comment by narendasan** [comment]
Yes it does not work out of the box. There is a small patch in lowering you must apply (essentially revert this commit https://github.com/pytorch/TensorRT/commit/c009a1fc5167a9b85818aa94d2a67c9a650b6070) to get it working with 1.10.

**Comment by mjack3** [comment]
Hello @narendasan 

Finally, I updated JP to the production release and I managed the conversion correctly using `torch==1.11.0` and `torch_tensorrt==1.1.0+c2e396a8`. Thank for your help!
