### ISSUE TITLE
🐛 [Bug] Can't install torch_tensorrt python wheel with Bazel and rules_python 

### ISSUE THREAD

**Issue by gdippolito** [pytorch/TensorRT#1262]
##  Bug Description

When installed with `rules_python` the python wheel`torch_tensorrt` is not made available in the runfiles folder and thefore an import error is raised: 
```
ModuleNotFoundError: No module named 'torch_tensorrt'
```

## To Reproduce

Simple repo https://github.com/gdippolito/reproduce-rules-python-bug/tree/main

## Expected behavior

The package is made available to Bazel targets.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): v1.1.0
 - PyTorch Version (e.g. 1.0): 1.12.1
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Linux
 - How you installed PyTorch: pip (via `rules_python`)
 - Build command you used (if compiling from source): N/A
 - Are you using local sources or building from archives: Using python wheel releases
 - Python version: 3.8.12
 - CUDA version: 1.11.0
 - GPU models and configuration: T4
 - Any other relevant information:

## Additional context

Not sure if the issue is with `rules_python` or TorchRT I have created an equivalent ticket in the rules_python repository https://github.com/bazelbuild/rules_python/issues/788

**Comment by narendasan** [comment]
Tried this out and can see the issue but not sure what is causing it. Will investigate further

**Comment by cullenwren-volair** [comment]
Was a solution ever landed for this? I'm experiencing this issue trying to depend on `torch-tensorrt==1.4.0` in a bazel environment using `rules_python`. Is there a different intended way to use `torch-tensorrt` with a bazelified python environment?

**Comment by narendasan** [comment]
Do you have a error or something we can refer to, rules_python has changed significantly since this error was posted

**Comment by cullenwren-volair** [comment]
Sure, it's the same `ModuleNotFoundError: No module named 'torch_tensorrt'` error as in OP. 

Digging a little further into the files bazel has for the run I see that the `pip_deps_torch_tensorrt/site-packages` folder is missing a `torch_tensorrt` folder with the source files:
<img width="259" alt="image" src="https://github.com/pytorch/TensorRT/assets/124718675/81cf9f18-a246-4f3c-aeda-ae76ed92e748">

**Comment by narendasan** [comment]
hmm, so in the original bug, the issue was due to us shipping a BUILD file in the package to make it easier to link the internal C++ libs. We use that file for testing so its still there, maybe you can try removing that from the package by removing it from setup.py / pyproject.toml when you build and see if that helps

**Comment by ShijunK** [comment]
@narendasan  hi, could you provide the path/revision link? I am running into a similar problem, using bazel build system, and add `torch-tensorrt==1.3.0` as dependency, pulling down from pypi. 

The bazel output folder contains only two sub directories: `torch_tensorrt.libs` and `torch_tensorrt-1.3.0.dist-info`. There are no python codes there.
