### ISSUE TITLE
✨[Feature] Collection IO end to end support for TRT engine

### ISSUE THREAD

**Issue by bowang007** [pytorch/TensorRT#1293]
**Is your feature request related to a problem? Please describe.**

Currently Torch-TensorRT is relying on Partitioning to support Tuple/List grouped inputs, which means for some models with Tuple/List input/output, they are not supported end to end. This could also affect performance. So, we should try to implement a change where when we go to construct the inputs to the engine we on the fly group them to be in the form of the graph input so that conversion can work end to end.

**Comment by Christina-Young-NVIDIA** [comment]
Pending PR #1599 .

**Comment by narendasan** [comment]
@gs-olive Can we close this?

**Comment by gs-olive** [comment]
@narendasan I think we should get #1656 merged first - I can set that PR to auto-close this issue.
