### ISSUE TITLE
caffe2

### ISSUE THREAD

**Issue by s-mohaghegh97** [pytorch/TensorRT#1317]
Why don't you install caffe2 with pytorch in NGC container 22.08?

**Comment by ncomly-nvidia** [comment]
Hi @s-mohaghegh97  can you expand on your need for caffe2? We don't actively support it in the latest versions of Torch-TRT.

**Comment by s-mohaghegh97** [comment]
I use caffe2 to export detecron2 model to onnx format.
https://detectron2.readthedocs.io/en/latest/tutorials/deployment.html#caffe2-deployment
