### ISSUE TITLE
🐛 [Bug] Native compilation on Xavier AGX using L4T-Pytorch docker

### ISSUE THREAD

**Issue by SM1991CODES** [pytorch/TensorRT#1318]
## To Reproduce

1.
1.
1.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.1.1
 - PyTorch Version (e.g. 1.0): 1.11
 - CPU Architecture: aarch64
 - OS (e.g., Linux): Linux, Jetpack 5.0.2
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): docker NGC L4T-Pytorch
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version: 11.4
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

I build torch-tensorrt from source on the Xavier AGX inside a L4T-Pytorch docker conatiner.
Build was successful for both Python and C++.
Then I added another user to the docker image.

I can now import torch and see CUDA inside the docker root.
![image](https://user-images.githubusercontent.com/69435296/187047313-4c84f767-c6be-4248-b75c-2c3f92429262.png)

But when I log in as the new user with ssh, I get the following error:
![image](https://user-images.githubusercontent.com/69435296/187047337-63508a14-f01b-4c8e-a761-7f68f3aa717a.png)

Please help

**Comment by narendasan** [comment]
This doesnt seem like an issue with Torch-TensorRT, seems like an issue with your docker setup? Can you at least provide instructions on how to reproduce this issue?

**Comment by SM1991CODES** [comment]
I agree - in this case torch-tensorrt was not the problem.
It turns out on Xavier AGX and Orin, new user needs to be added to video group for cuda stuff to work.

sudo usermod -a -G video $USER

Best Regards
