### ISSUE TITLE
❓ [Question] Using torch-trt to test bert's qat quantitative model

### ISSUE THREAD

**Issue by lixiaolx** [pytorch/TensorRT#1332]
## ❓ Question

When using torch-trt to test Bert's qat quantization ( https://zenodo.org/record/4792496#.YxGrdRNBy3J ) model, I encountered many FakeTensorQuantFunction nodes in the pass, and at the same time triggered many nodes that could not convert TRT, and split the graph into many subgraphs
![image](https://user-images.githubusercontent.com/17673134/188449461-55791f9e-884a-4961-b861-7b82110c0db2.png)

![image](https://user-images.githubusercontent.com/17673134/188449320-cf8e345d-25af-4d0f-b7af-78e94750da73.png)

question:
1. Can you tell me how to explain the nodes that appear in the pass, and how to explain the symbols (^) in front of these nodes?
2. How can these quantization nodes be converted into qat nodes corresponding to torch-trt（ https://github.com/pytorch/TensorRT/blob/master/core/conversion/converters/impl/quantization.cpp ）?

**Comment by ncomly-nvidia** [comment]
@peri044 What nodes are inserted by the [PyT QAT Toolkit](https://github.com/NVIDIA/TensorRT/tree/main/tools/pytorch-quantization)? Are they `FakeTensorQuantFunction` layers?
