### ISSUE TITLE
❓ [Question] Why do you not build & release Windows wheels?

### ISSUE THREAD

**Issue by joeyballentine** [pytorch/TensorRT#1362]
## ❓ Question

Just curious why you only make Linux wheels. It seems like since the last release it totally should have been possible for you guys to pre-build windows wheels. Just curious why this is

**Comment by ncomly-nvidia** [comment]
Hi @joeyballentine currently windows support was added by the community and is experimental. We would need to setup further guides, testing, and infrastructure to put out a consistent & stable windows build. 

We will be doing all of this in the future, but are currently prioritizing other features like the new FX front-end!
