### ISSUE TITLE
🐛 [Bug] aten::unbind converter produces incorrect output dimensions

### ISSUE THREAD

**Issue by mfeliz-cruise** [pytorch/TensorRT#1374]
##  Bug Description
torch.unbind removes the dimension it splits on. The existing converter for aten::unbind preserves the dimension in its output. You can see the difference in the shapes below from the aten::unbind unit tests.
```
jit: [3, 4, 4]
trt: [1, 3, 4, 4]
jit: [3, 4, 4]
trt: [1, 3, 4, 4]

jit: [5]
trt: [5, 1]
```

## To Reproduce

1. Remove the reshapes on the trt outputs from the aten::unbind unit test. You will see that the split dimension is preserved in the converter output and removed in the jit output.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):
 - PyTorch Version (e.g. 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by peri044** [comment]
@mfeliz-cruise Can you let me know which test are you referring to ? 
I ran this one https://github.com/pytorch/TensorRT/blob/main/tests/core/conversion/converters/test_select.cpp#L1176-L1201 and got 
```
===== JIT RESULTS: [3, 4, 4]
===== TRT RESULTS: [3, 4, 4]
```

**Comment by mfeliz-cruise** [comment]
My fix for this was merged in September: https://github.com/pytorch/TensorRT/pull/1373

I think this can be closed.
