### ISSUE TITLE
🐛 [Bug] Using Dockerfile build, setMemoryPoolLimit error

### ISSUE THREAD

**Issue by prazyzheng** [pytorch/TensorRT#1384]
##  Bug Description

INFO: Found 1 target...
[0 / 30] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (6 actions, 0 running)
[6,682 / 6,881] Compiling core/util/trt_util.cpp; 13s processwrapper-sandbox ... (128 actions running)
[6,682 / 6,881] Compiling core/util/trt_util.cpp; 40s processwrapper-sandbox ... (128 actions running)
[6,683 / 6,881] Compiling core/util/trt_util.cpp; 61s processwrapper-sandbox ... (128 actions running)
ERROR: /workspace/torch_tensorrt/src/core/conversion/conversionctx/BUILD:13:11: Compiling core/conversion/conversionctx/ConversionCtx.cpp failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 61 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
core/conversion/conversionctx/ConversionCtx.cpp: In constructor 'torch_tensorrt::core::conversion::ConversionCtx::ConversionCtx(torch_tensorrt::core::conversion::BuilderSettings)':
core/conversion/conversionctx/ConversionCtx.cpp:111:10: error: 'using element_type = class nvinfer1::IBuilderConfig' {aka 'class nvinfer1::IBuilderConfig'} has no member named 'setMemoryPoolLimit'
  111 |     cfg->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kWORKSPACE, settings.workspace_size);
      |          ^~~~~~~~~~~~~~~~~~
core/conversion/conversionctx/ConversionCtx.cpp:111:39: error: 'nvinfer1::MemoryPoolType' has not been declared
  111 |     cfg->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kWORKSPACE, settings.workspace_size);
      |                                       ^~~~~~~~~~~~~~
core/conversion/conversionctx/ConversionCtx.cpp:128:12: error: 'using element_type = class nvinfer1::IBuilderConfig' {aka 'class nvinfer1::IBuilderConfig'} has no member named 'setMemoryPoolLimit'
  128 |       cfg->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kDLA_MANAGED_SRAM, settings.dla_sram_size);
      |            ^~~~~~~~~~~~~~~~~~
core/conversion/conversionctx/ConversionCtx.cpp:128:41: error: 'nvinfer1::MemoryPoolType' has not been declared
  128 |       cfg->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kDLA_MANAGED_SRAM, settings.dla_sram_size);
      |                                         ^~~~~~~~~~~~~~
core/conversion/conversionctx/ConversionCtx.cpp:131:12: error: 'using element_type = class nvinfer1::IBuilderConfig' {aka 'class nvinfer1::IBuilderConfig'} has no member named 'setMemoryPoolLimit'
  131 |       cfg->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kDLA_LOCAL_DRAM, settings.dla_local_dram_size);
      |            ^~~~~~~~~~~~~~~~~~
core/conversion/conversionctx/ConversionCtx.cpp:131:41: error: 'nvinfer1::MemoryPoolType' has not been declared
  131 |       cfg->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kDLA_LOCAL_DRAM, settings.dla_local_dram_size);
      |                                         ^~~~~~~~~~~~~~
core/conversion/conversionctx/ConversionCtx.cpp:134:12: error: 'using element_type = class nvinfer1::IBuilderConfig' {aka 'class nvinfer1::IBuilderConfig'} has no member named 'setMemoryPoolLimit'
  134 |       cfg->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kDLA_GLOBAL_DRAM, settings.dla_global_dram_size);
      |            ^~~~~~~~~~~~~~~~~~
core/conversion/conversionctx/ConversionCtx.cpp:134:41: error: 'nvinfer1::MemoryPoolType' has not been declared
  134 |       cfg->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kDLA_GLOBAL_DRAM, settings.dla_global_dram_size);
      |                                         ^~~~~~~~~~~~~~

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):
 - PyTorch Version (e.g. 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by andi4191** [comment]
Which TensorRT version are you using?
What command did you run for docker build?

**Comment by narendasan** [comment]
@prazyzheng please fill out the information on how you are building and what your system configuration is otherwise it is incredibly hard for us to help you:
```
Environment

    Build information about Torch-TensorRT can be found by turning on debug messages

    Torch-TensorRT Version (e.g. 1.0.0):
    PyTorch Version (e.g. 1.0):
    CPU Architecture:
    OS (e.g., Linux):
    How you installed PyTorch (conda, pip, libtorch, source):
    Build command you used (if compiling from source):
    Are you using local sources or building from archives:
    Python version:
    CUDA version:
    GPU models and configuration:
    Any other relevant information:
```

**Comment by chenzhengda** [comment]
@prazyzheng  Hello, I had the same problem when building torch tensorrt, how did you solve it then? I would be very grateful for your help.

**Comment by prazyzheng** [comment]
> 

![image](https://user-images.githubusercontent.com/41980867/203259702-9aa8bf57-ca0b-4f18-a803-c2e629ceae50.png)
Em, you can download binary file and run it. I can't solve this problem before.

**Comment by chenzhengda** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/41980867/203259702-9aa8bf57-ca0b-4f18-a803-c2e629ceae50.png) Em, you can download binary file and run it. I can't solve this problem before.

I think I've found the problem. The docker build process was trying to fetch tensorrt and cudnn, which were not downloading correctly when using the docker/Dockerfile build(It could be a network problem). The wrong version of tensorrt is being used. Building using locally installed cuDNN & TensorRT works.

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/73685931/203261356-b4e7cab6-22ea-482e-a4d0-db9bc746a1a7.png">
