### ISSUE TITLE
🐛 [Bug] Encountered bug of same layer name when using Torch-TensorRT compile function

### ISSUE THREAD

**Issue by fatemebafghi** [pytorch/TensorRT#1389]
##  Bug Description

Hello every one. I am trying to compile my traced model using torch-tensorrt; In my model I have some tensor.Long values so I had to turn truncate_long_and_double flag true. when compiling with this flag on, I get following error.

![Screenshot from 2022-10-03 17-34-16](https://user-images.githubusercontent.com/91779797/193740762-9a455d81-5c01-4626-b18d-443be51afdf9.png)
I have even tried to dump my programm when compile function crashes by os.abort() but in gdb I don’t see a understandable bt.
I do not know how I can fix the problem. 
My model is curl with SwinIr backbone

![image](https://user-images.githubusercontent.com/91779797/193741387-5c2ff199-7217-4b73-a6a1-9dccf6b0a85c.png)

## Environment

 - Torch-TensorRT Version: (1.2.0)
 - PyTorch Version (e.g. 1.0): '1.12.1'
 - CPU Architecture: 3060 
 - OS (e.g., Linux): Ubuntu 22
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): conda
 - Python version: 3.8
 - CUDA version: 11.3

**Comment by narendasan** [comment]
Can you try in v1.3.0, I believe we should have fixed the clashing names issue there. Reopen if there are still issues
