### ISSUE TITLE
Question about triton example in tutorial

### ISSUE THREAD

**Issue by allen-ash** [pytorch/TensorRT#1396]
Why using platform: "pytorch_libtorch" while model.pt as Torch TensorRT 

> model.pt as platform: "pytorch_libtorch" 

instead of 

> model.pt as platform: "tensorrt_plan" in [serving_torch_tensorrt_with_triton](https://pytorch.org/TensorRT/tutorials/serving_torch_tensorrt_with_triton.html)

**Comment by tanayvarshney** [comment]
Hi @allen-ash

Even after the torch tensorrt compilation, the model is still viewed as TorchScript, using PyTorch to execute the model. Therefore, from Triton's perspective, we still need to use a PyTorch backend.
