### ISSUE TITLE
🐛 [Bug] Cannot import torch_tensorrt after following installation steps

### ISSUE THREAD

**Issue by nrakltx** [pytorch/TensorRT#1398]
##  Bug Description

I want to use `torch_tensorrt` in my Python code. After following the installation steps, I still am not able to use it as it cannot find `libtorch_cuda_cu.so`.
Running `tree / | grep libtorch_cuda_cu.so` also doesn't find anything, which probably means it doesn't actually exist on my computer. Trying solutions of similar issues hasn't worked.
## To Reproduce

 I installed it using the following steps:
1. Install `torch` using pip.
2. Install `nvidia-pyindex` and `nvidia-tensorrt` using pip.
3. `pip install torch_tensorrt -f https://github.com/pytorch/TensorRT/releases/expanded_assets` (as per [here](https://pytorch.org/TensorRT/getting_started/installation.html#installation))
4. (added after the above didn't work) Add `torch_tensorrt` package lib and `tensorrt` package lib to `LD_LIBRARY_PATH`

When importing, I get:
```
Traceback (most recent call last):
  File "step_by_step.py", line 23, in <module>
    import torch_tensorrt
  File "/opt/conda/envs/jojo_env/lib/python3.8/site-packages/torch_tensorrt/__init__.py", line 85, in <module>
    from torch_tensorrt._compile import *
  File "/opt/conda/envs/jojo_env/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 2, in <module>
    from torch_tensorrt import _enums
  File "/opt/conda/envs/jojo_env/lib/python3.8/site-packages/torch_tensorrt/_enums.py", line 1, in <module>
    from torch_tensorrt._C import dtype, DeviceType, EngineCapability, TensorFormat
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
```
## Expected behavior

Importing after following installation steps should work.
## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.2.0
 - PyTorch Version (e.g. 1.0): 1.12.1
 - CPU Architecture: amd64
 - OS (e.g., Linux): Debian 10
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.8.13
 - CUDA version: 11.6
 - GPU models and configuration: 1x T4
 - Any other relevant information:

## Additional context

Using the `pytorch` docker image is not an option due to engineering constraints.

**Comment by narendasan** [comment]
Did you install the cuda 11.3 or cuda 11.6 version of pytorch?

**Comment by nrakltx** [comment]
Yes that was indeed the issue thank you!

**Comment by yunseung-dable** [comment]
@nrakltx have you solved the problem? i'm having a same issue now 😭
