### ISSUE TITLE
✨[Feature] PyPi binaries

### ISSUE THREAD

**Issue by msaroufim** [pytorch/TensorRT#1402]
**Is your feature request related to a problem? Please describe.**
Having to use a custom index is less than ideal if I'd like to for example have this library be part of extra dependencies in my `setup.py`

**Describe the solution you'd like**
 `pip install torch-tensorrt`

**Comment by narendasan** [comment]
We already have the name reserved on pypi but we cannot currently upload builds since some of our dependencies are not compliant with the manylinux spec. This may change in the future and when it does we will push packages there.

**Comment by msaroufim** [comment]
@ncomly-nvidia do you think this is happening this year? I was hoping to create a seamless installation experience for my users in torchserve https://github.com/pytorch/serve/pull/1857

**Comment by msaroufim** [comment]
Thank you @ncomly-nvidia !

**Comment by ncomly-nvidia** [comment]
@msaroufim sure thing. We have been gated by TensorRT's availability on PyPI. It will be available early Nov. so torch-trt should be able to get this up shortly there after. By the end of the year seems reasonable.

Looking forward to your working in torch serve!

**Comment by ychfan** [comment]
Is TensorRT available [here](https://pypi.org/project/nvidia-tensorrt/)?

**Comment by ncomly-nvidia** [comment]
Hi @ychfan yes it is, however, the package is undergoing changes internally which will be finalized in the next TRT release in Nov. Torch-TRT will pickup this package after the changes.

**Comment by Christina-Young-NVIDIA** [comment]
Expected completion by EOW.

**Comment by Christina-Young-NVIDIA** [comment]
Waiting on CI fixes.  Naren following up.

**Comment by Christina-Young-NVIDIA** [comment]
Now unblocked.

**Comment by ncomly-nvidia** [comment]
@narendasan can we please post a package to [PyPI](https://pypi.org/project/torch-tensorrt/). I know there are still outstanding improvements we are considering getting in - can we post v1.3.0 & update to v1.3.1 if needed?

**Comment by narendasan** [comment]
Binaries are uploaded
