### ISSUE TITLE
🐛 [Bug] Error when running fx_trt_example.py

### ISSUE THREAD

**Issue by agunapal** [pytorch/TensorRT#1405]
##  Bug Description

Error when running [fx_trt_example.py
](https://github.com/pytorch/TensorRT/blob/master/examples/fx/fx2trt_example.py)

## To Reproduce

1. Start a docker container with the following command 
`docker run --gpus all -it --rm -v local_dir:container_dir nvcr.io/nvidia/pytorch:22.09-py3`
2. Run the script `python fx2trt_example.py`

Getting the following error
```

    splitter = TRTSplitter(traced, inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/fx/tools/trt_splitter.py", line 64, in __init__
    settings = TRTSplitterSetting()
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/fx/tools/trt_splitter.py", line 52, in __init__
    self.exclude_support_node_name: set = set(self.op_lowering_disallow_list)
AttributeError: 'TRTSplitterSetting' object has no attribute 'op_lowering_disallow_list'
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Docker : nvcr.io/nvidia/pytorch:22.09-py3
 - OS (e.g., Linux): Ubuntu18:04

**Comment by yinghai** [comment]
@wushirong could you take a look?

**Comment by frank-wei** [comment]
@agunapal  contacted me internally. We have solved the issue by using fx only installation. The reason ngc pytorch 22.09 does not work is that it contains torch-tensorRT 1.1.0 which does not contain fx path yet. 
I think we can close this issue.
