### ISSUE TITLE
🐛 [Bug] Routine pip install of torch-tensorrt leads to ImportError on Ubuntu

### ISSUE THREAD

**Issue by IncrediBlame** [pytorch/TensorRT#1436]
##  Bug Description

Hi, I tried to install **torch-tensorrt** through **pip** in a newly created environment in Ubuntu 22.04 LTS. Environment is created with **venv**, Python version 3.10.6.

I noticed that after the packages are installed **torch-tensorrt** throws errors like
`ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory`, 
where the missing library varies in different situations: **libtorch_cuda_cu.so**, **libcudart.so.11.0**, **libnvinfer.so.8**, etc…

I think i figured out what the problem is. When **pip** tries to install **torch-tensorrt** it pulls **torch==1.12.1** (I didn't install **torch** beforehand, as I noticed **torch-tensorrt** pulls this version on top of the one you have), but with the wrong Cuda library, in my case **torch==1.12.1+cu102** (checked with `torch.__version__`), while it seems Cuda 11.0+ is required for **torch-tensorrt**. So when i manually installed **torch==1.12.1+cu113** all the errors disappeared and the package  worked as expected.

I think it's a bug in the requirements somewhere. If not, ignore me pls. I can see this `torch<1.13.0,>=1.12.0+cu116` when **pip**-ing **torch-tensorrt**, but it still brings me **torch==1.12.1+cu102**.

## To Reproduce

Normal routine:
1. Make a new environment in **venv**
2. `pip install nvidia-pyindex`
3. `pip install nvidia-tensorrt`
4. `pip install torch-tensorrt==1.2.0 --find-links https://github.com/pytorch/TensorRT/releases/expanded_assets/v1.2.0`
5. `import torch_tensorrt`
6. Results in `ImportError`

Alternatively:
1. Make a new environment in **venv**
2. `pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113`
3. `pip install nvidia-pyindex`
4. `pip install nvidia-tensorrt`
5. `pip install torch-tensorrt==1.2.0 --find-links https://github.com/pytorch/TensorRT/releases/expanded_assets/v1.2.0`
6. `import torch_tensorrt`
7. No errors

## Expected behavior

No import errors expected.

## Environment

 - Torch-TensorRT Version: **1.2.0**
 - PyTorch Version: **1.12.1** (should be **+cu11*** but **+cu102** gets installed)
 - CPU Architecture: **Intel Core i5 5200U**
 - OS: Ubuntu **22.04 LTS**
 - How you installed PyTorch: `pip install torch-tensorrt==1.2.0 --find-links https://github.com/pytorch/TensorRT/releases/expanded_assets/v1.2.0` pulls pytorch version it needs.
 - Python version: **3.10.6**
 - CUDA version: **11.7** by **nvidia-smi**
 - GPU models and configuration: **GM108M [GeForce 940M]**
 - Any other relevant information: the problem is **solvable**, but looks like a bug in the requirements

**Comment by narendasan** [comment]
Not sure if pip is able to support both version ranges and also handle PyTorch's specific convention for specific cuda versions. We want the range to let users install patch releases that come out after Torch-TensorRT is released without pip reporting version conflicts. We could probably amend the instructions to have an explicit step to install torch beforehand.

**Comment by IncrediBlame** [comment]
I'm not sure how requirements are passed to pip, but can't something like this be used?
```
--extra-index-url https://download.pytorch.org/whl/cu116
torch<1.13.0,>=1.12.0
```

**Comment by narendasan** [comment]
I am working on moving the python package to use pyproject.toml / pep 508 so looking for a way to specify this there
