### ISSUE TITLE
🐛 [Bug] Non-zero bias term for torch.nn.Linear causes engine building to fail using FX frontend (release/1.3)

### ISSUE THREAD

**Issue by frank-wei** [pytorch/TensorRT#1444]
##  Bug Description

One fx test is failing on the release/1.3 branch

## To Reproduce

1. pytest test_fuse_permute_linear_trt.py 

## Expected behavior
Here is the debug process:
1. I simplified the test to the version below
2. The test will fail if self.linear2.bias.data.fill_() with non-zero. If we filled it with zero, then test is good.
3. I further checked that self.linear1.bias.data.fill_(1) does not affect the test
4. The bias value is printed out in [converter function](https://github.com/pytorch/TensorRT/blob/master/py/torch_tensorrt/fx/converters/acc_ops_converters.py#L52) and it is under expectation with value=1 as shown below:
===bias= Parameter containing:
tensor([1., 1.], requires_grad=True)
5. Here is the output comparison. TRT output is 5 while ref is 6. bias is missed in the calculation.
==ref= tensor([[[6., 6.],
         [6., 6.]]])
==trt= tensor([[[5., 5.],
         [5., 5.]]], device='cuda:0') 

Conclusion: this test works well in previous TRT versions. The root cause seems that the linear 2 bias is neglected. 
```
def test_multi_fuse_permute_linear(self):
        """
        Fusion when permute output is shared by multiple linears
        """
    
        class TestModule(torch.nn.Module):
            def __init__(self, in_features, out_features):
                super().__init__()
                self.linear1 = torch.nn.Linear(in_features, out_features)
                self.linear2 = torch.nn.Linear(in_features, out_features)
                self.linear1.weight.data.fill_(1)
                self.linear1.bias.data.fill_(1)
                self.linear2.weight.data.fill_(1)
                self.linear2.bias.data.fill_(1)   <=========test fails if bias is non-zero. If bias is set to 0, test succeeds. 
    
            def forward(self, x):
                y = x.permute(0, 2, 1)
                return self.linear1(y) + self.linear2(y)
    
        inputs = [torch.ones(1, 2, 2)]
    
 
       self.run_test(
            TestModule(2, 2),
            inputs,
            {trt_transposed_linear},
            apply_passes=[fuse_permute_linear],
            test_implicit_batch_dim=False,
        )

```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 8.5
 - PyTorch Version (e.g. 1.0): 1.13
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by frank-wei** [comment]
I reproduced this test on https://app.circleci.com/pipelines/github/pytorch/TensorRT/1304/workflows/ef298775-40a3-4f78-8da8-3318789a8908/jobs/6365

**Comment by narendasan** [comment]
@peri044 can you take a look here?

**Comment by gs-olive** [comment]
I was able to reproduce the issue and investigate the cause further, and it seems that changing the shape of the bias term affects the result. Specifically, replacing the following line in the test case makes it work on my machine, interestingly:
```python
self.linear2.bias.data.fill_(1)
### REPLACED WITH ###
self.linear2.bias = torch.nn.Parameter(torch.tensor(1.))
```
The default shape of the bias in this case is `(2,)`, so it seems the shape of the bias term in the second linear argument (`linear2`) is playing a role in the issue. I will continue to investigate the issue

**Comment by peri044** [comment]
Thanks @frank-wei  George and I verified this and this seems to be a regression. We have escalated it internally.

**Comment by frank-wei** [comment]
thanks for your investigation @peri044  and @gs-olive . It is interesting for George's experiment. I can repro it. Since its initial size is (1,1) compared with default (1,2) and this create different final output which seems very weird.

**Comment by narendasan** [comment]
Internal tracker: nvbugs/3871266

**Comment by narendasan** [comment]
We should replace fully_connected here with matmul + add https://github.com/pytorch/TensorRT/blob/a1498ea7cf72afee86acef364cbf3422c11f10c6/py/torch_tensorrt/fx/converters/linear.py#L33

This may address this issue.

**Comment by frank-wei** [comment]
> We should replace fully_connected here with matmul + add
> 
> https://github.com/pytorch/TensorRT/blob/a1498ea7cf72afee86acef364cbf3422c11f10c6/py/torch_tensorrt/fx/converters/linear.py#L33
> 
> This may address this issue (at least partially) and is necessary as fully_connected is deprecated.

I may miss the doc. Where is it documented that fully_connected is deprecated?

**Comment by narendasan** [comment]
https://docs.nvidia.com/deeplearning/tensorrt/operators/docs/FullyConnected.html

**Comment by frank-wei** [comment]
> TensorRT/py/torch_tensorrt/fx/converters/linear.py

Thanks for giving the pointer.
For this test, we are using matmul+add as in https://github.com/pytorch/TensorRT/blob/a1498ea7cf72afee86acef364cbf3422c11f10c6/py/torch_tensorrt/fx/converters/acc_ops_converters.py#L51

**Comment by gs-olive** [comment]
As a side note, I am not seeing the issue when the model is compiled via TorchScript, in TRT 8.5. The outputs appear to agree, potentially because the fusion causing this discrepancy may not be used here. Code attached below:

```python
model = TestModule(2, 2).eval().cuda()
scripted_model = torch.jit.script(model)
compile_settings = {
    "inputs": [
        torch_tensorrt.Input((1, 2, 2))
    ],
    "enabled_precisions": {torch.float},
}
trt_ts_module = torch_tensorrt.ts.compile(scripted_model, **compile_settings)

input_data = torch.ones((1, 2, 2), device="cuda:0")
pytorch_out = model(input_data).detach()
torch_tensorrt_out = trt_ts_module(input_data)

print("PyTorch output: \n", pytorch_out)
print("Torch-TensorRT output: \n", torch_tensorrt_out)

"""
Prints:
PyTorch output: 
 tensor([[[6., 6.],
         [6., 6.]]], device='cuda:0)
Torch-TensorRT output: 
 tensor([[[6., 6.],
         [6., 6.]]], device='cuda:0')
"""
```

**Comment by Christina-Young-NVIDIA** [comment]
TRT 8.5.3 to fix.

**Comment by Christina-Young-NVIDIA** [comment]
Pending 8.5.3.

**Comment by Christina-Young-NVIDIA** [comment]
Still blocked by TRT 8.5.3 expected early January 2023.

**Comment by Christina-Young-NVIDIA** [comment]
Code-frozen EA build available.  Dheeraj to check.

**Comment by Christina-Young-NVIDIA** [comment]
Dheeraj still waiting for a build from TRT.

**Comment by Christina-Young-NVIDIA** [comment]
TRT 8.5.3 is now available.

**Comment by frank-wei** [comment]
Due to our resources' limit, we prefer to test the TRT8.6 if it is approaching.

**Comment by hl475** [comment]
With rtol=5e-3 and atol=2e-3, the test is passed
