### ISSUE TITLE
❓ [Question] How do you compile for multiple GPU architectures?

### ISSUE THREAD

**Issue by dfung** [pytorch/TensorRT#1449]
## ❓ Question

How do you compile for multiple GPU architectures?  Or do you need to compile one torchscript per architecture?

**Comment by narendasan** [comment]
Right now it is one TorchScript per GPU architecture.

**Comment by sardanian** [comment]
Is there a way to see how they compile different on each GPU architecture? I am getting different results between a 3090 and a 4090 and want to see what is different and how it is affecting accuracy.

**Comment by narendasan** [comment]
You can use the layer inspector feature added in 1.3 to see the different resultant engines
