### ISSUE TITLE
Create RFC for plugin support in FX

### ISSUE THREAD

**Issue by narendasan** [pytorch/TensorRT#1495]
See AHA! description.

Previous plugin RFC

**Comment by Christina-Young-NVIDIA** [comment]
Pending review from Dheeraj.

**Comment by narendasan** [comment]
RFC can found here: https://github.com/pytorch/TensorRT/discussions/1590

**Comment by Christina-Young-NVIDIA** [comment]
Expecting to complete sprint that started 1/30.
