### ISSUE TITLE
❓ [Question] How to save and load compiled model from torch-tensorrt

### ISSUE THREAD

**Issue by MartinPedersenpp** [pytorch/TensorRT#1508]
I am working on a Jetson Xavier NX16 and using torch-tensorrt.compile(model, "default", input, enable_optimization) every time I restart my program seems like it is just doing the same tedious task over and over.
Is there not a way for torch-tensorrt to load the serialized engine created by  torch_tensorrt.convert_method_to_trt_engine or is it only on the CXX backend API?
How would I go about saving and loading a compiled model?

Okay, so I used print(dir(comp_model)) and saw that the model had a save function. I tried using it and figured out after a friendly pop up, that I should load it with torch.jit.load and it works.
Is this an okay solution or are there some kind of insecurities with it?

**Comment by narendasan** [comment]
yes, save the compiled module with `torch.save` or `torch.jit.save`

**Comment by MartinPedersenpp** [comment]
> yes, save the compiled module with `torch.save` or `torch.jit.save`

Sorry for not closing it myself, but thanks for the confirmation 👍🏼
