### ISSUE TITLE
✨[Feature] PTQ support for FX front-end

### ISSUE THREAD

**Issue by collinmccarthy** [pytorch/TensorRT#1514]
**Is your feature request related to a problem? Please describe.**
I currently have an FX workflow, but to use PTQ I need to also get my models to compile with TS, and it's hard to maintain compatibility for both. I tried overriding the `TRTInterpreter.run` to set the int8_calibrator field of the builder config, but I get the following error:

```console
builder_config.int8_calibrator = int8_calibrator
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: tensorrt.tensorrt.IBuilderConfig, arg1: tensorrt.tensorrt.IInt8Calibrator) -> None

Invoked with: <tensorrt.tensorrt.IBuilderConfig object at 0x7fabd4df48f0>, <torch_tensorrt.ptq.Int8EntropyCalibrator2 object at 0x7fabdbd68680>
```

**Describe the solution you'd like**
I would like to be able to pass in a `DataLoaderCalibrator` object to `TRTInterpreter.run` so I can perform PTQ with the FX workflow.

**Describe alternatives you've considered**
The alternative is to use the TS workflow for PTQ, or (correctly) override the `TRTInterpreter.run` function myself (e.g. fix the error above).

**Comment by collinmccarthy** [comment]
I would also be fine with just supporting PTQ for `torch_tensorrt.fx.compile` (for either the regular FX or experimental FX runtime) without working about the `TRTInterpreter` itself.

**Comment by peri044** [comment]
@ncomly-nvidia  Tagging for Feature request
