### ISSUE TITLE
🐛 Bug v.1.2.0 and v.1.3.0 can not be installed

### ISSUE THREAD

**Issue by mjack3** [pytorch/TensorRT#1516]
##  Bug Description

If I try to install Pytorch/TensorRT I get the next error:
`ERROR: Could not find a version that satisfies the requirement torch-tensorrt==1.2.0 (from versions: 0.0.0, 0.0.0.post1)
ERROR: No matching distribution found for torch-tensorrt==1.2.0`

## To Reproduce

1. `pip3 install nvidia-pyindex`
2. `pip3 install nvidia-tensorrt`
3. `pip3 install torch-tensorrt==<VERSION> -f https://github.com/pytorch/TensorRT/releases/expanded_assets/<VERSION>`

For VERSION, i tried `1.2.0` and `v1.2.0`
I have also tried `pip3 install torch-tensorrt==<VERSION> -f https://github.com/pytorch/TensorRT/releases/<VERSION>`

## Expected behavior

torch-tensorrt should be installed

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g. 1.0): 1.11
 - OS (e.g., Linux): Ubuntu 22
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): conda
 - Python version: 3.8
 - CUDA version: 11.8
 - GPU models and configuration: RTX3090

**Comment by sardanian** [comment]
I think you need to do 1.2.0 first and then v1.2.0 in the links
pip install torch-tensorrt==1.2.0 --find-links https://github.com/pytorch/TensorRT/releases/expanded_assets/v1.2.0

I am unable to install 1.3.0 though

**Comment by mjack3** [comment]
Now worked. Thank

`pip3 install torch-tensorrt==v1.2.0 -f https://github.com/pytorch/TensorRT/releases/expanded_assets/v1.2.0
`
