### ISSUE TITLE
🐛 [Bug] UserWarning: acc_tracer does not support currently support models for training. Calling eval on model before tracing.

### ISSUE THREAD

**Issue by 1559588143** [pytorch/TensorRT#1520]
##  Bug Description

I got the `UserWarning: acc_tracer does not support currently support models for training. Calling eval on model before tracing.` even though I had invoked `eval` on the module.

## To Reproduce

```python
import torch
from torch import nn
from torch.nn import functional as F
from torch.nn.parameter import Parameter
from torch_tensorrt.fx import compile


class MyPReLU(nn.Module):
    """FX has no converter for nn.PReLU yet."""
    def __init__(self, num_parameters=1, init=0.25):
        super(MyPReLU, self).__init__()
        self.weight = Parameter(torch.empty(num_parameters).fill_(init))

    def forward(self, input):
        return F.relu(input) - self.weight.reshape(1, -1, 1, 1) * F.relu(-input)


class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.m = MyPReLU()

    def forward(self, x):
        return self.m(x)


if __name__ == '__main__':
    device = torch.device('cuda')
    input = torch.randn(1, 1, 2, 2, dtype=torch.half, device=device)

    mod = MyModule().eval().requires_grad_(False).to(device).half()
    trt_mod = compile(mod, [input], min_acc_module_size=1, explicit_batch_dimension=True, dynamic_batch=False)

    print(f'\n input: \n {input}')
    print(f'\n output from mod: \n {mod(input)}')
    print(f'\n output from trt_mod: \n {trt_mod(input)}')
```

## Expected behavior

No warning occurs.

## Environment

 - Torch-TensorRT Version (e.g. 1.0.0): 1.3.0
 - PyTorch Version (e.g. 1.0): 1.13.0+cu117
 - CPU Architecture:
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.10.8
 - CUDA version: 11.7
 - GPU models and configuration:
 - Any other relevant information:

**Comment by yinghai** [comment]
Maybe put the lowering processing in `with torch.inference_mode():` context?
