### ISSUE TITLE
[BUG] Error While installing Torch-tensorrt

### ISSUE THREAD

**Issue by SP-Amrith-Shrivas** [pytorch/TensorRT#1525]
I installed Tensor Rt for Cuda 11.6 but i need to install torch-tensorrt==1.2.0. My NVIDIA-tensorrt version is 8.4 and pytorch version is 1.13.0 . So i installed torch-tensorrt==1.2.0 as per the instruction in GitHub. But received error as

ERROR: Could not find a version that satisfies the requirement torch-tensorrt==1.2.0 (from versions: 0.0.0, 0.0.0.post1)
ERROR: No matching distribution found for torch-tensorrt==1.2.0

Help me out.!

**Comment by mjack3** [comment]
use v1.2.0

**Comment by narendasan** [comment]
pip3 install torch-tensorrt==1.2.0 -f https://github.com/pytorch/TensorRT/releases/expanded_assets/v1.2.0 

Similarly for 1.3.0

pip3 install torch-tensorrt==1.3.0 -f https://github.com/pytorch/TensorRT/releases/expanded_assets/v1.3.0

**Comment by SP-Amrith-Shrivas** [comment]
> 

Hi Tried the same thing but got another error while import torch_tensorrt. The error is:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bmw/anaconda3/envs/amrith_aimet/lib/python3.8/site-packages/torch_tensorrt/__init__.py", line 85, in <module>
    from torch_tensorrt._compile import *
  File "/home/bmw/anaconda3/envs/amrith_aimet/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 2, in <module>
    from torch_tensorrt import _enums
  File "/home/bmw/anaconda3/envs/amrith_aimet/lib/python3.8/site-packages/torch_tensorrt/_enums.py", line 1, in <module>
    from torch_tensorrt._C import dtype, DeviceType, EngineCapability, TensorFormat
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

**Comment by mjack3** [comment]
You need ha e installed the dependences specified in the TensorRt page.

Then, install the 3 python libraries (pyindex, tensorrt and torch_tensorrt) :)

**Comment by SP-Amrith-Shrivas** [comment]
> You need to install the dependences specified in the TensorRt page.
> 
> Then, install the 3 python libraries (pyindex, tensorrt and torch_tensorrt) :)

Thank you . Done with the bug.. The problem is pytorch version..!

**Comment by SP-Amrith-Shrivas** [comment]
Thank you . Done with the bug.. The problem is pytorch version..!
