### ISSUE TITLE
[Bug] Invoke error while implementing TensorRT on pytorch

### ISSUE THREAD

**Issue by SP-Amrith-Shrivas** [pytorch/TensorRT#1535]
## ❓ Question

Got the error while using tensorrt on pytorch pretrained resnet model. what is this error and how to solve it.

## Error
Traceback (most recent call last):
  File "pretrained_resnet.py", line 116, in <module>
    trt_model_32 = torch_tensorrt.compile(traced, inputs=[torch_tensorrt.Input(
  File "/home/am/anaconda3/envs/amrith/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 125, in compile
    return torch_tensorrt.ts.compile(
  File "/home/am/anaconda3/envs/amrith/lib/python3.8/site-packages/torch_tensorrt/ts/_compiler.py", line 136, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
TypeError: compile_graph(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Module, arg1: torch_tensorrt._C.ts.CompileSpec) -> torch::jit::Module

Invoked with: <torch.ScriptModule object at 0x7fb5cc5c78f0>, <torch_tensorrt._C.ts.CompileSpec object at 0x7fb5cc47d8b0>

**Comment by SP-Amrith-Shrivas** [comment]
> ## question Question
> 
> Got the error while using tensorrt on pytorch pretrained resnet model. what is this error and how to solve it.
> ## Error
> 
> Traceback (most recent call last): File "pretrained_resnet.py", line 116, in trt_model_32 = torch_tensorrt.compile(traced, inputs=[torch_tensorrt.Input( File "/home/bmw/anaconda3/envs/amrith_aimet/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 125, in compile return torch_tensorrt.ts.compile( File "/home/bmw/anaconda3/envs/amrith_aimet/lib/python3.8/site-packages/torch_tensorrt/ts/_compiler.py", line 136, in compile compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec)) TypeError: compile_graph(): incompatible function arguments. The following argument types are supported: 1. (arg0: torch::jit::Module, arg1: torch_tensorrt._C.ts.CompileSpec) -> torch::jit::Module
> 
> Invoked with: <torch.ScriptModule object at 0x7fb5cc5c78f0>, <torch_tensorrt._C.ts.CompileSpec object at 0x7fb5cc47d8b0>
> ## Additional context

I could under where is the problem is..

**Comment by peri044** [comment]
Can you provide more context ? 

1) Full compilation line of your model 
2) Which precision ? 
3) Repro script if possible? 
4) We frequently test resnet model compilation here : https://github.com/pytorch/TensorRT/blob/master/tests/py/models/test_models.py#L13-L35 You can run this to see what's different from your model

**Comment by SP-Amrith-Shrivas** [comment]
trt_model_32 = t_trt.compile(traced,
                                 inputs=[t_trt.Input([1, 3, 32, 32])],
                                 enabled_precisions={t_trt.dtype.half}
This is my compilation code and precision i am trying for both float16 and int8. I tried Normal script from tensorrt blogs for Resnet50

This to benchmark on resnet model on imagenet dataset on both precisions..
