### ISSUE TITLE
✨[Feature] Improve Integer Range Specification for `Input` class

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#1543]
Adding FX support for specifying integer range + adding lowering pass to support int64 inputs with automatic casting.

1/2 MVP + Phase 1 of RFC #1425 

See RFC for details.

**Comment by gs-olive** [comment]
Addressed by PR #1551, Phase 1 already exists as discussed in https://github.com/pytorch/TensorRT/discussions/1425#discussioncomment-4661390

**Comment by Christina-Young-NVIDIA** [comment]
Also a duplicate of 1531.
