### ISSUE TITLE
✨[Feature] Add sample tensor field to `Input` class

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#1544]
Phase 2 of RFC #1425 

See RFC for details.

**Comment by narendasan** [comment]
@gs-olive Is this not already supported via the top level api? Does the internal Input need access to a sample tensor?

**Comment by gs-olive** [comment]
The top-level API does support sample tensor inputs, but it only uses them to parse fields including shapes and data types. The intent of the original RFC was to allow these sample inputs to be propagated through to the partitioning phase and used as inputs for the dry-run, similar to `torch.jit.trace()` semantics. At this time, since input tensor domains are currently supported as of PR #1537, it may not be worth the additional effort to pass full Tensors from Python to C++ for the dry-run, as the benefit of this could be marginal above specifying an input domain. Open to thoughts on this.

**Comment by gs-olive** [comment]
After discussion, RFC #1425 has been marked as Implemented due to PR #1537 and this issue will be closed for now.
