### ISSUE TITLE
✨[Feature] Will we have NGC L4T PyTorch images with built-in Torch-TensorRT?

### ISSUE THREAD

**Issue by huyaoyu** [pytorch/TensorRT#1564]
It is really nice to know that recent [NGC PyTorch images](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) have Torch-TensorRT by default. 

However, do you consider also making Torch-TensorRT available to the L4T versions of the NGC images? Like the [NGC L4T PyTorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-pytorch) or [NGC L4T ML](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-ml).

If the development team of Torch-TensorRT has no direct contact with the team of the NGC L4T images, do you happen to know where should I file this request then?

Thank you!

**Comment by peri044** [comment]
We are planning to release a Jetson compatible torch_tensorrt release soon in early January.

**Comment by huyaoyu** [comment]
Thank you! Looking forward to that!

Is it going to be embedded in NGC images?

**Comment by peri044** [comment]
Nope. We plan to make it like a github release similar to our existing github releases of Torch-TRT
