### ISSUE TITLE
🐛 [Bug] Unable to compile Resample layer when using Torch-TensorRT

### ISSUE THREAD

**Issue by dathudeptrai** [pytorch/TensorRT#1596]
##  Bug Description

Trying to run the following code but got bug.

## To Reproduce

```
import torchaudio.transforms as T

resample = T.Resample(16000, 32000, "kaiser_window", 12, 0.5, 4.663800127934911, dtype=torch.float32).cuda()
resample(torch.randn(1, 1, 32000).cuda())
resample = torch.jit.script(resample)
trt_ts_module = torch_tensorrt.compile(
 resample, 
 inputs=[
     torch_tensorrt.Input(
          min_shape=[1, 1, 16000],
          opt_shape=[1, 1, 32000],
          max_shape=[1, 1, 64000],
          dtype=torch.float32)
  ],
  enabled_precisions={torch.float32},
  truncate_long_and_double=True
)

```

## Expected behavior

Able to convert to TensorRT

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.3.0a0
 - PyTorch Version (e.g. 1.0): 1.14.0a0+410ce96
 - CPU Architecture: 
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): docker pull nvcr.io/nvidia/pytorch:22.12-py3
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.10
 - CUDA version: 11.8
 - GPU models and configuration: T4 Google Cloud
 - Any other relevant information:

## Additional context

```
RuntimeError                              Traceback (most recent call last)
Cell In[55], line 2
      1 # with torch_tensorrt.logging.debug():
----> 2 trt_ts_module = torch_tensorrt.compile(
      3    resample, 
      4    inputs=[
      5        torch_tensorrt.Input( # Specify input object with shape and dtype
      6             min_shape=[1, 1, 16000],
      7             opt_shape=[1, 1, 32000],
      8             max_shape=[1, 1, 64000],
      9             dtype=torch.float32)
     10     ],
     11     enabled_precisions={torch.float32},
     12     truncate_long_and_double=True
     13 )

File /usr/local/lib/python3.8/dist-packages/torch_tensorrt/_compile.py:125, in compile(module, ir, inputs, enabled_precisions, **kwargs)
    120         logging.log(
    121             logging.Level.Info,
    122             "Module was provided as a torch.nn.Module, trying to script the module with torch.jit.script. In the event of a failure please preconvert your module to TorchScript",
    123         )
    124         ts_mod = torch.jit.script(module)
--> 125     return torch_tensorrt.ts.compile(
    126         ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs
    127     )
    128 elif target_ir == _IRType.fx:
    129     if (
    130         torch.float16 in enabled_precisions
    131         or torch_tensorrt.dtype.half in enabled_precisions
    132     ):

File /usr/local/lib/python3.8/dist-packages/torch_tensorrt/ts/_compiler.py:136, in compile(module, inputs, input_signature, device, disable_tf32, sparse_weights, enabled_precisions, refit, debug, capability, num_avg_timing_iters, workspace_size, dla_sram_size, dla_local_dram_size, dla_global_dram_size, calibrator, truncate_long_and_double, require_full_compilation, min_block_size, torch_executed_ops, torch_executed_modules)
    110     raise ValueError(
    111         f"require_full_compilation is enabled however the list of modules and ops to run in torch is not empty. Found: torch_executed_ops: {torch_executed_ops}, torch_executed_modules: {torch_executed_modules}"
    112     )
    114 spec = {
    115     "inputs": inputs,
    116     "input_signature": input_signature,
   (...)
    133     },
    134 }
--> 136 compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
    137 compiled_module = torch.jit._recursive.wrap_cpp_module(compiled_cpp_mod)
    138 return compiled_module

RuntimeError: [Error thrown at core/conversion/converters/impl/conv_deconv.cpp:115] Expected orig_dims.nbDims > 2 to be true but got false
Unable to create convolution layer from node: %6 : Tensor = aten::_convolution(%5, %7, %3, %8, %11, %8, %10, %11, %4, %10, %10, %10, %10)

```

@narendasan

**Comment by narendasan** [comment]
@apbose Can you look into this, seems like another case of the issue you were working on

**Comment by dathudeptrai** [comment]
@apbose any update? and thank you very much.

**Comment by apbose** [comment]
I started looking into the issue. The torch-tensorRT main branch currently supports the Torch nightly build with torch==2.0.0.dev20230103+cu117 and I am installing the nightly torch audio==2.0.0.dev20230103+cu117, instead of the above 1.14 however it fails in importing with the error-  undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

**Comment by dathudeptrai** [comment]
@apbose I forgot the fact is that I did not able to install torch audio as well and yield the exactly bug you got. Instead, I copied the original code here (https://pytorch.org/audio/stable/_modules/torchaudio/transforms/_transforms.html#Resample) without the need of installing torch audio. Hope this help. @apbose

**Comment by dathudeptrai** [comment]
`class Resample(torch.nn.Module):
    r"""Resample a signal from one frequency to another. A resampling method can be given.

    .. devices:: CPU CUDA

    .. properties:: Autograd TorchScript

    Note:
        If resampling on waveforms of higher precision than float32, there may be a small loss of precision
        because the kernel is cached once as float32. If high precision resampling is important for your application,
        the functional form will retain higher precision, but run slower because it does not cache the kernel.
        Alternatively, you could rewrite a transform that caches a higher precision kernel.

    Args:
        orig_freq (int, optional): The original frequency of the signal. (Default: ``16000``)
        new_freq (int, optional): The desired frequency. (Default: ``16000``)
        resampling_method (str, optional): The resampling method to use.
            Options: [``sinc_interpolation``, ``kaiser_window``] (Default: ``"sinc_interpolation"``)
        lowpass_filter_width (int, optional): Controls the sharpness of the filter, more == sharper
            but less efficient. (Default: ``6``)
        rolloff (float, optional): The roll-off frequency of the filter, as a fraction of the Nyquist.
            Lower values reduce anti-aliasing, but also reduce some of the highest frequencies. (Default: ``0.99``)
        beta (float or None, optional): The shape parameter used for kaiser window.
        dtype (torch.device, optional):
            Determnines the precision that resampling kernel is pre-computed and cached. If not provided,
            kernel is computed with ``torch.float64`` then cached as ``torch.float32``.
            If you need higher precision, provide ``torch.float64``, and the pre-computed kernel is computed and
            cached as ``torch.float64``. If you use resample with lower precision, then instead of providing this
            providing this argument, please use ``Resample.to(dtype)``, so that the kernel generation is still
            carried out on ``torch.float64``.

    Example
        >>> waveform, sample_rate = torchaudio.load("test.wav", normalize=True)
        >>> transform = transforms.Resample(sample_rate, sample_rate/10)
        >>> waveform = transform(waveform)
    """

    def __init__(
        self,
        orig_freq: int = 16000,
        new_freq: int = 16000,
        resampling_method: str = "sinc_interpolation",
        lowpass_filter_width: int = 6,
        rolloff: float = 0.99,
        beta: Optional[float] = None,
        *,
        dtype: Optional[torch.dtype] = None,
    ) -> None:
        super().__init__()

        self.orig_freq = orig_freq
        self.new_freq = new_freq
        self.gcd = math.gcd(int(self.orig_freq), int(self.new_freq))
        self.resampling_method = resampling_method
        self.lowpass_filter_width = lowpass_filter_width
        self.rolloff = rolloff
        self.beta = beta

        if self.orig_freq != self.new_freq:
            kernel, self.width = _get_sinc_resample_kernel(
                self.orig_freq,
                self.new_freq,
                self.gcd,
                self.lowpass_filter_width,
                self.rolloff,
                self.resampling_method,
                beta,
                dtype=dtype,
            )
            self.register_buffer("kernel", kernel)

[[docs]](https://pytorch.org/audio/stable/generated/torchaudio.transforms.Resample.html#torchaudio.transforms.Resample.forward)    def forward(self, waveform: Tensor) -> Tensor:
        r"""
        Args:
            waveform (Tensor): Tensor of audio of dimension (..., time).

        Returns:
            Tensor: Output signal of dimension (..., time).
        """
        if self.orig_freq == self.new_freq:
            return waveform
        return _apply_sinc_resample_kernel(waveform, self.orig_freq, self.new_freq, self.gcd, self.kernel, self.width)`

**Comment by apbose** [comment]
Thanks @dathudeptrai. That helps, I could reproduce the error.

**Comment by Christina-Young-NVIDIA** [comment]
PR 1624
