### ISSUE TITLE
🐛 [Bug] Model Decoder Failure

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#1616]
**Summary:** Model failing on `trt::const` with NoneType input, and other errors.

See NVBugs for more details.

**Comment by gs-olive** [comment]
Applying #1619 and #1623 together resolve the compilation error on my machine

**Comment by Christina-Young-NVIDIA** [comment]
2 open PRs need review.  George to find someone to review and close during sprint starting 1/30.
