### ISSUE TITLE
[fx2trt] explicit_precision, strict_type_constraints and max_workspace_size are deprecated

### ISSUE THREAD

**Issue by HolyWu** [pytorch/TensorRT#1626]
https://github.com/pytorch/TensorRT/blob/a3436504714dc40885e80f70c93478d263eb1df1/py/torch_tensorrt/fx/fx2trt.py#L56

https://github.com/pytorch/TensorRT/blob/a3436504714dc40885e80f70c93478d263eb1df1/py/torch_tensorrt/fx/fx2trt.py#L237

`EXPLICIT_PRECISION` is marked as [DEPRECATED] on https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Builder.html#tensorrt.NetworkDefinitionCreationFlag. TensorRT emits a `The NetworkDefinitionCreationFlag::kEXPLICIT_PRECISION flag has been deprecated and has no effect. Please do not use this flag when creating the network.` warning when this flag is set.

`STRICT_TYPES` is also marked as [DEPRECATED] on https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/BuilderConfig.html#tensorrt.BuilderFlag, although no warning is emitted when set. I suggest that the individual flag should be provided instead.

## Environment

 - Torch-TensorRT Version (e.g. 1.0.0): https://github.com/pytorch/TensorRT/commit/09bef46a5c5e308184f3a2a1be5c082b55878423
 - PyTorch Version (e.g. 1.0): 1.13.1+cu117
 - CPU Architecture: x64
 - OS (e.g., Linux): Windows 11
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.10.9
 - CUDA version: 11.7.1
 - GPU models and configuration: RTX 3050
 - Any other relevant information:

**Comment by frank-wei** [comment]
@shirong, let's put it this in the backlog. We need to remove it later when we are upgraded.

**Comment by frank-wei** [comment]
@HolyWu thanks for reminding us. I'd say this is not a bug yet since it will create issue if set. But we will remove it later.

**Comment by HolyWu** [comment]
https://github.com/pytorch/TensorRT/blob/d35fe2aa5190ebf0abaea06315f89fff7c651f72/py/torch_tensorrt/fx/fx2trt.py#L212

`max_workspace_size` is also [deprecated](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/BuilderConfig.html#tensorrt.IBuilderConfig). New release should change to use [set_memory_pool_limit](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/BuilderConfig.html#tensorrt.IBuilderConfig.set_memory_pool_limit) instead.
