### ISSUE TITLE
Is NN inheritance possible?

### ISSUE THREAD

**Issue by manbehindthemadness** [pytorch/TensorRT#1631]
So I have an application that I am enhancing; I really want to use the TensorRT backend as it's benchmarks are just brilliant; however, I cannot see a way one would go about using inheritance: eg ``class MyFancyEncoder(tensor_compiled_resnet_passing_torch.nn)``

Example here: https://pastebin.com/nTdTfFnZ
Versus here: https://pastebin.com/L0YyKg9H

**Comment by narendasan** [comment]
I think this would be a bit easier to do with the FX frontend since it returns a pure Python class (either with the old or new runtime), I am not entirely sure about the inheritance properties of the wrapped TorchScript models. From a quick search it doesn't seem like it is supported. https://pytorch.org/docs/stable/jit_language_reference.html

**Comment by narendasan** [comment]
That being said, I am wondering how useful it would be since the TRTModule[Next] classes are designed to be generic to any TRT engine.

**Comment by manbehindthemadness** [comment]
Well, I benchmarked the difference (I'm using Robust Background Matting from PeterL1n) and it's a startling variation. I'm developing on a Jetson platform and using the Nsight profiler I am certain I can pull at least thirty percent. I'm tearing my hair out trying to get at it. Torch on aarm64 will **not** compile with native tensorrt due to a borked onnx importer requirement.... so this is my play.

**Comment by manbehindthemadness** [comment]
To clarify, looking at the code itself it's obvious this is *possible* but I simply cannot find the succulents toon to achieve it

**Comment by narendasan** [comment]
Are you able to use the precompiled NGC PyTorch builds? https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html

**Comment by narendasan** [comment]
or are you talking about the model not compiling?

**Comment by manbehindthemadness** [comment]
> Are you able to use the precompiled NGC PyTorch builds? https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html

My project is based on a custom OS using python 3.10.6 their aren't precompiled wheels to suffice, everything is hand built

**Comment by manbehindthemadness** [comment]
I have discovered additional information that has lead me to acquiring a workaround by exporting into onnx, and then converting to TensoRT:
https://github.com/NVIDIA/TensorRT/issues/2301
https://github.com/PeterL1n/RobustVideoMatting/issues/219
