### ISSUE TITLE
Port Tensor-RT and model compatibility tests to FX

### ISSUE THREAD

**Issue by Christina-Young-NVIDIA** [pytorch/TensorRT#1634]

**Comment by Christina-Young-NVIDIA** [comment]
To find any FX2TRT / dynamo gaps.

**Comment by gs-olive** [comment]
Currently, the TorchScript path routinely tests model compatibility for ResNet18, MobileNetV2, EfficientNetB0, ResNet18 with Half precision, and HuggingFace BERT base uncased. I have added a PR which tests the FX path (via specifying `ir="fx"` directly in `torch_tensorrt.compile(...)`) for all of these models except BERT, which currently fails to compile with this method and also does not compile using `torch_tensorrt.fx.compile(...)` with either `is_aten=True` or `is_aten=False`, via the current main branch (deda87b). The model also fails to compile with `torch._dynamo.optimize(...)`. An issue will be raised regarding compilation of HuggingFace BERT in FX. This (current) investigative issue will be closed and the PR will remain as a draft until BERT model compilation in FX is supported.
