### ISSUE TITLE
Add support for Torch_executed_ops in FX

### ISSUE THREAD

**Issue by Christina-Young-NVIDIA** [pytorch/TensorRT#1635]

**Comment by Christina-Young-NVIDIA** [comment]
https://github.com/pytorch/TensorRT/blob/a3436504714dc40885e80f70c93478d263eb1df1/py/torch_tensorrt/fx/tools/trt_splitter.py#L73

**Comment by gs-olive** [comment]
RFC #1681 created, currently under review
