### ISSUE TITLE
✨[Feature] Could TensorRT set a more flexible pattern for fmha and fmhca?

### ISSUE THREAD

**Issue by de1star** [pytorch/TensorRT#1703]
**Is your feature request related to a problem? Please describe.**
I am using TensorRT to accelerate the inference time of stable diffusion model, but my model structure is a bit different from a standard stable diffusion. For example, there are more cross attention modules in my model and thus the code in stable diffusion demo could not detect those modules correctly and insert fmhca plugins. I have tried to modify some logics in function **mha_mhca_detected** to insert plugins successfully, but I still wonder whether you'd like to consider providing a more flexible pattern for plugins like fmha and fmhca?

**Comment by ncomly-nvidia** [comment]
Hi @de1star can you please repost this to [NVIDIA/TensorRT](https://github.com/NVIDIA/TensorRT/issues)? We will continue the conversation there. This repo is just for the Torch-TensorRT PyTorch integration.
Thanks!
