### ISSUE TITLE
↔ [Converter] Add support for Tensor reshape and permute operators in the FX `aten` path

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#1724]
## aten.unsqueeze, aten.reshape, aten.permute, aten.transpose

- **Function Schema**:
  - `torch.ops.aten.unsqueeze.default: ((torch.int32,), {})`
  - `torch.ops.aten.reshape: ((torch.float32,), {})`
  - `torch.ops.aten.permute.default: ((torch.float32,), {})`
  - `torch.ops.aten.transpose.int: ((torch.float32,), {})`

- **Original PyTorch API**: `torch.unsqueeze`, `torch.reshape`, `torch.permute`, `torch.transpose`

- **Relevant TensorRT Documentation**: [IGatherLayer](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Layers.html?highlight=igather#igatherlayer), [IShuffleLayer](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Layers.html?highlight=ishuffle#ishufflelayer)

Add support for `unsqueeze`, `reshape`, `permute`, and `transpose` as [aten converters](https://github.com/pytorch/TensorRT/blob/main/py/torch_tensorrt/fx/converters/aten_ops_converters.py).

**Comment by apbose** [comment]
Linked issue #1754 for torch.ops.aten.permute.default: ((torch.float32,), {}),  torch.ops.aten.unsqueeze.default: ((torch.int32,), {}), torch.ops.aten.reshape: ((torch.float32,), {})
