### ISSUE TITLE
🐛 [Bug] Torch-TRT test failures on Jetson Xavier 22.12 version

### ISSUE THREAD

**Issue by peri044** [pytorch/TensorRT#1725]
##  Bug Description

I have updated our CI to use this branch https://github.com/pytorch/TensorRT/tree/packaging_22.12 to build a Jetson wheel file for Torch-TRT which uses Jetpack 5.1 (TRT 8.5.2, CUDA-11.4). The torch wheel file used is from https://developer.download.nvidia.com/compute/redist/jp/v502/pytorch/ (22.12 version). 

Here are the following test failures on a Jetson Xavier machine. 

1) NaN issues: 
```
FAILED acc_op/test_binary_ops.py::TestBinaryOpConverters::test_elementwise_op_with_dynamic_shape_12_no_broadcast_pow - AssertionError: Tensor-likes are not close!
FAILED acc_op/test_binary_ops.py::TestBinaryOpConverters::test_elementwise_op_with_dynamic_shape_25_broadcast_pow - AssertionError: Tensor-likes are not close!
FAILED acc_op/test_binary_ops.py::TestBinaryOpConverters::test_elementwise_op_with_dynamic_shape_four_dimensions_12_no_broadcast_pow - AssertionError: Tensor-likes are not close!
FAILED acc_op/test_binary_ops.py::TestBinaryOpConverters::test_elementwise_op_with_dynamic_shape_four_dimensions_25_broadcast_pow - AssertionError: Tensor-likes are not close!
FAILED acc_op/test_binary_ops.py::TestBinaryOpConverters::test_elementwise_ops_with_one_constant_12_pow - AssertionError: Tensor-likes are not close!
```
The above issues are resolved if we enable `equal_nan=True` in this line https://github.com/pytorch/TensorRT/blob/release/ngc/22.12/py/torch_tensorrt/fx/tools/common_fx2trt.py#L98

2) Expected ops issue: 
```
FAILED acc_op/test_cat.py::TestCatConverter::test_cat_1_concat - AssertionError: False is not true : expected ops {<function cat at 0xffff2d1ec670>}, actuall ops {<built-in method concat of type object at 0xffff82610e60>}
FAILED acc_op/test_cat.py::TestCatConverter::test_cat_neg_1_concat - AssertionError: False is not true : expected ops {<function cat at 0xffff2d1ec670>}, actuall ops {<built-in method concat of type object at 0xffff82610e60>}
FAILED acc_op/test_cat.py::TestCatConverter::test_cat_with_dynamic_shape_1_concat - AssertionError: False is not true : expected ops {<function cat at 0xffff2d1ec670>}, actuall ops {<function add at 0xffff2d1ec430>, <built-in method concat of type object at 0xffff82610e60>}
FAILED acc_op/test_cat.py::TestCatConverter::test_cat_with_dynamic_shape_four_dimensions_1_concat - AssertionError: False is not true : expected ops {<function cat at 0xffff2d1ec670>}, actuall ops {<function add at 0xffff2d1ec430>, <built-in method concat of type object at 0xffff82610e60>}
FAILED acc_op/test_cat.py::TestCatConverter::test_concat - AssertionError: False is not true : expected ops {<function cat at 0xffff2d1ec670>}, actuall ops {<built-in method concat of type object at 0xffff82610e60>}
```
These are issues where the expected op is different from the op in the graph. They arise from this line https://github.com/pytorch/TensorRT/blob/release/ngc/22.12/py/torch_tensorrt/fx/tools/common_fx2trt.py#L65

3) Output dtype issue 
```
 AssertionError: The values for attribute 'dtype' do not match: torch.int32 != torch.int64.
```
test_max.py, test_min.py, test_topk.py fail with the above error. This is relatively easy to fix. Casting the right output type will fix these issues. This casting exists in the Torchscript side of tests. This has to be added to FX tests. 

4) Tracer issue 

```
tracer/test_acc_tracer.py
FAILED tracer/test_acc_tracer.py::AccTracerTest::test_addmm_0 - AssertionError: False is not true
FAILED tracer/test_acc_tracer.py::AccTracerTest::test_all_acc_ops_registered - AttributeError: module 'torch_tensorrt.fx.tracer.acc_tracer.acc_ops' has no attribute 'prelu'
FAILED tracer/test_acc_tracer.py::AccTracerTest::test_cumsum - AssertionError: Cannot normalize ('dtype',) to dtype for cumsum
FAILED tracer/test_acc_tracer.py::AccTracerTest::test_quantized_conv2d - RuntimeError: Didn't find engine for operation quantized::conv2d_prepack NoQEngine
FAILED tracer/test_acc_tracer.py::AccTracerTest::test_quantized_convrelu2d - RuntimeError: Didn't find engine for operation quantized::conv2d_prepack NoQEngine
FAILED tracer/test_acc_tracer.py::AccTracerTest::test_quantized_linear - RuntimeError: Didn't find engine for operation quantized::linear_prepack NoQEngine
FAILED tracer/test_acc_tracer.py::AccTracerTest::test_transpose - TypeError: list indices must be integers or slices, not Node
```

5) Passes failures

```
Error with passes/test_fuse_permute_matmul_trt.py::TestFusePermuteMatmul::test_fuse_permute_matmul_6_transpose_lhs_bmm_broadcast - AssertionError
FAILED passes/test_fuse_permute_matmul_trt.py::TestFusePermuteMatmul::test_fuse_permute_matmul_7_transpose_rhs_bmm_broadcast - AssertionError

[03/01/2023-16:00:06] [TRT] [E] 4: [MATRIX_MULTIPLY]-[acc_ops.trt_transposed_matmul]-[trt_transposed_matmul]: inputs with the same operation must have same number of dimensions, but have 3 and 2 dimensions respectively.
[03/01/2023-16:00:06] [TRT] [E] 4: [MATRIX_MULTIPLY]-[acc_ops.trt_transposed_matmul]-[trt_transposed_matmul]: inputs with the same operation must have same number of dimensions, but have 3 and 2 dimensions respectively.
[03/01/2023-16:00:06] [TRT] [E] 4: [network.cpp::validate::3014] Error Code 4: Internal Error (Layer [MATRIX_MULTIPLY]-[acc_ops.trt_transposed_matmul]-[trt_transposed_matmul] failed validation)
```
6) Torchscript BERT failure. 

In the test_models.py, the output tensors are all `NaN` for random inputs which makes the cosine_sim=NaN too. Changing it to torch.ones((1, 14)) works fine.

cc: @narendasan  @frank-wei 

## Expected behavior

All tests should be passed.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):
 - PyTorch Version (e.g. 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by peri044** [comment]
@frank-wei  Any comments on 2), 4) and 5) ? Thank you.

**Comment by frank-wei** [comment]
1) the unit test generated NaN, I am surprised to see that. Is it due to Jetson compatibility? 
2) expected ops {<function cat at 0xffff2d1ec670>}, actuall ops {<built-in method concat of type object at 0xffff82610e60>} looks like it is not being recognized in acc tracer. We can print the graph see what kind of op is that at here (https://github.com/pytorch/TensorRT/blob/main/py/torch_tensorrt/fx/tools/common_fx2trt.py#L255)
4) I am wondering why we are seeing these tracer issues? Do you have insight? 
5) existing bug I filed before about TRT8.5
