### ISSUE TITLE
🐛 [Bug] Encountered bug when using Torch-TensorRT

### ISSUE THREAD

**Issue by BryceWayne** [pytorch/TensorRT#1737]
##  Bug Description

I am following the Torch 2 TensorRT guide located on the website.
https://pytorch.org/TensorRT/tutorials/use_from_pytorch.html

I created a `main.py` in the NGC container with the provided code
```python
import torch
import torch_tensorrt

import torchvision.models as models

model = models.mobilenet_v2(pretrained=True)
script_model = torch.jit.script(model)

spec = {
    "forward": torch_tensorrt.ts.TensorRTCompileSpec(
        **{
            "inputs": [torch_tensorrt.Input([1, 3, 300, 300])],
            "enabled_precisions": {torch.float, torch.half},
            "refit": False,
            "debug": False,
            "device": {
                "device_type": torch_tensorrt.DeviceType.GPU,
                "gpu_id": 0,
                "dla_core": 0,
                "allow_gpu_fallback": True,
            },
            "capability": torch_tensorrt.EngineCapability.default,
            "num_avg_timing_iters": 1,
        }
    )
}

trt_model = torch._C._jit_to_backend("tensorrt", script_model, spec)

input = torch.randn((1, 3, 300, 300)).to("cuda").to(torch.half)
print(trt_model.forward(input))
```

## To Reproduce

1. Get NGC docker container (https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch)
2. Docker run
3. Create main python file with provided code
4. Run
5. Crash

```bash
docker run --gpus all  --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -it --rm -v ./:/opt/pytorch nvcr.io/nvidia/pytorch:22.01-py3
```

```bash
root@ccd963ef2591:/workspace# python main.py
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    trt_model = torch._C._jit_to_backend("tensorrt", script_model, spec)
RuntimeError:
temporary: the only valid use of a module is looking up an attribute but found  = prim::SetAttr[name="num_batches_tracked"](%_1.8, %1471)
:
```

## Expected behavior

I expected the code to work out of the box as described in the tutorial.

## Environment
Docker container version 22.01

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): '1.1.0a0'
 - PyTorch Version (e.g. 1.0): PyTorch Version 1.11.0a0+bfe5ad2
 - CPU Architecture:
 - OS (e.g., Linux): WSL Ubuntu
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: Python 3.8.12
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context
This is my first bug report. Please be kind. Will update info as requested.

**Comment by BryceWayne** [comment]
This might be related
[issues34002](https://github.com/pytorch/pytorch/issues/34002#issuecomment-612782073)

**Comment by HarryPham0123** [comment]
I experience the same issue with Pytorch 1.10.0 and Torchvision 0.11.1 on Jetson Nano (Jetpack 4.6). Do we have any update on this?

**Comment by BryceWayne** [comment]
I abandoned this approach @HarryPham0123 but I hope they help you.
