### ISSUE TITLE
🐛 [Bug] RuntimeError: [Error thrown at core/conversion/conversionctx/ConversionCtx.cpp:147] Building serialized network failed in TensorRT

### ISSUE THREAD

**Issue by AllesOderNicht** [pytorch/TensorRT#1753]
![image](https://user-images.githubusercontent.com/91169172/226618791-62473d95-9e78-45ce-a175-3baa58cbc021.png)

**Comment by narendasan** [comment]
The error gives you an explanation of what happens and how to try to avoid it. It says you are running out of memory so its unable to find a kernel that works and to try increasing the workspace size. Change the value of the setting `max_workspace_size` to provide tensorrt more memory.

**Comment by AllesOderNicht** [comment]
Thanks, Now it seems to compile fine.But it still doesn't work properly. I don't know what the reason is, it doesn't show the error.
![image](https://user-images.githubusercontent.com/91169172/226777813-871d616f-001c-45de-b9cc-46096995c9ea.png)
![image](https://user-images.githubusercontent.com/91169172/226777857-9c6733cc-46b9-4220-a9bb-57ea064b240e.png)
![image](https://user-images.githubusercontent.com/91169172/226777887-39d0e2b3-d7d2-46c9-9e04-5eacb68100df.png)

**Comment by narendasan** [comment]
You can try increasing logging verbosity to see what is happening at runtime by adding a context 
 
```
with torch_tensorrt.logging.debug(): 
    model(input_data, input_data)
```
