### ISSUE TITLE
Torch 2.0 python whl

### ISSUE THREAD

**Issue by big-thousand** [pytorch/TensorRT#1760]
Is There a nightly build whl that can support torch 2.0?

**Comment by narendasan** [comment]
Track this branch's CI (https://app.circleci.com/pipelines/github/pytorch/TensorRT?branch=stack_upgrade_1.4). We are setting up nightlies on 2.0 stable

**Comment by Data-drone** [comment]
Will there be a release support torch 2.0 soon?

**Comment by narendasan** [comment]
Yes. We are waiting on TensorRT 8.6 and PyTorch 2.0.1 for critical bug fixes, then we will release

**Comment by Data-drone** [comment]
Looks like it has been released? https://github.com/pytorch/TensorRT/releases/tag/v1.4.0 I haven't tested yet

**Comment by narendasan** [comment]
Yes it has been released, closing this issue.
