### ISSUE TITLE
🐛 [Bug] Error encountered when completing inference on component module of GPT2

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#1761]
##  Bug Description

When compiling an attention submodule of the [HuggingFace GPT2 model](https://huggingface.co/gpt2) from TorchScript to Torch-TRT, the following error is encountered:

```python
Traceback (most recent call last):
  File "err.py", line 286, in <module>
    main()
  File "err.py", line 277, in main
    out = trt_compiled(inp)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: [Error thrown at core/runtime/execute_engine.cpp:136] Expected inputs[i].dtype() == expected_type to be true but got false
Expected input tensors to have type Half, found type float
```

## To Reproduce

1. Instantiate GPT2 model from pretrained source: 
```python
from transformers import GPT2Model
model = GPT2Model.from_pretrained("gpt2", output_attentions=False, output_hidden_states=False, use_cache=False, torchscript=True).eval().cuda()
```
2. Define model wrapper to extract relevant portion of model:
```python
class ForwardWrapper(torch.nn.Module):
    def __init__(self, model) -> None:
        super().__init__()
        self.model = model

    def forward(self, x):
        return self.model(x)[0]
```
3. Wrap model attention module: `model_portion = ForwardWrapper(model.h[0].attn).eval().cuda()` 
4. Generate hidden state data: `hidden_state = torch.rand((8, 128, 768)).cuda()`
5. Trace model `traced = torch.jit.trace(model_portion, inp).cuda().eval()`
6. Cast traced and input to `half` types for compilation: `traced = traced.half(); hidden_state=hidden_state.half()`
7. Define inputs: `inputs = [torchtrt.Input(shape=[8, 128, 768], dtype=torch.half)]`
8. Compile model:
```python
trt_model = torchtrt.compile(traced, inputs=inputs, enabled_precisions={torch.half}, truncate_long_and_double=True)
```
9. Complete inference: `trt_model (hidden_state)`

## Expected behavior

Module should perform inference when compiled with half precision via the TorchScript path

## Environment

- Transformers: 4.27.2
 - Torch-TensorRT Version (e.g. 1.0.0): a1d4af0f
 - PyTorch Version (e.g. 1.0): 2.1.0.dev20230219+cu117
- CPU Architecture: Intel Xeon CPU
- OS: Ubuntu 20.04
- How you installed PyTorch: pip
- Build command you used: `python setup.py develop`
- Are you using local sources or building from archives: local
- Python version: 3.8.13
- CUDA version: 11.7

## Additional Considerations
The full GPT2 model is functional - see #1455. Each of its component modules should be able to compile successfully as a result.

**Comment by gs-olive** [comment]
Related to #1777

**Comment by narendasan** [comment]
Working in the dynamo frontend
