### ISSUE TITLE
🐛 [Bug]nn.AdaptiveAvgPool2d can't convert Tensorrt.

### ISSUE THREAD

**Issue by AllesOderNicht** [pytorch/TensorRT#1766]
![image](https://user-images.githubusercontent.com/91169172/227158122-3b28b88f-72ab-45ee-8590-c02aca5fc35a.png)
![image](https://user-images.githubusercontent.com/91169172/227158191-ed8df6f1-caa6-40b0-b8d4-3a262395b47b.png)

**Comment by narendasan** [comment]
Seems like this bug is coming from jit scripting. I would first make sure that you are able to pass your model through `torch.jit.script` or `torch.jit.trace`.

**Comment by AllesOderNicht** [comment]
![image](https://user-images.githubusercontent.com/91169172/227421707-facf5914-a4e2-4c99-a9ad-f391ba97301e.png)
Thanks，but how should I modify the JIT model in Torch Tensorrt
