### ISSUE TITLE
🐛 [Bug]  in lowering graph for mini graph input.

### ISSUE THREAD

**Issue by AllesOderNicht** [pytorch/TensorRT#1768]
compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/partitioning/shape_analysis.cpp:68] Expected ivalues_maps.count(input) to be true but got false
Could not find torch::jit::Value* image_hw.1 produced from %image_hw.1 : int[] = aten::slice(%2061, %11, %self.backbone.conv1.bias.3, %12) # /data/czj1/code/2022.1/model/models_0427.py:265:19 in lowering graph for mini graph input.

![image](https://user-images.githubusercontent.com/91169172/227476759-bd040f71-feaf-4687-a828-33d017c457f9.png)

I used Resnet18 for compiling, but show me this bug.  ps ,My model passed scripted_module.

**Comment by bowang007** [comment]
@AllesOderNicht 
Could you please share the Torch-TensorRT version that you are using ? 
I think this should be fixed in our latest master branch. 
Do you have a more detailed log ?
