### ISSUE TITLE
🐛 [Bug] RuntimeError: Expected Tensor but got Uninitialized

### ISSUE THREAD

**Issue by rishic3** [pytorch/TensorRT#1772]
##  Bug Description

I'm currently attempting to compile my model into TensorRT using the torch_tensorrt.compile command like so:

> fusion_inputs = 
[torch_tensorrt.Input(min_shape=[1, 3, height, width],opt_shape=[batch_size, 3, height, width],max_shape=[batch_size, 3, height, width],dtype=torch.half,)]
enabled_precisions = {torch.half}

>trt_model_fp16 = torch_tensorrt.compile(model.half(), inputs=fusion_inputs, enabled_precisions=enabled_precisions)

The compilation fails, and I receive the following error:
> Traceback (most recent call last):
  File "fusion_data_tensorrt.py", line 229, in <module>
    trt_model_fp16 = torch_tensorrt.compile(model.half(), inputs=fusion_inputs, enabled_precisions=enabled_precisions)
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 97, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/ts/_compiler.py", line 119, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: Expected Tensor but got Uninitialized

Upon inspecting the graph log, I can see that I have many of the following errors: 
>Unable to get schema for Node %input.5 : Tensor = prim::If(%5827) # /opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:3810:4
>...
>Unable to get schema for Node %5817 : int = prim::Loop(%5304, %5816, %5303) # /opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:3778:12
>...

The errors point to a function call in 'torch.nn.functional.py', so I am not sure where the source of the error is in my code. I don't believe I reference torch.nn.functional anywhere in my model, so I am unsure whether this is a fixable issue or is an inherent TensorRT incompatibility.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.1.0a0
 - PyTorch Version (e.g. 1.0): 1.11.0a0+b6df043
 - CPU Architecture: 8-core Carmel ARM® v8.2 64-bit CPU, 8MB L2 + 4MB L3
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Python version: 3.8.12 
 - CUDA version: 11.6
 - GPU models and configuration: Nvidia RTX 6000
 - Any other relevant information: Running on Nvidia Clara AGX, in a Pytorch NGC container

**Comment by bowang007** [comment]
Hey @rishic3 , 
basically, some info like this:
...
Unable to get schema for Node %5817 : int = prim::Loop(%5304, %5816, %5303) # /opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:3778:12
...
does not mean it's an error. 
It just indicates that those operations cannot be converted to TensorRT, so they will be fallback to run in Torch. 

Now fp16 is not fully supported for partial compilation since this involves in some type conversions between TRT engines and Torch running modules,  we are trying to support it. 

As for the error you have now: 
```
RuntimeError: Expected Tensor but got Uninitialized
```
Please refer to this one: https://github.com/pytorch/TensorRT/issues/1282
