### ISSUE TITLE
↔ [Converter] Add support for key operators in aten path

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#1809]
**Operators:**
`torch.ops.aten.amax.default`
`torch.ops.aten.scalar_tensor.default`
`torch.ops.aten.baddbmm.default`
`torch.ops.aten.exp.default`
`torch.ops.aten.empty.memory_format`
`torch.ops.aten.all.dim`

**Comment by gs-olive** [comment]
To Support:
```
- torch.ops.aten._to_copy.default + Operator Count: 1
- torch.ops.aten.all.dim + Operator Count: 1
- torch.ops.aten.sum.dim_IntList + Operator Count: 1
- torch.ops.aten.exp.default + Operator Count: 1
- torch.ops.aten.amax.default + Operator Count: 1
- torch.ops.aten.baddbmm.default + Operator Count: 1
- torch.ops.aten.empty.memory_format + Operator Count: 1
- torch.ops.aten.sqrt.default + Operator Count: 1
- _operator.getitem + Operator Count: 2
- torch.ops.aten.var_mean.correction + Operator Count: 1
- torch.ops.aten.clone.default + Operator Count: 1
```

**Comment by apbose** [comment]
Implemeted - `torch.ops.aten.amax.default`, `torch.ops.aten.exp.default`
Lowering ops- `torch.ops.aten.baddbmm.default`
To be implemented - `torch.ops.aten.scalar_tensor.default`,` torch.ops.aten.empty.memory_format`, `torch.ops.aten.all.dim`
