### ISSUE TITLE
🐛 [Bug] Failed to run examples/fx/quantized_resnet_test.py while PyTorch==2.0.0 and tensorrt==8.5.1.7

### ISSUE THREAD

**Issue by shiwenloong** [pytorch/TensorRT#1813]
##  Bug Description

Failed to run examples/fx/quantized_resnet_test.py while PyTorch==2.0.0 and tensorrt==8.5.1.7.
tensorrt is installed by `pip install tensorrt==8.5.1.7`

## To Reproduce

1. cd py && python3 setup.py install --fx-only
2. cd ..
3. python examples/fx/quantized_resnet_test.py

## Expected behavior
```
[04/10/2023-16:22:43] [TRT] [V] Trying to load shared library libnvinfer_builder_resource.so.8.5.1
[04/10/2023-16:22:43] [TRT] [V] Loaded shared library libnvinfer_builder_resource.so.8.5.1
[04/10/2023-16:22:49] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +441, GPU +118, now: CPU 1055, GPU 40249 (MiB)
[04/10/2023-16:04:04] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[04/10/2023-16:04:04] [TRT] [W] The NetworkDefinitionCreationFlag::kEXPLICIT_PRECISION flag has been deprecated and has no effect. Please do not use this flag when creating the network.
INFO:torch_tensorrt.fx.fx2trt:TRT INetwork construction elapsed time: 0:00:00.079192
[04/10/2023-16:04:04] [TRT] [W] Calibrator is not being used. Users must provide dynamic range for all tensors that are not Int32 or Bool.
[04/10/2023-16:04:04] [TRT] [E] 4: [standardEngineBuilder.cpp::initCalibrationParams::1685] Error Code 4: Internal Error (Calibration failure occurred with no scaling factors detected. This could be due to no int8 calibrator or insufficient custom scales for network layers. Please see int8 sample to setup calibration correctly.)
Traceback (most recent call last):
  File "/data2/nice/projects/TensorRT/examples/fx/quantized_resnet_test.py", line 142, in <module>
    int8_trt = build_int8_trt(rn18)
  File "/data2/nice/anaconda3/envs/pt2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data2/nice/projects/TensorRT/examples/fx/quantized_resnet_test.py", line 74, in build_int8_trt
    interpreter_result = interp.run(lower_precision=LowerPrecision.INT8)
  File "/data2/nice/anaconda3/envs/pt2/lib/python3.10/site-packages/torch_tensorrt/fx/fx2trt.py", line 252, in run
    assert engine
AssertionError
```
## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 5a45f6b1
 - PyTorch Version (e.g. 1.0): 2.0.0+cu117
 - CPU Architecture: A40
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives: No
 - Python version: 3.10.9
 - CUDA version:11.7
 - GPU models and configuration:
 - Any other relevant information:
 - TensorRT version: 8.5.1.7

**Comment by frank-wei** [comment]
The test seems broken. cc @jerryzh168

**Comment by jerryzh168** [comment]
maybe it's related to some recent refactors to the code base, but we don't have people working on this right now, can we skip this test for now?

**Comment by matcosta23** [comment]
> I could reproduce this bug.
> 
> ```
> Calibrator is not being used. Users must provide dynamic range for all tensors that are not Int32 or Bool.
> [04/11/2023-18:00:22] [TRT] [E] 4: [standardEngineBuilder.cpp::initCalibrationParams::1463] Error Code 4: Internal Error (Calibration failure occurred with no scaling factors detected. This could be due to no int8 calibrator or insufficient custom scales for network layers. Please see int8 sample to setup calibration correctly.)
> ```
> 
> @frank-wei Any thoughts ? My suspicion is https://github.com/pytorch/TensorRT/blob/main/examples/fx/quantized_resnet_test.py#L44-L57 isn't correctly inserting scales for all tensors maybe ?

Yeah, I would say the same. I tried to compare two quantized graphs . The first one obtained from the *QConfig* shown in the code snippet linked by @peri044 and the second one using the default *QConfig*.

The code defining both QConfigs and their differences can be found here:
```python
>>> qconfig_default = get_default_qconfig("x86")
>>> qconfig_default.activation
functools.partial(<class 'torch.ao.quantization.observer.HistogramObserver'>, reduce_range=True){}
>>> qconfig_default.weight
functools.partial(<class 'torch.ao.quantization.observer.PerChannelMinMaxObserver'>, dtype=torch.qint8, qscheme=torch.per_channel_symmetric){}
>>> qconfig_trt= QConfig(
        activation=torch.ao.quantization.observer.HistogramObserver.with_args(
            qscheme=torch.per_tensor_symmetric, dtype=torch.qint8
        ),
        weight=torch.quantization.default_per_channel_weight_observer,
    )
>>> qconfig_trt.activation
functools.partial(<class 'torch.ao.quantization.observer.HistogramObserver'>, qscheme=torch.per_tensor_symmetric, dtype=torch.qint8){}
>>> qconfig_trt.weight
functools.partial(<class 'torch.ao.quantization.observer.PerChannelMinMaxObserver'>, dtype=torch.qint8, qscheme=torch.per_channel_symmetric){}
```

After preparing (prepare_fx), calibrating and quantizing (quantize_fx) the ResNet18 model with these two different QConfig instances, we can compare the FX graphs obtained.

>⚠️ Disclaimer
>
> The function convert_to_reference_fx has been replaced by quantize_fx in quantized_resnet_test.py.

```python
>>> quantized_resnet_18_from_qconfig_trt
GraphModule(
  (conv1): ConvReLU2d(
    (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3))
    (1): ReLU(inplace=True)
  )
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Module(
    (0): Module(
      (conv1): ConvReLU2d(
        (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (1): ReLU(inplace=True)
      )
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (relu): ReLU(inplace=True)
    )
    ...
>>> quantized_resnet_18_from_qconfig_default
GraphModule(
  (conv1): QuantizedConvReLU2d(3, 64, kernel_size=(7, 7), stride=(2, 2), scale=0.010285161435604095, zero_point=0, padding=(3, 3))
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Module(
    (0): Module(
      (conv1): QuantizedConvReLU2d(64, 64, kernel_size=(3, 3), stride=(1, 1), scale=0.018722333014011383, zero_point=0, padding=(1, 1))
      (conv2): QuantizedConv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), scale=0.032894741743803024, zero_point=67, padding=(1, 1))
    )
    ...
```

When comparing the two quantized graphs, we see that the scale and zero points are not inserted on the graph when using *qconfig_trt*, as supposed by @peri044 . Also, we see that Conv2d and ReLU are not fused.

However, despite the *qconfig_default* correctly inserts the calibration statistics, the TensorRT engine can only be obtained from graphs where $\text{zero point}=0 \text{ } \forall$ layers. 

The scripts keeps non-functional, but I've commented on an [unsolved and closed issue (#48473)](https://github.com/pytorch/pytorch/issues/48473) related to this lack of control of the model calibration. Maybe is not the script itself that is broken, but the API for [FX Graph Mode Static PTQ](https://pytorch.org/tutorials/prototype/fx_graph_mode_ptq_static.html) proposed by torch 2.0.

**Comment by MaltoseFlower** [comment]
anybody solve this problem? I encounter this error in torch==2.4.0, tensorrt==10.1.0, torch-tensorrt==2.4.0, modelopt==0.25.0

**Comment by MaltoseFlower** [comment]
cc @jerryzh168 @frank-wei @peri044
