### ISSUE TITLE
❓ [Question] Pytorch 2.0 Compatability?

### ISSUE THREAD

**Issue by FabianSchuetze** [pytorch/TensorRT#1824]
## ❓ Question

Thanks for this repo. Is TensorRT compatible with pytorch 2.0? I see that the latest release targets pytorch 1.13. Is there some way I can use TensorRT with pytorch 2.0?

**Comment by gs-olive** [comment]
Hello - our current `main` branch is based on a development version of PyTorch 2.0, and our upcoming release (Torch-TensorRT 1.4) will be based on PyTorch 2.0 Stable.

**Comment by FabianSchuetze** [comment]
Thanks for the comment, @gs-olive

**Comment by andrewjong** [comment]
When is 1.4 expected to be released?
