### ISSUE TITLE
↔ [Converter] Add support for `aten::Int.Tensor` in Torch-TensorRT TorchScript Path

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#1836]
## aten::Int.Tensor

- **Function Schema**: `aten::Int.Tensor(Tensor a) -> int`

- **Original PyTorch API**: torch.item() [[documentation](https://pytorch.org/docs/stable/generated/torch.Tensor.item.html)]

This converter/evaluator extracts the integer value from single-element tensors.

**Comment by narendasan** [comment]
Is this for FX or TS?

**Comment by gs-olive** [comment]
This is for the TorchScript path and relates to a model for which this is the only missing operator.

**Comment by xunleiw** [comment]
The related issue closed more than 1 yr ago.
https://github.com/pytorch/TensorRT/issues/513
