### ISSUE TITLE
❓ [Question] Can I use TensorRT8.5.3.1 and torch1.10.1 with torch_TensorRT? 

### ISSUE THREAD

**Issue by Yoh-Z** [pytorch/TensorRT#1845]
## ❓ Question

I found that when pip install torch_tensorrt corresponding to TensorRT8.5.3.1, torch must be 1.13. Can I use TensorRT8.5.3.1 and torch1.10.1 with torch_TensorRT? 

And if I use c++ torch_tensorrt, can i avoid this situation?

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.10.1
 - CPU Architecture: x86
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Python version: 3.9.16
 - CUDA version: 11.6
 - GPU models and configuration: rtx3090

**Comment by gs-olive** [comment]
Torch-TensorRT does not currently support Torch 1.10.1, and using that build with either the Python or C++ APIs could lead to errors as TorchScript schemas, functions, and paradigms can change. Though not supported, you could try building with that Torch version by replacing the `urls` and `sha256` fields of the `libtorch` and `libtorch_pre_cxx11_abi` sections in the WORKSPACE file, and rebuilding Torch-TensorRT from scratch:
https://github.com/pytorch/TensorRT/blob/1d78f436a9a423a8486338ecefd972fd08777f63/WORKSPACE#L56-L70

**Comment by Yoh-Z** [comment]
thanks a lot, I will try it

**Comment by Yoh-Z** [comment]
I try to use cmake to compile, but it seems that the lower version of torch is not supported, some api has changed.
