### ISSUE TITLE
❓ [Question] Why was this Repo renamed to TensorRT ?

### ISSUE THREAD

**Issue by MatthieuTPHR** [pytorch/TensorRT#1858]
Thank you all for the great work on Torch-TensorRT. 
It's been a pleasure to see it evolve since the days of TRTorch.

This repo went through multiple names but I think the current one is extremely confusing, if I clone both this repo and the original TensorRT repo I now have two TensorRT folders. 

This is extremely confusing and at times infuriating. Would it be possible to know more about what prompted this naming choice ? 

Wouldn't it be clearer to use Torch-TensorRT ? 

PS: it seems [other people are confused and are posting issues for TensorRT here](https://github.com/pytorch/TensorRT/issues/1703)

**Comment by narendasan** [comment]
The reason we named it TensorRT is it follows convention within the pytorch org. Ex. vision, text, xla, tvm. This was the option amongst a few different options the PyTorch/Meta and NVIDIA teams agreed on when moving the the project to PyTorch to have the project best fit in. I get that it could potentially be confusing. Personally I have a pytorch_org directory to contain the pytorch projects Im looking at. I know others do `git clone git@github.com:pytorch/TensorRT Torch-TensorRT`. I believe we still have support in the code base to handle some of the legacy names so it should not break bazel.

**Comment by MatthieuTPHR** [comment]
Ok, thank you it's clearer now
