### ISSUE TITLE
❓ [Question] torch.fx.proxy.TraceError: Proxy object cannot be iterated

### ISSUE THREAD

**Issue by DanielLevi6** [pytorch/TensorRT#1871]
## ❓ Question

I'm trying to convert an nn.Module of ASLfeat(Pytorch) to a runtime Torch-TensorRT model(for C++)
The steps I followed are the same as written in- https://github.com/pytorch/TensorRT/blob/main/examples/fx/fx2trt_example_next.py

But for some reason, the tracing step fails every time.
The error message is-
`torch.fx.proxy.TraceError: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.fx docs on pytorch.org for a more detailed explanation of what types of control flow can be traced, and check out the Proxy docstring for help troubleshooting Proxy iteration errors`

The line which cause it is- `n_samples, n_channel, *_ = dense_feat_map.shape`

The same is happening when I'm trying to use the FasterRCNN model from torchvision.
The same error occurs because of a loop running on the input list in the model.

Is there a workaround for these cases?
ASLfeat and FasterRCNN are complicated models which I can't convert directly to TensorRT, so Torch-TensorRT could be a very useful option for me.

## To Reproduce

Steps to reproduce the behavior(for FasterRCNN):

1. `from torchvision.models.detection.faster_rcnn import fasterrcnn_resnet50_fpn,FasterRCNN_ResNet50_FPN_Weights`
2. `model = fasterrcnn_resnet50_fpn(weights=FasterRCNN_ResNet50_FPN_Weights.DEFAULT).cuda().eval()`
3. `inputs = [torch.rand((1, 300, 400), device="cuda"), torch.rand((1, 500, 400), device="cuda")]`
4. `traced = acc_tracer.trace(model, inputs)`

The result-
`Traceback (most recent call last):`
`  File "/home/Projects/Torch-TensorRT/python/trainingPath/step_7_fasterRCNNInference-X.py", line 44, in <module>`
`    traced = acc_tracer.trace(model, inputs)`
`  File "/home/Projects/Torch-TensorRT/python/venv/lib/python3.8/site-packages/torch_tensorrt/fx/tracer/acc_tracer/acc_tracer.py",` `line 667, in trace`
`    traced = rewriter_base_trace(mod, ast_rewriter_allow_list, leaf_module_list)`
`  File "/home/Projects/Torch-TensorRT/python/venv/lib/python3.8/site-packages/torch_tensorrt/fx/tracer/acc_tracer/acc_tracer.py",` `line 585, in rewriter_base_trace`
`    rewritten_graph, rewritten_mod = AccRewritingTracer().trace(`
`  File "/home/Projects/Torch-TensorRT/python/venv/lib/python3.8/site-packages/torch_tensorrt/fx/tracer/acc_tracer/acc_tracer.py",` `line 309, in trace`
`    return super().trace(rewritten, concrete_args), rewritten`
`  File "/home/Projects/Torch-TensorRT/python/venv/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 778, in trace`
`    (self.create_arg(fn(*args)),),`
`  File "/home/Projects/Torch-TensorRT/python/venv/lib/python3.8/site-packages/torchvision/models/detection/generalized_rcnn.py",` `line 75, in forward`
`    for img in images:`
`  File "/home/Projects/Torch-TensorRT/python/venv/lib/python3.8/site-packages/torch/fx/proxy.py", line 385, in __iter__`
`    return self.tracer.iter(self)`
`  File "/home/Projects/Torch-TensorRT/python/venv/lib/python3.8/site-packages/torch/fx/proxy.py", line 285, in iter`
`    raise TraceError('Proxy object cannot be iterated. This can be '`
`torch.fx.proxy.TraceError: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.fx docs on pytorch.org for a more detailed explanation of what types of control flow can be traced, and check out the Proxy docstring for help troubleshooting Proxy iteration errors`

## What you have already tried
I also tried to use torch.jit.trace which traces the ASLfeat model successfully, but I need to trace the model using fx(because I need to convert it to a runtime model)

## Expected behavior

Receive a traced model, prepared for the torch-tensorrt usage.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

-     PyTorch Version (e.g., 1.0): 2.0
-     CPU Architecture: x86-64
-     OS (e.g., Linux): Ubuntu 20.04
-     How you installed PyTorch (conda, pip, libtorch, source): pip
-     Build command you used (if compiling from source): -
-     Are you using local sources or building from archives: Torch-TensorRT which has been built from sources
-     Python version: 3.8.10
-     CUDA version: 11.8
-     GPU models and configuration: NVIDIA T1000
-     Any other relevant information: -

@OronG13

**Comment by DanielLevi6** [comment]
Hi @frank-wei @yinghai 
Another error related to the Proxy object, is raised when I'm trying to convert the OpenAI's Clip model. I'm using the same way as explained in the next notebook-
https://github.com/pytorch/TensorRT/blob/main/examples/fx/fx2trt_example_next.py

The error message is raised when I'm using the acc_trace command
`File "/home/Projects/Clip_TorchTRT/clip/model.py", line 227, in forward`
`    x = torch.cat([self.class_embedding.to(x.dtype) + torch.zeros(x.shape[0], 1, x.shape[-1], dtype=x.dtype, device=x.device), x],` `dim=1)  # shape = [*, grid ** 2 + 1, width]`
`TypeError: zeros() received an invalid combination of arguments - got (Proxy, int, Proxy, device=Attribute, dtype=Attribute), but` `expected one of:`
` * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool` `requires_grad)`
` * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool` `requires_grad)`

* The model is published in OpenAI's github-
https://github.com/openai/CLIP

@OronG13

**Comment by frank-wei** [comment]
@DanielLevi6  that is the limitation from fx. The loop is not traceable in fx. We can not really work around it.

**Comment by yinghai** [comment]
The workaround is to wrap the code with for loop with a Module and mark it as a leaf node so we don't trace into it.  @frank-wei, could you maybe give an example of this?
