### ISSUE TITLE
❓ [Question] Request for a model which is supported by Torch-TRT(FX)

### ISSUE THREAD

**Issue by DanielLevi6** [pytorch/TensorRT#1882]
## ❓ Question

I'm trying to evaluate the Torch-TensorRT tool, using FX backend for running models in the C++ library.
My goal is to convert models which are not fully supported by TRT, and accelerate them by running some of the sub-graphs on TRT(as explained by this notebook- https://github.com/pytorch/TensorRT/blob/main/examples/fx/fx2trt_example_next.py)

The steps I have already completed-
- I converted a small model which is fully supported by TRT, and I received a single sub-graph as expected.
  The model runs successfully using the python lib, and the C++ lib also.
- I have already tried to convert the Resnet50 model, and did it successfully. But this is a fully TRT supported model.
- I converted a small model with a TRT unsupported operator, so the model was divided to 3 sub-graphs.
  The model runs successfully using the python Torch-TensorRT lib, and the C++ lib also.
  The problem is that the Torch-TensorRT model's latency is twice bigger than the original Torch model's latency.

I thought that maybe there is overhead because of the passes between sub-graphs on Torch and TRT back and forth. So I want to take a larger model, which is not fully supported by TensorRT, but still supported by Torch-TensorRT(by dividing the graph to TRT and Torch sub-grpahs, using the FX backend).
I tried some models, but I can't find such a model.
Is there a model that you tested the tool with?

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 2.0
 - CPU Architecture: x86-64
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): -
 - Are you using local sources or building from archives: Torch-TensorRT which has been built from sources
 - Python version: 3.8.10
 - CUDA version: 11.8
 - GPU models and configuration: NVIDIA T1000
 - Any other relevant information: -

@OronG13

**Comment by narendasan** [comment]
@gs-olive do you have a transformer model you can recommend? Also you can always disable support for an operator to simulate lack of full support.

**Comment by gs-olive** [comment]
Many of the transformers have dynamic control flow which makes FX tracing challenging without code modifications. Some examples of alternative models which do compile successfully in Torch-TRT's FX path are:

- `mobilenet_v2` as in `import torchvision; torchvision.models.mobilenet_v2(pretrained=True).eval().to("cuda")`
- `efficientnet_b0` as in `import timm; timm.create_model("efficientnet_b0", pretrained=True).eval().to("cuda")`

**Comment by DanielLevi6** [comment]
@gs-olive 
Actually these models are fully supported by TensorRT. I want to evaluate a model which is not fully supported by TensorRT, so it will be divided to sub-graphs which will run also on Torch. I couldn't find such a model up until now.

@narendasan 
What you wrote about the disable of operators could be a good solution for my problem. Is there any example for what you're suggesting?

Thank you both

**Comment by narendasan** [comment]
@DanielLevi6 You should be able to use the `leaf_module_list` api with FX to force a module to run in PyTorch. This test case should demonstrate how to use it. https://github.com/pytorch/TensorRT/blob/25db25768c31f976adff59e7ab3e2192b71b6968/py/torch_tensorrt/fx/test/tracer/test_acc_tracer.py#LL894C6-L894C6

Also there is a new api compatibility layer between FX and TorchScript in release/1.4 where youd use the `torch_executed_ops` API just like torchscript
