### ISSUE TITLE
how to convert itensor to pytorch tensor in torch-tensorrt fx mode?

### ISSUE THREAD

**Issue by shuyuan-wang** [pytorch/TensorRT#1920]
Hi:
I'm trying to create engine with custom plugin using torch-tensorrt fx. How do I convert ITensor to torch tensor?

**Comment by narendasan** [comment]
See this example: https://github.com/pytorch/TensorRT/blob/ac3ab77a307e2ce14aa0a3a1873ef02ec4aa262a/core/plugins/impl/interpolate_plugin.cpp#L263

**Comment by shuyuan-wang** [comment]
Hi, Thank you for your info, What I was trying to do is to convert the ITensor get from plugin output and convert it to pytorch tensor in python end. Is there an example?
