### ISSUE TITLE
🐛 [Bug] ERROR: [Torch-TensorRT] - 3: [runtime.cpp::~Runtime::346] Error Code 3: API Usage Error (Parameter check failed at: runtime/rt/runtime.cpp::~Runtime::346, condition: mEngineCounter.use_count() == 1.

### ISSUE THREAD

**Issue by sanbuphy** [pytorch/TensorRT#1934]
##  Bug Description

Hello, I have encountered an bug when loading and running a model generated with torch-tensorrt. Could you please advise on how to resolve the following error? Thank you.

![image](https://github.com/pytorch/TensorRT/assets/96160062/e935a999-346d-4c2a-a421-92a3cbc7430f)

## To Reproduce

```python
 model_trt = torch.jit.load('test.trt')
y = model_trt(img_LR)
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):  1.3
 - PyTorch Version (e.g. 1.0):  1.3.1
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by narendasan** [comment]
Can you share your model and compilation code so we can understand better what is going on?

**Comment by sanbuphy** [comment]
> Can you share your model and compilation code so we can understand better what is going on?

sure, could you give me  your email?  i will send an email include the code and files

**Comment by yifeili518** [comment]
> > Can you share your model and compilation code so we can understand better what is going on?
> 
> sure, could you give me your email? i will send an email include the code and files

have you sovled the bug? I met the same problem when using torch_tensorrt

**Comment by sanbuphy** [comment]
> > > Can you share your model and compilation code so we can understand better what is going on?
> > 
> > 
> > sure, could you give me your email? i will send an email include the code and files
> 
> have you sovled the bug? I met the same problem when using torch_tensorrt

I change the docker than run the torch_tensorrt and the problem be solved

**Comment by ZacharyGong** [comment]
> > > > Can you share your model and compilation code so we can understand better what is going on?
> > > 
> > > 
> > > sure, could you give me your email? i will send an email include the code and files
> > 
> > 
> > have you sovled the bug? I met the same problem when using torch_tensorrt
> 
> I change the docker and than rerun the torch_tensorrt and the problem be solved

Hi, I'm seeing the same issue. Could you please share what is the docker you were using, or what is the torch_tensorrt you used?

**Comment by mlaves** [comment]
I have the same issue and would also be very interested in the exact docker container you used.

**Comment by sanbuphy** [comment]
@mlaves  @ZacharyGong  Hi guys. I recommand you use the NGC docker and it can help you :https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorrt/tags

**Comment by dugushiyu** [comment]
runtime要先声明，而mEngine要后声明，才能达到后声明的先析构，先声明的后析构的目的，所以runtime要放在mEngine前面。
context也必须在mEngine后面，否则会报类似的顺序报错。
