### ISSUE TITLE
✨[Feature] Add support for `truncate_long_and_double` in Dynamo compile

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#1964]
# Context
Certain models, including T5 (see #1864, #1740) require INT64 inputs to their embedding layers. 64-bit input types are not compatible with TRT Engines, however, thus a truncation mechanism is necessary to resolve this issue.

# Feature Proposal
Add support for `truncate_long_and_double` in Dynamo compile, tracking data types and automatically casting to TRT-allowed types (and back) as necessary.

**Comment by narendasan** [comment]
@gs-olive We have this issue in review but the linked PR is closed, do we need to point this issue at a new PR?

**Comment by gs-olive** [comment]
I reordered the linked PRs (there were two, one of which had been closed), and now the issue should be resolved.
