### ISSUE TITLE
🐛 [Bug] Missing directory and file in FX path (Python only) installation

### ISSUE THREAD

**Issue by HolyWu** [pytorch/TensorRT#1976]
##  Bug Description

1. `torch_tensorrt.fx.converters.impl` was not added to the `packages` and `package_dir` list, hence the `impl` directory was not installed.
2. `_Input.py` was not installed even though you had added it to `package_data` because `torch_tensorrt` was not in the `packages` list in FX_ONLY. Instead, you have to use [py_modules](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#py-modules) to copy modules that aren't part of a package.
3. `_Input.py` imported `_enums.py` which was also not installed in FX_ONLY. And `_enums.py` imported stuff from `torch_tensorrt._C` which was unavailable in FX_ONLY.
4. `torch_tensorrt/dynamo/__init__.py` imported `compile` from `torch_tensorrt/dynamo/backend`, but the `backend` directory was not installed in FX_ONLY.

## To Reproduce

`python3 setup.py install --fx-only`

## Environment

 - Torch-TensorRT Version (e.g. 1.0.0): 1.4.0
 - PyTorch Version (e.g. 1.0): 2.0.1+cu118
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.11.3
 - CUDA version: 11.8
 - GPU models and configuration:
 - Any other relevant information:

**Comment by gs-olive** [comment]
Thank you for reporting this - regarding the Dynamo comments, our `torch_tensorrt.dynamo` path still has a few C++ dependencies, and so it is currently not able to be imported without the full `python setup.py install`, though we have open issues to resolve this: #1943, #1993.

**Comment by apbose** [comment]
Hi, thanks for reporting the issue. I wanted to clarify. I have added `torch_tensorrt.fx.converters.impl` to package list and I do see it in the site_packages of torch_tensorrt installed, however even if I do not mention the  `torch_tensorrt.fx.converters.impl`  in package list, the impl is still installed. So I wanted to clarify on what issue you are facing currently. Thanks!

**Comment by HolyWu** [comment]
https://colab.research.google.com/drive/1hJwftiDT1U7rzGu_YeuVA9rrffikCvR6?usp=sharing

**Comment by apbose** [comment]
Ok, looking into this.

**Comment by apbose** [comment]
Thanks for the repo steps above.
So when I install using` python setup.py install --fx-only --release` and do `import torch_tensorrt.fx` it shows `ModuleNotFoundError: No module named 'torch_tensorrt._C`.  As mentioned earlier since dynamo still has C++ dependencies these won't be imported until we do the full `python setup.py install`

**Comment by apbose** [comment]
From `torch_tensorrt._compile import * `  ts  package is getting imported ( torch_tensorrt/_compile.py ).
--fx-only  is not working properly at the moment. PEP517- https://github.com/pytorch/TensorRT/pull/2056 changes should address the cross C++ and python dependencies
