### ISSUE TITLE
Add example scripts for module/function level acceleration

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#1984]
- Add step-by-step instructions in `.rst` format for excluding specific modules or functions from Dynamo tracing

**Comment by gs-olive** [comment]
Pending #1966

**Comment by narendasan** [comment]
@gs-olive is this still blocked?

**Comment by gs-olive** [comment]
This is dependent on #1966, #1979, #1980, so to avoid issues in the PR dependency graph, I haven't pushed a PR for it yet.

**Comment by gs-olive** [comment]
Blocked by #1985

**Comment by gs-olive** [comment]
In-progress #2103 and future development.
