### ISSUE TITLE
Centralize converters for `MaxPool1D` and `einsum`

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#1985]
- Utilize new `impl` directory to centralize converters for key ops across FX compilation formats
- See #1979, #1980

**Comment by narendasan** [comment]
@gs-olive is this still blocked?

**Comment by gs-olive** [comment]
Pending discussion on the best location for converters such as those introduced in #1979, #1980. Is it preferable to move those converters to a central location even though the code that repairs the FX graph to add those ops is elsewhere?

**Comment by gs-olive** [comment]
Addressed in #2317

**Comment by gs-olive** [comment]
Completed on main for maxpool. Einsum pending.
