### ISSUE TITLE
🐛 [Bug] Torch-TensorRT takes long time to compile densenet161

### ISSUE THREAD

**Issue by Anlarry** [pytorch/TensorRT#2016]
##  Bug Description

torch_tensorrt cannot finish compiling densenet161, and there is no outputted logging.

## To Reproduce

1. Create a conda environment, install pytorch, torch_tensorrt
2. Run the following code to compile densenet161

```python
import torch
import torch_tensorrt
torch.hub._validate_not_a_forked_repo=lambda a,b,c: True
from torchvision import models

# load model
model = torch.hub.load('pytorch/vision:v0.10.0', 'densenet161', pretrained=True).eval().to("cuda")

# Compile with Torch TensorRT;
trt_model = torch_tensorrt.compile(model,
    inputs= [torch_tensorrt.Input((1, 3, 224, 224))],
    # enabled_precisions= { torch.half} # Run with FP32
)

# Save the model
torch.jit.save(trt_model, "model.pt")
```

## Expected behavior

torch_tensorrt will save the compiled model as quickly as resnet152.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version: 1.2.0
 - PyTorch Version: 1.12.1
 - CPU Architecture: x86_64
 - OS: Linux
 - How you installed PyTorch: conda
 - Are you using local sources or building from archives: building from archives
 - Python version: 3.10
 - CUDA version: 11.6
 - GPU models and configuration: V100

## Additional context

I tried to compile vgg16 and resnet, all works perfectly.

**Comment by peri044** [comment]
@bowang007  try with dynamo to verify

**Comment by bowang007** [comment]
Densenet161 can be successfully converted in Dynamo. 
Closing.
