### ISSUE TITLE
🐛 [Bug] Segmentation fault when using int8 precision 

### ISSUE THREAD

**Issue by AhmetHamzaEmra** [pytorch/TensorRT#2018]
##  Bug Description

tensorrt cannot work with int8 precision when using on NanoGPT like (bark text-to-audio) model.

## To Reproduce

```
inp1, inp2 = get_sample_input()

inp1 = torch.unsqueeze(inp1, 0)

traced_model = torch.jit.trace(model, example_inputs=[inp1, inp2])

batch_size = 1

trt_model = torch_tensorrt.compile(
    traced_model,
    inputs = [  torch_tensorrt.Input((batch_size,1), dtype=torch.long), 
                torch_tensorrt.Input((batch_size, 1024, 8), dtype=torch.long)],
    enabled_precisions = { torch.int8},
    workspace_size=20000000000,
    truncate_long_and_double = True
)
```

and I am getting following error:

```
Segmentation fault
```

## Expected behavior

When I run the same code on float32 or half precion everyting works fine. only happens when its int8

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): '1.4.0'
 - PyTorch Version (e.g. 1.0): 2.0.1+cu117
 - CPU Architecture: x64
 - OS (e.g., Linux): WSL 
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives: Local
 - Python version: Python 3.10.6
 - CUDA version: 11.5
 - GPU models and configuration: 4090
 - Any other relevant information:

**Comment by SongDabao** [comment]
I have the same issue, any update in this?

**Comment by AhmetHamzaEmra** [comment]
I am waiting for an update too 😅

**Comment by AhmetHamzaEmra** [comment]
Why are you guys keep closing the issue? We are still waitign for an update ?????
