### ISSUE TITLE
❓ [Question] Torch-TensorRT 1.3.0 uses cuDNN 8.6.0 instead of 8.5.0

### ISSUE THREAD

**Issue by akaimody123** [pytorch/TensorRT#2028]
## ❓ Question

Hi, I am using torch-tensorRT 1.3.0, it seems it is linked to cuDNN 8.6.0 instead of 8.5.0 as described in the release note? Please find my environment setup below

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.13.1 with cu117
 - OS (e.g., Linux): Linux (ubuntu 20.04)
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
 - Python version:3.8
 - CUDA version: 11.7
 - TensorRT: 8.5.3.1
 - torch-tensorrt: 1.3.0

I got the warning: tensorrt is linked to cuDNN 8.6.0 but cuDNN 8.5.0 is loaded --- when i print torch.backend.cudnn.version() it says 8500, so I assume if torch-tensorrt is linked with cuDNN as it is described in the release note, there should not be such warning?
Could you please let me know if there is something I'm doing wrong? Thank you!

**Comment by narendasan** [comment]
Yeah this warning is because we typically default to PyTorch's cuDNN choice vs. TensorRT because PyTorch has a stricter dependency (we have observed crashes otherwise in the past). TensorRT supports 8.5 in 8.5.3.1 even though it was built with 8.6.0
