### ISSUE TITLE
❓ [Question] How can I install the latest version of python API? Torch and Tensorrt's CUDA dependencies conflict with each other.

### ISSUE THREAD

**Issue by 1585231086** [pytorch/TensorRT#2044]
## What you have already tried

I have already create a python=3.9 env, when I use the command 'pip install torch-tensorrt', I find that the torch version that the latest torch-tensorrt needs is 2.0.1 and the tensorrt version it needs is 8.6.1, but these two packages need different cuda versions(which one is cu11 and another is cu12). When I run a simple model(input) example python code, torch can't resolve the environment. 
## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 2.0.1
 - CPU Architecture: x86_64
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): pip install torch-tensorrt
 - Are you using local sources or building from archives: archives
 - Python version: 3.9
 - tensorrt version: 8.6.1

## Additional context
example python code:
```
import torch
#import torch_tensorrt #No tensorrt and torch_tensorrt installed, this code will run successfully.
conv=torch.nn.Conv2d(3,32,3,1,0,bias=False)
input=torch.randn(1,3,224,224)
conv.cuda()
input.cuda()
print(conv(input).shape)
```

**Comment by narendasan** [comment]
Can you post the error you are seeing?

**Comment by 1585231086** [comment]
before I install the tensorrt, the example code can be run succsessfully, but after installing, here will report an error:
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

**Comment by 1585231086** [comment]
> Can you post the error you are seeing?

This problem maybe has been solved. I firstly install tensorrt==8.6.1, and then install torch==2.0.1, which is ok.

**Comment by 1585231086** [comment]
There is another problem, when I use function torch_tensorrt.compile(*) to compile a torch ts model,  it shows WARNINGs and auto exits running. WARNING info is as follows,
```bash
WARNING: [Torch-TensorRT TorchScript Conversion Context] - Unable to determine GPU memory usage
WARNING: [Torch-TensorRT TorchScript Conversion Context] - Unable to determine GPU memory usage
WARNING: [Torch-TensorRT TorchScript Conversion Context] - CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
```
The env packages and versions are as follows,
```bash
nvidia-cublas-cu11       11.10.3.66
nvidia-cublas-cu117      11.10.1.25
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu11        8.5.0.96
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
packaging                23.1
safetensors              0.3.1
tensorrt                 8.6.1
tensorrt-bindings        8.6.1
tensorrt-libs            8.6.1
torch                    2.0.1
torch-tensorrt           1.4.0
torchvision              0.15.2
```

**Comment by narendasan** [comment]
What driver are you running? Can you share the output of `nvidia-smi`?

**Comment by 1585231086** [comment]
> What driver are you running? Can you share the output of `nvidia-smi`?
The driver and cuda version are as follows,
 NVIDIA-SMI 470.42.01    Driver Version: 470.42.01    CUDA Version: 11.4

The GPU is a Tesla T4.
