### ISSUE TITLE
🐛 [Bug] TRT Error when compiling ViT with Dynamic Shape

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#2075]
##  Bug Description
See #2074 for code + model description

```python
ERROR: [Torch-TensorRT - Debug Build] - 3: [executionContext.cpp::setInputShape::2264] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2264, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape.
```

## To Reproduce
See #2074

## Expected behavior

Model should compile with Dynamic shapes.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 8b09e718a3694c28ba02dd8fdf30a26df0076bb3
 - PyTorch Version (e.g. 1.0): `2.1.0.dev20230620+cu118`
 - TensorRT Version: `8.6.1`

**Comment by shiyongde** [comment]
same problem

**Comment by Hukongtao** [comment]
still have
