### ISSUE TITLE
🐛 [Bug] Error while loading Torch-TensorRT ResNet50

### ISSUE THREAD

**Issue by agunapal** [pytorch/TensorRT#2088]
##  Bug Description

Not able to jit load a tensorrt model

## To Reproduce

1.
Create a torch tensorrt model using
```
from torchvision.models import resnet50, ResNet50_Weights
import torch_tensorrt
import torch

model = resnet50(weights=ResNet50_Weights.IMAGENET1K_V2)

model.eval()

trt_model_fp32 = torch_tensorrt.compile(model, inputs = [torch_tensorrt.Input((128, 3, 224, 224), dtype=torch.float32)],
    enabled_precisions = torch.float32, # Run with FP32
    workspace_size = 1 << 22
)
torch.jit.save(trt_model_fp32, "trt_model_fp32.ts")
```
2. Load the model
```
>>> import torch
>>> model = torch.jit.load("trt_model_fp32.ts")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/torchserve/lib/python3.10/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError: 
Unknown type name '__torch__.torch.classes.tensorrt.Engine':
  File "code/__torch__/torchvision/models/resnet.py", line 4
  __parameters__ = []
  __buffers__ = []
  __torch___torchvision_models_resnet_ResNet_trt_engine_ : __torch__.torch.classes.tensorrt.Engine
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  def forward(self_1: __torch__.torchvision.models.resnet.ResNet_trt,
    input_0: Tensor) -> Tensor:

```
4.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.5.0.dev0
 - PyTorch Version (e.g. 1.0): 2.1.0a0+4136153
 - CPU Architecture:
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): `nvcr.io/nvidia/pytorch:23.06-py3`
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives: using `nvcr.io/nvidia/pytorch:23.06-py3`
 - Python version: 3.10
 - CUDA version: CUDA 11.7
 - GPU models and configuration:
 - Any other relevant information:

**Comment by narendasan** [comment]
You still need to have `torch_tensorrt` imported to load torch-tensorrt programs even at runtime, as it will register an extension to the torchscript runtime to execute the TRT engines. 
Adding `import torch_tensorrt` to your program with all else the same should address the `Unknown type name '__torch__.torch.classes.tensorrt.Engine'` error

**Comment by agunapal** [comment]
Thanks! That worked
