### ISSUE TITLE
✨[Feature] Does torch_tensorrt have a smaller runtime environment?

### ISSUE THREAD

**Issue by sanbuphy** [pytorch/TensorRT#2100]
**Is your feature request related to a problem? Please describe.**

NO
**Describe the solution you'd like**

Hello, I think torch_tensorrt is great, but every time I install its Python environment, it always requires a lot of dependencies. This makes my Docker image very large. Is there a way to have a smaller runtime environment that can still support inference with torch_tensorrt? Thank you very much.
**Describe alternatives you've considered**

N O
**Additional context**

NO

**Comment by narendasan** [comment]
Yes, the only dependencies needed to run a compiled torch_tensorrt module are `libtorchtrt_runtime.so` (~1MB), perhaps `libtorchtrt_plugins.so` if you are utilizing those plugins, `libnvinfer.so` + its deps (tensorrt) and pytorch how ever you want to include that.
https://pytorch.org/TensorRT/tutorials/runtime.html

**Comment by sanbuphy** [comment]
> Yes, the only dependencies needed to run a compiled torch_tensorrt module are `libtorchtrt_runtime.so` (~1MB), perhaps `libtorchtrt_plugins.so` if you are utilizing those plugins, `libnvinfer.so` + its deps (tensorrt) and pytorch how ever you want to include that. https://pytorch.org/TensorRT/tutorials/runtime.html

It sounds like pybind?  Thank you very much!

**Comment by sanbuphy** [comment]
> Its not really pybind, it just registers the extension to the torchscript runtime needed to run torch-tensorrt
Get it ,and I have another question,  what's the different between torch_tensorrt IR and tensorrt engine IR？ Can I translate is into the trt engine and that use the trt api?  Thank you very much.
