### ISSUE TITLE
❓ [Question] How can I learn to convert an intermediate format IR to the TensorRT target?

### ISSUE THREAD

**Issue by sanbuphy** [pytorch/TensorRT#2108]
## ❓ Question

Hello, I am also currently working on something similar to PyTorch FX. I would like to convert an intermediate format graph into a target engine (which can be any inference framework, using TensorRT as an example). I wanted to ask how Torch TRT accomplishes this operation. Are there any source code or documentation resources that I can refer to? Thank you very much!

**Comment by narendasan** [comment]
https://github.com/pytorch/TensorRT/blob/d4c9c06213602c6e8d2ce568154ed287ee67dafd/py/torch_tensorrt/fx/fx2trt.py#L36

This is the core logic for pulling up functions from a function table to incrementally create the graph in tensorrt

**Comment by sanbuphy** [comment]
> https://github.com/pytorch/TensorRT/blob/d4c9c06213602c6e8d2ce568154ed287ee67dafd/py/torch_tensorrt/fx/fx2trt.py#L36
> 
> This is the core logic for pulling up functions from a function table to incrementally create the graph in tensorrt

Thank you very much, I will take a look.
