### ISSUE TITLE
🐛 [Bug] TensorRT dependecy not installed when using Torch-TensorRT 1.4.0

### ISSUE THREAD

**Issue by ivan94fi** [pytorch/TensorRT#2110]
##  Bug Description

Installing the torch_tensorrt package version 1.4.0 from pip with `pip install torch_tensorrt==1.4.0` does not install the required `tensorrt` package.

## To Reproduce

Use `pip install torch_tensorrt==1.4.0`

Run this python line:

```python
import tensorrt
```

## Expected behavior

TensorRT should be installed as a dependecy of this package.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.4.0
 - PyTorch Version (e.g. 1.0): 2.0.1
 - CPU Architecture: x86
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): installed by torch_tensorrt
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.10
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

The 1.3.0 wheels contain this line in the METADATA files:
```
Requires-Dist: torch (<1.14.0,>=1.13.0)
Requires-Dist: tensorrt (<8.6.0,>=8.5.1.7)
```

The 1.4.0 wheels contain only
```
Requires-Dist: torch (<2.1,>=2.0.1)
```

**Comment by narendasan** [comment]
Is just installing tensorrt separately not working for you? We can fix this in the next release but we would not address this in 1.4.0 unless this causes actual issues using the library.

**Comment by ivan94fi** [comment]
Installing tensorrt separately works, but it is not the expected workflow. If you do not plan to release a new patch version before the next release, I suggest to update the [Prebuilt binaries and wheel files](https://github.com/pytorch/TensorRT#prebuilt-binaries-and-wheel-files) section in the readme: a simple note that suggests to install tensorrt separately would be enough.

By the way, maybe you are already aware of this, or even it was a design decision, but I think the cause of this behavior is that the `setup.py` file does not contain anymore the `tensorrt` package in the `install_requires` parameter of `setup()`:

Tag 1.3.0:
https://github.com/pytorch/TensorRT/blob/8dc1a0648ee7c07667d96e2a2871ef0219e3a8f1/py/setup.py#L378

Tag 1.4.0:
https://github.com/pytorch/TensorRT/blob/7d1d807731c95ffbaa980a3742e289d4184b7871/py/setup.py#L428-L430
