### ISSUE TITLE
✨[Feature] Move `_C` code out of `_util.py`

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#2121]
# Context
PR #2118 moves key version-checking functionality into a utilities file which imports `_C`. This file, `_util.py` needs to be refactored and/or imported differently to allow use of the utility without pulling in the C dependency, which is undesirable for users who prefer to use Python-only runtimes or install a lightweight version of the repository.

# Proposal
See 38a2c4cf1694d39d5cf0e17df4db07300d0955fd for a potential solution. In short, one can move the `_C`-dependent utilities to the `ts` directory and update the imports, with a new utilities file being created in the main directory.

**Comment by narendasan** [comment]
Some of the _C code can be reimplemented in Python as well. Particularly the build_info stuff
