### ISSUE TITLE
❓ Why the speed (time) in PTQ and QAT are different? 

### ISSUE THREAD

**Issue by panahikhas** [pytorch/TensorRT#2122]
## ❓ Why the speed (time) in PTQ and QAT are different? 

I used your sample notebook.
The link is https://github.com/pytorch/TensorRT/blob/main/notebooks/qat-ptq-workflow.ipynb.
I also performed this approach on some other models. In all cases like your example the PTQ converted model is faster than QAT converted model.

I think they must have the same speed because their process is the same just some weights are different. Speeds must be the same. Is this for your implementation or this is typical?
Can I make QAT converted model faster like PTQ?

**Comment by peri044** [comment]
PTQ is faster than QAT since the whole model is quantized usually. In QAT, a subset of layers will be quantized. You can enable verbose logging with profiling to check the engine profiles between PTQ and QAT.
