### ISSUE TITLE
❓ [Question] Could torch-tensorrt support mixed-precision inference?

### ISSUE THREAD

**Issue by sanbuphy** [pytorch/TensorRT#2159]
## ❓ Question

Hello, in my PyTorch inference, I initially set the entire model to fp16 and provided fp16 inputs. Considering the output will become `NAN` (transformer model) , and then I used `.to()` to switch certain weight layers and inference parameters back to fp32. 

However, if I export it to ONNX and convert to TensorRT, I would need to make those settings again in TensorRT, which can be quite complicated.

 I would like to know if the torch_tensorrt export includes these dependence and if it can automatically perform mixed-precision export to TensorRT based on my settings. Thank you!

**Comment by sanbuphy** [comment]
@narendasan  Hi , could you help me take a look, Thank you very much

**Comment by narendasan** [comment]
This is currently not supported. We use TensorRT's behavior for automatic mixed precision
