### ISSUE TITLE
❓ [Question] Is a INT8 calibrator specific to a given model or just specific to a dataset?

### ISSUE THREAD

**Issue by laclouis5** [pytorch/TensorRT#2167]
## ❓ Question

Is a INT8 calibrator specific to a given model or just specific to a dataset?

INT8 calibrators can be cached to accelerate further usage, which is nice. However, it's not clear from the documentation if the cached calibrator can only be used to calibrate the model it was used for TensorRT conversion or any model that uses the same calibration dataset.

As a practical example, let say that I'm training and comparing two classification neural networks A and B on the same dataset and with the same data preprocessing. I converted network A for TensorRT using INT8 quantization and saved the calibrator cache file. to disk. Can I use this calibrator to convert model B to TensorRT (which otherwise would have used the same calibration dataset as A)?

My intuition is that a calibrator is specific to given dataset **and** network and it cannot be reused for a different network.

**Comment by narendasan** [comment]
A DatasetCalibrator is specific to a dataset and can be resused, but the cache will be specific a specific model

**Comment by laclouis5** [comment]
Thank you!
