### ISSUE TITLE
✨[Feature] An idea about a new feature in Torch-TensorRT Version for Windows

### ISSUE THREAD

**Issue by My12123** [pytorch/TensorRT#2247]
- [ ] Version for Windows
```[tasklist]
### Tasks
- [ ] Version for windows with installation via pip
```

**Comment by fmatulic** [comment]
Upvoting this request.
Building the library on Windows isn't straightforward, very error prone, and according to [the installation guide](https://pytorch.org/TensorRT/getting_started/installation.html), with [the recommended method using CMake](https://pytorch.org/TensorRT/getting_started/getting_started_with_windows.html), the Python API isn't created.

**Comment by jensdraht1999** [comment]
> Upvoting this request. Building the library on Windows isn't straightforward, very error prone, and according to [the installation guide](https://pytorch.org/TensorRT/getting_started/installation.html), with [the recommended method using CMake](https://pytorch.org/TensorRT/getting_started/getting_started_with_windows.html), the Python API isn't created.

I wanted to ask you, is there a way to create the python api somehow or download a pytorch version with trt support somehow or is is not possible?

**Comment by narendasan** [comment]
We are working on Python on windows but it will likely be Dynamo only. Getting good UX for the build system (both for linux and windows) has been the blocker. https://github.com/pytorch/TensorRT/tree/windows_dynamo_testing
