### ISSUE TITLE
🐛 [Bug] placeholder node meta data not preserved in fast partitioning

### ISSUE THREAD

**Issue by peri044** [pytorch/TensorRT#2258]
##  Bug Description

placeholder node meta data not preserved in fast partitioning but works in global partitioning

## To Reproduce

1.
2.
3.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):
 - PyTorch Version (e.g. 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by gs-olive** [comment]
Maybe be fixed by https://github.com/pytorch/pytorch/pull/107248
