### ISSUE TITLE
🐛 [Bug] Input bindings change b/w fast and global partitioner

### ISSUE THREAD

**Issue by peri044** [pytorch/TensorRT#2260]
##  Bug Description

Global partitioner:
```
Torch-TensorRT TensorRT Engine:
  Name: fused_0_engine
  Inputs: [
    id: 0
      name: arg0
      shape: [1, 3, 224, 224]
      dtype: Float
    id: 1
      name: _param_constant0
      shape: [16, 3, 3, 3]
      dtype: Float
    id: 2
      name: _param_constant1
      shape: [16]
      dtype: Float
  ]
```
Fast partitioner:
```
Torch-TensorRT TensorRT Engine:
  Name: fused_0_engine
  Inputs: [
    id: 0
      name: arg0
      shape: [1, 3, 224, 224]
      dtype: Float
  ]
```

## To Reproduce

1.
2.
3.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):
 - PyTorch Version (e.g. 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by zewenli98** [comment]
@peri044
