### ISSUE TITLE
🐛 [Bug] Slowdown due to cudaGetDeviceProperties_v2 CUDA API call when using C++ TRT backend

### ISSUE THREAD

**Issue by austinapatel** [pytorch/TensorRT#2266]
##  Bug Description

When using the Dynamo TorchTRT path on the network provided below, there is a 2x slowdown compared to PyTorch eager mode. The NSight Systems trace reveals that the slowdown is due to `cudaGetDeviceProperties_v2` calls from the CUDA API that happen during each engine execution. I am able to reproduce this slowdown when using the C++ TRT API (`use_python_runtime=False` in the call to `torch_tensorrt.compile`), but am not able to reproduce this issue with the Python TRT API (`use_python_runtime=True`).

With C++ API:
![cpp_api_annotated](https://github.com/pytorch/TensorRT/assets/15927999/48dbc930-e277-471f-9e19-4a2d081d2035)

With Python API:
![python_api_annotated](https://github.com/pytorch/TensorRT/assets/15927999/5a2b589e-4945-4599-9fed-d907577631ae)

## To Reproduce

Profiling command: `nsys profile --trace cuda,nvtx --sample cpu --force-overwrite true --output profiling_results/tmp --gpu-metrics-device=all --gpu-metrics-frequency=20000 python torchtrt_cudadeviceissue_minified.py`

1. Set `use_python_runtime=False` to use C++ API and run profiling command
2. Set `use_python_runtime=True` to use Python API and run profiling command

`torchtrt_cudadeviceissue_minified.py`:
```python
import torch
from torch import nn
from torch.nn import functional as F
import torch_tensorrt

"""NETWORK"""
class SimpleNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10, 100)
        self.fc2 = nn.Linear(100, 5)
        self.mha = nn.MultiheadAttention(embed_dim=5, num_heads=1)
        self.conv = nn.Conv1d(10, 2, 1)
    
    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        x = F.relu(x)
        x, _ = self.mha(x, x, x)
        x = F.relu(x)
        return x

"""PROFILING UTILITIES"""
def timed(fn, msg):
    torch.cuda.synchronize()
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)
    torch.cuda.nvtx.mark(f'timed start: {msg}')
    start.record()
    result = fn()
    end.record()
    torch.cuda.nvtx.mark(f'timed end: {msg}')
    torch.cuda.synchronize()
    return result, start.elapsed_time(end)


def profile(method, nvtx_msg=None):
    # profiling
    print('Profiling with torch NVTX markers enabled')
    torch.cuda.cudart().cudaProfilerStart()
    with torch.autograd.profiler.emit_nvtx(record_shapes=True):
        if nvtx_msg:
            torch.cuda.nvtx.mark(f'profile start: {nvtx_msg}')
        result = method()
        if nvtx_msg:
            torch.cuda.nvtx.mark(f'profile end: {nvtx_msg}')
    torch.cuda.cudart().cudaProfilerStop()

    return result


def run_two_models(model1, model2, inp):
    torch.cuda.synchronize()

    output1, time1 = timed(lambda: model1(inp), f'profiling model1')
    output2, time2 = timed(lambda: model2(inp), f'profiling model2')

    return time1, time2

"""MAIN"""
if __name__ == '__main__':
    inp = torch.ones((10,10), device='cuda:0')

    # Eager
    eager_model = SimpleNetwork()
    eager_model.to('cuda:0').eval()
    print(f'Calling eager model')
    eager_model(inp)

    # TorchTRT
    torch._dynamo.reset()
    trt_model = torch_tensorrt.compile(eager_model, ir="torch_compile", inputs=inp, use_python_runtime=False)
    print(f'Calling trt_model')
    trt_model(inp)

    # Profiling
    time_eager, time_trt = profile(lambda: run_two_models(eager_model, trt_model, inp))
    print(f'Eager time: {time_eager}ms\nTime TRT: {time_trt}ms')
```

Note if you are TorchTRT debug build you might get an error about profiling already being enabled. In this case you can either:
1. Replace `time_eager, time_trt = profile(lambda: run_two_models(eager_model, trt_model, inp))` with `time_eager, time_trt = run_two_models(eager_model, trt_model, inp)`
2. Change https://github.com/pytorch/TensorRT/blob/b774440657f3f998b785a65fe7504e8efc8c67b6/setup.py#L141 from `dbg` to `opt` and re-build TorchTRT.

Script output with `use_python_runtime=False`:
```
Calling eager model
Calling trt_model
Profiling with torch NVTX markers enabled
Eager time: 1.5432000160217285ms
Time TRT: 3.0739200115203857ms
```

Script output with `use_python_runtime=True`:
```
Calling eager model
Calling trt_model
Profiling with torch NVTX markers enabled
Eager time: 1.5895999670028687ms
Time TRT: 1.4472320079803467ms
```

Note the much faster TRT performance with `use_python_runtime=True`.

## Expected behavior

Did not expect `cudaGetDeviceProperties_v2` calls to make TRT slower than eager execution when using C++ TRT API.

## Environment
 - Torch-TensorRT Version (e.g. 1.0.0): commit `65c6494ce3107d33b27fdb1630ac7982f8649382` built from source
 - PyTorch Version (e.g. 1.0): `2.1.0a0+4136153` (commit `7682252cac9ed31055d2ae950cf6942dd311da73`)
 - CPU Architecture:
 - OS (e.g., Linux):  Ubuntu 22.04.2 LTS
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): source
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.10.6
 - CUDA version: 12.1
 - GPU models and configuration: NVIDIA A100 80GB PCIe
 - Any other relevant information:

**Comment by zewenli98** [comment]
@peri044

**Comment by narendasan** [comment]
Fixed with new multi-gpu specific safety runtime mode
