### ISSUE TITLE
↔ [Converter] Support starter `prims` operators

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#2295]
```python
- torch.ops.prims.var.default + Operator Count: 109
- torch.ops.prims.broadcast_in_dim.default + Operator Count: 218
- torch.ops.prims.sum.default + Operator Count: 109
- torch.ops.prims.div.default + Operator Count: 109
```
Either via decomposition or direct operator conversion.
Additional optimization idea: many prims operators are immediately followed by broadcasts, due to `keepdim`, which is not a supported argument in `prims`, but is supported in TRT reduce layers. Consider adding a lowering pass to coalesce these. For instance, we could have:

```python
- `torch.ops.prims.var.default` + `torch.ops.prims.broadcast_in_dim.default` --> `torch.ops.aten.var.default(..., keepdim=True)`
```
In this way, we would be able to convert `aten.var` _and_ `prims.var`, while enhacing performance.

**Comment by narendasan** [comment]
NB: https://github.com/pytorch/pytorch/blob/cd6a332bc500b70e92bc05af06c65fcbcbf4f123/torch/_prims/__init__.py#L277
