### ISSUE TITLE
↔ [Converter] Implement Converter for `aten.expand`

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#2299]
- **Function Schema:** [`expand`](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/native_functions.yaml#L2545-L2551)
- **Torch Documentation:** [`torch.expand`](https://pytorch.org/docs/stable/generated/torch.Tensor.expand.html)
- **C++ Implementation**
  - https://github.com/pytorch/TensorRT/blob/bb5bf0069a4198498d27f1ab827c2f80476768b9/core/conversion/converters/impl/expand.cpp#L199-L214

**Comment by zewenli98** [comment]
@apbose
