### ISSUE TITLE
❓ Why cant't I compile Torch-TensorRT 1.0.0? 

### ISSUE THREAD

**Issue by VictorIOVI** [pytorch/TensorRT#2318]
## What you have already tried

I've been trying to compile versions 1.0.0 and 1.1.0 of Torch-TensorRT in my Jetson Xavier NX 16GB, I had followed the official guides of installation mentioned in this [issue](https://github.com/pytorch/TensorRT/discussions/1077).

## Environment
I have the next environment:
- Jetpack 4.6
- Python 3.6.9
- Pytorch 1.10.0
- Torchvision 0.11.1
- CUDA 10.2
- CUDNN 8.2.1
- TensorRT 8.0.1.6
- GPU models and configuration: Jetson Xavier NX with JetPack 4.6

## The error
Finally, when I launch python3 py/setup.py install --use-cxx11-abi the error happend

`running install
using CXX11 ABI build
Jetpack version: 4.6
building libtorchtrt
INFO: Analyzed target //:libtorchtrt (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/iovi/SW/TensorRT/core/lowering/BUILD:10:11: Compiling core/lowering/register_trt_placeholder_ops.cpp failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 61 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
core/lowering/register_trt_placeholder_ops.cpp:16:34: error: invalid user-defined conversion from 'torch::jit::<lambda(torch::jit::Stack&)>' to 'torch::jit::OperationCreator {aka std::function<void(std::vector<c10::IValue>*)> (*)(const torch::jit::Node*)}' [-fpermissive]
         aliasAnalysisFromSchema()),
                                  ^
core/lowering/register_trt_placeholder_ops.cpp:15:24: note: candidate is: torch::jit::<lambda(torch::jit::Stack&)>::operator void (*)(torch::jit::Stack&)() const <near match>
         [](Stack& stack) { /*noop*/ },
                        ^
core/lowering/register_trt_placeholder_ops.cpp:15:24: note:   no known conversion from 'void (*)(torch::jit::Stack&) {aka void (*)(std::vector<c10::IValue>&)}' to 'torch::jit::OperationCreator {aka std::function<void(std::vector<c10::IValue>*)> (*)(const torch::jit::Node*)}'
In file included from external/libtorch/include/torch/csrc/jit/runtime/custom_operator.h:5:0,
                 from core/lowering/register_trt_placeholder_ops.cpp:1:
external/libtorch/include/torch/csrc/jit/runtime/operator.h:98:3: note:   initializing argument 2 of 'torch::jit::Operator::Operator(std::__cxx11::string, torch::jit::OperationCreator, c10::AliasAnalysisKind)'
   Operator(
   ^~~~~~~~
Target //:libtorchtrt failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 225,037s, Critical Path: 54,01s
INFO: 46 processes: 13 internal, 33 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
`

**Comment by janblumenkamp** [comment]
I attempted compiling it for the Jetson Orin NX in #1600 using a docker container, perhaps that's helpful?

**Comment by VictorIOVI** [comment]
In this case there is no Docker with Torch 1.10 for the Jetpack 4.6 so I can't use Docker to make the deployment of it unless I make a base image composed from what I've made before. In this case shouldn't be necessary to use docker, but thanks for the information!
