### ISSUE TITLE
❓ [Question] How to use C++ bindings for torch tensorrt with CMake?

### ISSUE THREAD

**Issue by janblumenkamp** [pytorch/TensorRT#2320]
## ❓ Question

I would like to know how to use the examples provided [here](https://github.com/pytorch/TensorRT/tree/v1.4.0/examples/torchtrt_runtime_example) with CMake. The instructions seem to indicate only how to use it with a makefile. CMake is not able to find `torchtrt`, exactly as described in #1207, but unfortunately that issue has been closed without actually resolving it.

I get the following error:
```
CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "Findtorchtrt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "torchtrt",
  but CMake did not find one.

  Could not find a package configuration file provided by "torchtrt" with any
  of the following names:

    torchtrtConfig.cmake
    torchtrt-config.cmake

  Add the installation prefix of "torchtrt" to CMAKE_PREFIX_PATH or set
  "torchtrt_DIR" to a directory containing one of the above files.  If
  "torchtrt" provides a separate development package or SDK, be sure it has
  been installed.
```

## What you have already tried

I noticed that there is a `python3.8/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake`, but there are no cmake files at all in my torch_tensorrt installation, which otherwise works perfectly fine:
```
root@jetson:/opt/inference/TensorRT# find /usr/local/lib/python3.8/dist-packages -name *.cmake | grep Torch
/usr/local/lib/python3.8/dist-packages/torch/share/cmake/Torch/TorchConfigVersion.cmake
/usr/local/lib/python3.8/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake
root@jetson:/opt/inference/TensorRT# find /usr/local/lib/python3.8/dist-packages -name *.cmake | grep tensorrt
root@jetson:/opt/inference/TensorRT# 
```

 I noticed that `torchtrtConfig.cmake` is [mentioned in the CMakeLists.txt](https://github.com/pytorch/TensorRT/blob/v1.4.0/CMakeLists.txt#L38), but it doesn't exist anywhere in my installation. Am I supposed to install Torch TensorRT with CMake in order to use the C++ API in a CMake project?
 
## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 2.0
 - CPU Architecture: aarch64
 - OS (e.g., Linux): L4T
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): L4T docker container
 - Build command you used (if compiling from source): Building from source as per instructions via bazel
 - Are you using local sources or building from archives:
 - Python version: 3.8
 - CUDA version: 
 - GPU models and configuration: Jetson Orin NX 16GB
 - Any other relevant information:

**Comment by gcuendet** [comment]
> I noticed that torchtrtConfig.cmake is [mentioned in the CMakeLists.txt](https://github.com/pytorch/TensorRT/blob/v1.4.0/CMakeLists.txt#L38), but it doesn't exist anywhere in my installation. Am I supposed to install Torch TensorRT with CMake in order to use the C++ API in a CMake project?

Yes.

The reason is pretty simple: `find_package(torchtrt)` mechanism in CMake relies on a CMake "finder" (typically findtorchtrt.cmake or as in this case torchtrtConfig.cmake). That "finder" is itself currently only generated by CMake.

**Comment by janblumenkamp** [comment]
Thanks for explaining, that makes sense.
I assume there is currently no way to build for other targets (e.g. Jetson) with CMake? I am currently following the instructions for the Jetson build [as explained here](https://pytorch.org/TensorRT/getting_started/installation.html):

1. Replace the WORKSPACE file with the corresponding WORKSPACE file in //toolchains/jp_workspaces
2. Compile with `bazel build //:libtorchtrt --platforms //toolchains:jetpack_5.0`
3. Install with `python3 setup.py install --use-cxx11-abi`.

Do you see an easy way to compile it similarly with CMake, or is there another way to generate `torchtrtConfig.cmake`? I guess I could try to build both with CMake and bazel, copy the generated `torchtrtConfig.cmake` and hope that it works?

**Comment by gcuendet** [comment]
Regarding building torch-tensorRT with CMake for the Jetson, I am not sure whether or not the Jetson build would work with CMake and if not what would be required to fix it. Maybe try it out and if you manage to make it work, I would guess that the maintainers would be happy to incorporate your changes (?). 

Regarding the generation of `torchtrtConfig.cmake`, there is actually not much super complicated stuff in there... So technically you could even write it by hand and add it to your torchtrt install (usually either in `/lib/cmake/torchtrt` or in `/share/cmake/torchtrt`; see [the full list of default locations searched by CMake](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure)). Practically, you can probably start from the `torchtrtConfig.cmake.in` at the root of the repo.

**Comment by BrettRyland** [comment]
I don't have a `torchtrtConfig.cmake` file, but I'm able to compile and link against `libtorchtrt.so` by setting the following in my `CMakeLists.txt` file:
```cmake
set(WITH_TORCHTRT ON CACHE BOOL "With Torch-TensorRT") # Build with/without Torch-TensorRT support.
message(STATUS "WITH_TORCHTRT: ${WITH_TORCHTRT}")
if (WITH_TORCHTRT)
	# Build Torch-TensorRT with "bazel build //:libtorchtrt -c opt" and install it to /usr/local with "sudo tar -xvzf bazel-bin/libtorchtrt.tar.gz -C /usr/local/"
	add_compile_definitions(WITH_TORCHTRT)
	include_directories("/usr/local/torch_tensorrt/include")
	link_directories("/usr/local/torch_tensorrt/lib")
	set(Torch_TensorRT_LIBS -Wl,--no-as-needed -ltorchtrt -Wl,--as-needed)
endif()

add_executable(<target> ... <sources>)
target_link_libraries(<target> ... ${Torch_TensorRT_LIBS})
```
After building your target, you should be able to check that it was linked against `libtorchtrt.so` with
```bash
$ ldd <target> | grep torchtrt
  libtorchtrt.so => /usr/local/torch_tensorrt/lib/libtorchtrt.so (0x00007f111b200000)

**Comment by janblumenkamp** [comment]
Thanks a lot, this worked for me!
