### ISSUE TITLE
🐛 [Bug] Encountered bug when using Torch-TensorRT

### ISSUE THREAD

**Issue by JosephLYH** [pytorch/TensorRT#2322]
##  Bug Description

The code to compile then save a model doesn't work as intended, the compiled model cannot be saved.

## To Reproduce

1. Directly run the sample code below to get the error

Minimal reproducible sample:

model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet18', pretrained=False).cuda()
model.eval()

trt_ts_module = torch_tensorrt.compile(model, 
    inputs=[torch_tensorrt.Input(
        min_shape=[1, 3, 256, 256],
        opt_shape=[1, 3, 512, 512],
        max_shape=[1, 3, 1024, 1024],
    )],
    enabled_precisions = {torch.half}) # Run with FP16

result = trt_ts_module(torch.ones((1, 3, 512, 512).cuda())) # run inference
torch.jit.save(trt_ts_module, "trt_torchscript_module.ts") # save the TRT embedded Torchscript

Error and stack trace:

>>> torch.jit.save(trt_ts_module, "trt_torchscript_module.ts") # save the TRT embedded Torchscript
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_serialization.py", line 80, in save
    m.save(f, _extra_files=_extra_files)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1640, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GraphModule' object has no attribute 'save'

## Expected behavior

Successfully save the compiled model.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - NGC container of PyTorch version 23.08-py3
 - Torch-TensorRT Version (e.g. 1.0.0): 2.0.0.dev0
 - PyTorch Version (e.g. 1.0): 2.1.0a0+29c30b1
 - CPU Architecture: x64
 - OS (e.g., Linux): Ubuntu 23.04
 - Python version: 3.10.12
 - CUDA version: 12.2
 - GPU models and configuration: 2x RTX 3090

**Comment by nviwch** [comment]
I also encountered this issue

**Comment by gs-olive** [comment]
Hi - thank you for reporting this issue. @peri044 - I believe this relates to the switch to `ir="dynamo"` as the default compilation path. Could you advise on the recommended serialization method/code for this path?

In the meantime, a temporary workaround that should resolve this issue is to specify `ir="ts"` to the `torch_tensorrt.compile` call, which will use the TorchScript backend.

**Comment by peri044** [comment]
@JosephLYH Since we output a `GraphModule` object now, can you try with `torch.jit.trace` on the output model and then try to save it ?

**Comment by JosephLYH** [comment]
I can save the model with torch.jit.save after torch.jit.trace. Thanks for the help.
