### ISSUE TITLE
❓ [Question] How do you build and use PytorchTRT on Windows 10? 

### ISSUE THREAD

**Issue by jensdraht1999** [pytorch/TensorRT#2348]
## ❓ Question

After trying even using MSVC instead of Ninja, I kind was able to generate some dll files. The files are torchtrt.dll, torch_plugins.dll, torchtrt_runtimes.dll, torchtrtc.exe.
Now what do I do with these. I just assumed, I put them in the lib folder  "C:\Users\{Username}\AppData\Local\Programs\Python\Python310\Lib\site-packages\torch\lib" and now this does not work.

## What you have already tried

I have read everything and tried literrally everything and the building process is literaly broken.
https://pytorch.org/TensorRT/getting_started/getting_started_with_windows.html
and then tried a few diffrerent things and somehow was able to this.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (torch-2.0.1+cu118.dist-info):
 - CPU Architecture: Intel x86 10500H
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): Pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.10
 - CUDA version:11.8
 - GPU models and configuration: RTX 3060 Laptop
 - Any other relevant information:

## Additional context

The building and then also using of PytorchRT Tensor is not easy and very problematic and outdated it seems. 

And even if you manage to get it build somehow, you do not know, what to expect. Are those 4 dll files enough or did I miss something? 

What do I do with these dll files? 

Is there a simple example on Windows starting python files, that will run on TensorRT Pytorch like a Hello World Tensort TRT like.

**Comment by jensdraht1999** [comment]
This is a example, that does not work:



import torch
import torch_tensorrt



import torchvision.models as models

model = models.mobilenet_v2(pretrained=True)
script_model = torch.jit.script(model)



spec = {
    "forward": torch_tensorrt.ts.TensorRTCompileSpec(
        **{
            "inputs": [torch_tensorrt.Input([1, 3, 300, 300])],
            "enabled_precisions": {torch.float, torch.half},
            "refit": False,
            "debug": False,
            "device": {
                "device_type": torch_tensorrt.DeviceType.GPU,
                "gpu_id": 0,
                "dla_core": 0,
                "allow_gpu_fallback": True,
            },
            "capability": torch_tensorrt.EngineCapability.default,
            "num_avg_timing_iters": 1,
        }
    )
}


trt_model = torch._C._jit_to_backend("tensorrt", script_model, spec)


input = torch.randn((1, 3, 300, 300)).to("cuda").to(torch.half)
print(trt_model.forward(input))

**Comment by jensdraht1999** [comment]
C:\Users\USERNAME>C:\Users\USERNAME\Desktop\2.py
Traceback (most recent call last):
  File "C:\Users\USERNAME\Desktop\2.py", line 1, in <module>
    import torch
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 1114] Eine DLL-Initialisierungsroutine ist fehlgeschlagen. Error loading "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\torchtrt.dll" or one of its dependencies.

**Comment by jensdraht1999** [comment]
Okay here is the exact steps I have made:
1.) Download:  cudnn-windows-x86_64-8.9.5.29_cuda11-archive.zip
2.) Download: libtorch-win-shared-with-deps-2.0.1+cu118.zip
3.) Download: TensorRT-1.4.0.zip
4.) Download: TensorRT-8.5.3.1.Windows10.x86_64.cuda-11.8.cudnn8.6
5.) Download: Cuda 11.8

6.) Installed Cuda 11.8
7.) Put the Cudnn Files into the Cuda folder.
8.) Extracted: libtorch-win-shared-with-deps-2.0.1+cu118.zip to Libtorch
9.)  Extracted: TensorRT-8.5.3.1.Windows10.x86_64.cuda-11.8.cudnn8.6 to TensorRT-8.5.3.1


10.) Extracted:  TensorRT-1.4.0.zip and opened in Visual Studio 2022 Community.
11.) And then changed JSON Files like this:

`{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Visual Studio 17 2022 Win64",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "-S . -B out",
      "buildCommandArgs": "cmake --build out",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "CMAKE_MODULE_PATH",
          "value": "$PWD\\cmake\\Modules",
          "type": "FILEPATH"
        },
        {
          "name": "Torch_DIR",
          "value": "C:\\Users\\{Username}\\source\\repos\\thirdpartylibs\\libtorch\\share\\cmake\\Torch",
          "type": "FILEPATH"
        },
        {
          "name": "TensorRT_ROOT",
          "value": "C:\\Users\\{Username}\\source\\repos\\thirdpartylibs\\TensorRT-8.5.3.1",
          "type": "FILEPATH"
        },
        {
          "name": "CMAKE_BUILD_TYPE",
          "value": "Release",
          "type": "STRING"
        }
      ]
    }
  ]
}`

12:) After that it gave a error, so I have changed Ninja to  Visual Studio 17 2022 Win64.

13.) It builds successful with "Error: CMake file API response index file not found".

14.) I open the out folder and find a sln file: Torch-TensorRT.sln

15.) It gives a compile error, only 10 of 16 are working, so I add to all subprojects following: _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING      in all subprojects.

16. It compiles without errors and in the folder: "out\bin\Debug" following four files and their pbd files, which are not needed.
17. The files are:  torchtrt.dll, torch_plugins.dll, torchtrt_runtimes.dll, torchtrtc.exe.
18. I put them in my "C:\Users\{Username}\AppData\Local\Programs\Python\Python310\Lib\site-packages\torch\lib".

19. It does not work, it says the dll could not be loaded.


Now what should I do?

**Comment by narendasan** [comment]
The CMake instructions are for the C++ APIs for the torchscript frontend. That should be functional like any other C++ library on windows with the headers. The python API consumes these to build the python package but youd need to modify the setup.py (https://github.com/pytorch/TensorRT/blob/0d402fb9e66e2bc9b94a1426512ba7f5d2179aed/setup.py#L456C1-L456C1) to pull these files in since we dont have full windows support currently to build the python bindings. In H1Y24 we are hoping to be able to decouple the C++ backed parts and the python only parts so it should be possible easily build on windows as well

**Comment by jensdraht1999** [comment]
@narendasan 

Thank you, I try understand it.

Just another question. It says:

**To compile the python package for your local machine, just run python3 setup.py install in the //py directory. To build wheel files for different python versions, first build the Dockerfile in //py then run the following command
docker run -it -v$(pwd)/..:/workspace/Torch-TensorRT build_torch_tensorrt_wheel /bin/bash /workspace/Torch-TensorRT/py/build_whl.sh**


Should I add another file dir path with following location:
C:\Users\{UserName}\source\repos\TensorRT\out\build\x64-Debug\out\bin\Debug

in https://github.com/pytorch/TensorRT/blob/0d402fb9e66e2bc9b94a1426512ba7f5d2179aed/setup.py#L456C1-L456C1
?



Do I need docker and bazel on windows for installation, if I have already compiled the dll files?

**Comment by narendasan** [comment]
> Should I add another file dir path with following location:
C:\Users{UserName}\source\repos\TensorRT\out\build\x64-Debug\out\bin\Debug

Yes something like this should work, you will also need the paths for libtorch from Pytorch and tensorrt etc. 

You dont need docker, thats just to create builds for each version of python on linux. You also wouldnt need bazel if you have the DLLs, you can skip the build_libtorchtrt part and just compiling the extension. All you need is ninja for building the extension

**Comment by jensdraht1999** [comment]
> Yes something like this should work, you will also need the paths for libtorch from Pytorch and tensorrt etc.
> 
> You dont need docker, thats just to create builds for each version of python on linux. You also wouldnt need bazel if you have the DLLs, you can skip the build_libtorchtrt part and just compiling the extension. All you need is ninja for building the extension

Ok thank you for the information. I will go on with the building process and then if something new happens in my way, ask you again. I will close this issue.

Thank you very much!!!
