### ISSUE TITLE
Pytorch-2.1 based release

### ISSUE THREAD

**Issue by bsergean** [pytorch/TensorRT#2412]
**Is your feature request related to a problem? Please describe.**

The current release is built for pytorch-2.0.1.

pytorch 2.1 got released in October. We'd like to be able to use a pre-compiled wheel with pytorch-2.1 ; we are building a C++ project that depends on 2.1.

**Describe the solution you'd like**
Download the a 2.1 base wheel file from the Release page.

**Describe alternatives you've considered**
Using the 2.0.1 wheel.

**Additional context**

**Comment by ar13pit** [comment]
We have the same request. Currently we are using the branch `release/2.1` from source.
