### ISSUE TITLE
ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin Mod version 1

### ISSUE THREAD

**Issue by lin-lcx** [pytorch/TensorRT#2465]
I want to use tensorrt to accelerate VisionEncoderDecoderModel. Use the following code to convert it to onnx and it was successful.
```

from transformers import VisionEncoderDecoderModel
def model_converter():
    model = VisionEncoderDecoderModel.from_pretrained("./examples/data")
    model.to(device)
    model.eval()
    tokenizer = NougatTokenizerFast.from_pretrained(r'./examples/data')
    latex_processor = NougatLaTexProcessor.from_pretrained(r'./examples/data')
    task_prompt = tokenizer.bos_token
    decoder_input_ids = tokenizer(task_prompt, add_special_tokens=False,
                                    return_tensors="pt").input_ids.to(device)
    # Create dummy inputs with the correct shapes for both inputs
    dummy_pixel_values = torch.randn(1, 3, 224, 560, device=device)
    # Provide names for the inputs
    input_names = ['pixel_values', 'decoder_input_ids']
    output_names = ['output']
    # Export the model to ONNX
    torch.onnx.export(
        model,
        (dummy_pixel_values, decoder_input_ids),
        './examples/test2.onnx',
        export_params=True,
        verbose=True,
        input_names=input_names,
        output_names=output_names
    )
```

Then, when changing onnx into trt, an error occurred:

> Loading ONNX file from path ./examples/test.onnx...
Beginning ONNX file parsing
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:604] Reading dangerously large protocol message. If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons. To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 1400793072
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin Mod version 1
ERROR: Failed to parse the ONNX file.
In node -1 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
Completed parsing of ONNX file
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.
Traceback (most recent call last):
File "create_onnx.py", line 350, in <module>
f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'

the code is

```
import os
import tensorrt as trt
 
TRT_LOGGER = trt.Logger()
model_path = './examples/test.onnx'
engine_file_path = "./examples/test.trt"
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)  # batchsize=1
 
with trt.Builder(TRT_LOGGER) as builder, builder.create_network(EXPLICIT_BATCH) \
        as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
    builder.max_workspace_size = 1 << 28
    builder.max_batch_size = 1
    if not os.path.exists(model_path):
        print('ONNX file {} not found.'.format(model_path))
        exit(0)
    print('Loading ONNX file from path {}...'.format(model_path))
    with open(model_path, 'rb') as model:
        print('Beginning ONNX file parsing')
        if not parser.parse(model.read()):
            print('ERROR: Failed to parse the ONNX file.')
            for error in range(parser.num_errors):
                print(parser.get_error(error))

    network.get_input(0).shape = [1, 3, 224, 560]
    network.get_input(1).shape = [1,1]
    print('Completed parsing of ONNX file')
    engine = builder.build_cuda_engine(network)
    with open(engine_file_path, "wb") as f:
        f.write(engine.serialize())

```

> TensorRT-7.2.3.4

**Comment by lin-lcx** [comment]
pretrain model is https://huggingface.co/Norm/nougat-latex-base

**Comment by narendasan** [comment]
This doesnt seem like an issue with Torch-TensorRT but TensorRT itself, we can transfer this issue to that repo if you like

**Comment by lin-lcx** [comment]
Maybe I need to use the latest version of tensorrt, which supports mod operations
