### ISSUE TITLE
❓ [Question] New release of torch-tensorRT with PyTorch 2.1

### ISSUE THREAD

**Issue by agunapal** [pytorch/TensorRT#2468]
## ❓ Question

New release of torch-tensort with PyTorch 2.1

## What you have already tried

Is there going to be a new release? or is this supported now through torch.compile only?

**Comment by narendasan** [comment]
We are currently doing QA on our 2.1 release but you can find release candidates from the pytorch test package index

```
pip install torch-tensorrt==2.1.0 --extra-index-url https://download.pytorch.org/whl/test/cu121```

**Comment by sachanub** [comment]
Which version of `tensorrt` is recommended with `torch-tensorrt==2.1.0`?

**Comment by narendasan** [comment]
8.6

**Comment by tugui** [comment]
2.1.1 now

**Comment by sachanub** [comment]
What is the rough estimate for the official release of torch-tensorrt 2.1? Thanks!

**Comment by vgrytsun** [comment]
any updates on this one?
- is 2.1 going to be released?
- is it safe to use 2.1 RC ?

**Comment by narendasan** [comment]
We skipped 2.1 official release due to some internal alignment on stack, Torch-TRT 2.2 has been released already or if you are dependent on PyTorch 2.1 the RCs are safe to use

**Comment by s-smits** [comment]
> We skipped 2.1 official release due to some internal alignment on stack, Torch-TRT 2.2 has been released already or if you are dependent on PyTorch 2.1 the RCs are safe to use

Is this still the case?
```
The conflict is caused by:
    The user requested torch==2.1.1
    torchvision 0.16.1 depends on torch==2.1.1
    torchaudio 2.1.1 depends on torch==2.1.1
    torch-tensorrt 2.2.0 depends on torch<2.3.0 and >=2.2.0
```

**Comment by narendasan** [comment]
You would use the 2.1 rc's https://download.pytorch.org/whl/test/torch-tensorrt/, they should maintain support for 2.1.0
