### ISSUE TITLE
`aten.sym_size.int`

### ISSUE THREAD

**Issue by narendasan** [pytorch/TensorRT#2496]
Implement torch.ops.aten.sym_size.int converter. This is equivalent to IShapeLayer in Tensorrt. This is required for dynamic shapes + fallback feature in the standard vision models like Resnet, Mobilenet etc where a view layer is used before the final dimensions to reshape it to [-1, X] etc.

**Comment by peri044** [comment]
PR: https://github.com/pytorch/TensorRT/pull/2473
