### ISSUE TITLE
❓ [Question] Support for layers with Custom C++ and CUDA Extensions

### ISSUE THREAD

**Issue by Siyeong-Lee** [pytorch/TensorRT#2579]
## ❓ Question
Support for layers with Custom C++ and CUDA Extensions

## What you have already tried
Can I convert the LLTM class in directory `cuda` of https://github.com/pytorch/extension-cpp (below) into a tensorrt engine through Torch-TensorRT?

I tried the code below:
```lltm.py
import math
from torch import nn
from torch.autograd import Function
import torch

import lltm_cuda

torch.manual_seed(42)

class LLTMFunction(Function):
    @staticmethod
    def forward(ctx, input, weights, bias, old_h, old_cell):
        outputs = lltm_cuda.forward(input, weights, bias, old_h, old_cell)
        new_h, new_cell = outputs[:2]
        variables = outputs[1:] + [weights]
        ctx.save_for_backward(*variables)

        return new_h, new_cell

    @staticmethod
    def backward(ctx, grad_h, grad_cell):
        outputs = lltm_cuda.backward(
            grad_h.contiguous(), grad_cell.contiguous(), *ctx.saved_variables)
        d_old_h, d_input, d_weights, d_bias, d_old_cell, d_gates = outputs
        return d_input, d_weights, d_bias, d_old_h, d_old_cell


class LLTM(nn.Module):
    def __init__(self, input_features, state_size):
        super(LLTM, self).__init__()
        self.input_features = input_features
        self.state_size = state_size
        self.weights = nn.Parameter(
            torch.Tensor(3 * state_size, input_features + state_size))
        self.bias = nn.Parameter(torch.Tensor(1, 3 * state_size))
        self.reset_parameters()

    def reset_parameters(self):
        stdv = 1.0 / math.sqrt(self.state_size)
        for weight in self.parameters():
            weight.data.uniform_(-stdv, +stdv)

    def forward(self, input, state):
        return LLTMFunction.apply(input, self.weights, self.bias, *state)

import torch_tensorrt

model = LLTM(64, 32).cuda()
print(
    model(
        torch.randn(2, 64).cuda(),
        torch.randn(2, 32).cuda(),
        torch.randn(2, 32).cuda(),
    )
)


traced_model = torch.jit.trace(
    model,
    [
        torch.randn(2, 64).cuda(),
        torch.randn(2, 32).cuda(),
        torch.randn(2, 32).cuda(),
    ],
)

import torch_tensorrt

trt_model = torch_tensorrt.compile(
    traced_model,
    inputs=[
        torch_tensorrt.Input((2, 64), dtype=torch.float32),
        torch_tensorrt.Input((2, 32), dtype=torch.float32),
        torch_tensorrt.Input((2, 32), dtype=torch.float32),
    ],
    enabled_precisions={torch.float32},
)
```
output:
```
[1]    895656 segmentation fault (core dumped)  python lltm.py
````

I read the relevant materials, but I have no idea how to proceed at all.

**Comment by narendasan** [comment]
Are you looking to have tensorrt implement your custom function or are you looking to have your custom kernel embedded in the tensorrt engine? 

For either, first you will need to formalize your module into an op in PyTorch. This will give torch-tensorrt something to catch. For example: https://github.com/pytorch/TensorRT/blob/3c65d4fc570020b4871746140cc08073bb764bce/py/torch_tensorrt/dynamo/lowering/substitutions/maxpool1d.py#L23

Then you will need a converter to translate this op into TensorRT: 
https://github.com/pytorch/TensorRT/blob/3c65d4fc570020b4871746140cc08073bb764bce/py/torch_tensorrt/dynamo/lowering/substitutions/maxpool1d.py#L97

The implementation of the converter for TensorRT will vary based on if you want to use your kernel directly in which case you will need to write a plugin: https://github.com/NVIDIA/TensorRT/tree/main/samples/python/onnx_custom_plugin, which you will insert in to the engine with your converter - ex: https://github.com/pytorch/TensorRT/blob/fd76e0f3d1fa677b34ea45710354b0154194c73c/py/torch_tensorrt/fx/converters/acc_ops_converters.py#L3310. 

Or if you want to implement your op with TensorRT, there is a library of low level tensor operations you can use to compose your function natively: https://github.com/pytorch/TensorRT/tree/fd76e0f3d1fa677b34ea45710354b0154194c73c/py/torch_tensorrt/dynamo/conversion/impl

**Comment by Siyeong-Lee** [comment]
@narendasan Thank you!
