### ISSUE TITLE
🐛 [Bug] Cannot compile with FP16, "RuntimeError: Expected bias to have type Half but got Float" 

### ISSUE THREAD

**Issue by SM1991CODES** [pytorch/TensorRT#2587]
##  Bug Description

I am trying to compile a very simple network with Torch-Tensorrt with FP16.
I get the following error message:
![image](https://github.com/pytorch/TensorRT/assets/69435296/645627f3-5538-4c22-9459-8da1bebfbb62)

## To Reproduce

1. Here is the code I use to compile
`# 1. trace to create torchscript
        traced_model = torch.jit.trace(net, torch.empty([512, 2, 16]).to("cuda"))
        print(traced_model)

        script_model = torch.jit.script(net)
        print(script_model)
        torch.jit.save(script_model, "script_model.ts")
        
        trt_script_module = torch_tensorrt.compile(script_model, 
                                                   inputs = [torch_tensorrt.Input(min_shape=[512, 2, 16],
                                                                                  opt_shape=[512, 2, 16],
                                                                                  max_shape=[512, 2, 16], dtype=torch.half)], 
                                                                                  enabled_precisions={torch.half})

        input_data = torch.randn((512, 2, 16))
        input_data = input_data.half().to("cuda")

        # input_data = input_data.half()
        result = trt_script_module(input_data)
        torch.jit.save(trt_script_module, "trt_script_module.ts")`

3. A scripted model is attached
[script_model.zip](https://github.com/pytorch/TensorRT/files/13886490/script_model.zip)

5.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.3.0a0
 - PyTorch Version (e.g. 1.0): 1.13.0a0+d0d6b1f
 - CPU Architecture: x86-64
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): NGC docker image **nvcr.io/nvidia/pytorch:22.10-py3**
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.8.13
 - CUDA version:
 - GPU models and configuration: RTX2080 MaxQ
 - Any other relevant information:

**Comment by apbose** [comment]
Hi, could you please provide the source code of the traced model above?

**Comment by apbose** [comment]
The issue was that you need to convert the model to fp16 after loading it. Specifying the enabled_precisions= {torch.half} would not be enough since it would direct TensorRT to choose the enabled precision kernels for compilation.
The following works:
 
 ```
**script_model.half().eval().cuda()**
 trt_script_module = torch_tensorrt.compile(script_model, 
                                            inputs = [torch_tensorrt.Input(min_shape=[512, 2, 16],
                                                                           opt_shape=[512, 2, 16],
                                                                           max_shape=[512, 2, 16], dtype=torch.half)], 
                                                                           enabled_precisions={torch.half})

 input_data = torch.randn((512, 2, 16))
 input_data = input_data.half().to("cuda")

 # input_data = input_data.half()
 result = trt_script_module(input_data)
 torch.jit.save(trt_script_module, "trt_script_module.ts")`

```
