### ISSUE TITLE
[OPs to be supported]

### ISSUE THREAD

**Issue by zhangshaojie1993** [pytorch/TensorRT#2659]
![image](https://github.com/pytorch/TensorRT/assets/58938020/86b22080-6dde-492a-a1e8-cda139766b47)
When the three ops above can be supported? Very hope about that!
The three ops is related to torch.gather,  torch.nn.functional.unfold etc

**Comment by narendasan** [comment]
@zhangshaojie1993 Can you try using the dynamo frontend and see if you get these ops supported there?
