### ISSUE TITLE
How to convert model from double to float

### ISSUE THREAD

**Issue by inocsin** [pytorch/TensorRT#266]
When I try to complie torchscript model, I get this log
```
DEBUG: [TRTorch Conversion Context] - Found IValue containing object of type Double(requires_grad=0, device=cpu)
terminate called after throwing an instance of 'trtorch::Error'
  what():  [enforce fail at core/util/trt_util.cpp:293] Expected aten_trt_type_map.find(t) != aten_trt_type_map.end() to be true but got false
Unsupported Aten datatype
```

So I try to convert model to float using this
```
script_model = torch.jit.load(path)
script_model = script_model.eval()
script_model = script_model.float()
script_model.save(new_path)
```
And it still throw this error

**Comment by narendasan** [comment]
can you provide more of the log / the graph?

**Comment by inocsin** [comment]
> can you provide more of the log / the graph?
Log file is here
[double.log](https://github.com/NVIDIA/TRTorch/files/5779241/double.log)

**Comment by peri044** [comment]
This error is from [aten_to_trt_type mapping](https://github.com/NVIDIA/TRTorch/blob/master/core/util/trt_util.cpp#L226). The pytorch tensor in your graph has a double datatype and TRT doesn't support beyond float datatype. 
My guess: 
Looking at your log, it looks like the second input to the mul node is a double node.
```
%523 : Tensor = aten::mul(%x5.1, %22)
```
```
Adding Layer %523 : Tensor = aten::mul(%x5.1, %22) # /data00/home/roy.he/projects/super_res/infere/models/modules/RRDBNet_arch.py:28:0 (ctx.AddLayer)
[1;35mDEBUG: [0m[TRTorch Conversion Context] - Node input is an already converted tensor
[1;35mDEBUG: [0m[TRTorch Conversion Context] - Node input is a result of a previously evaluated value
[1;35mDEBUG: [0mFrozen tensor shape: [1, 64, 1000, 1000]
[1;35mDEBUG: [0m[TRTorch Conversion Context] - Found IValue containing object of type Double(requires_grad=0, device=cpu)
terminate called after throwing an instance of 'trtorch::Error'
  what():  [enforce fail at core/util/trt_util.cpp:293] Expected aten_trt_type_map.find(t) != aten_trt_type_map.end() to be true but got false
Unsupported Aten datatype
```
Maybe this %22 is a double value which might be causing the problem. If you have the  source code, can you force this constant to be float, regenerate the torchscript  and try ? 
There are other similar constants in your model as follows which are represented as explicit float constants unlike %22 tensor
```
 %13 : float = prim::Constant[value=0.20000000000000001]()
```

**Comment by inocsin** [comment]
> This error is from [aten_to_trt_type mapping](https://github.com/NVIDIA/TRTorch/blob/master/core/util/trt_util.cpp#L226). The pytorch tensor in your graph has a double datatype and TRT doesn't support beyond float datatype.
> My guess:
> Looking at your log, it looks like the second input to the mul node is a double node.
> 
> ```
> %22 : Tensor = prim::Constant[value={0.2}]()
> %523 : Tensor = aten::mul(%x5.1, %22)
> ```
> 
> ```
> Adding Layer %523 : Tensor = aten::mul(%x5.1, %22) # /data00/home/roy.he/projects/super_res/infere/models/modules/RRDBNet_arch.py:28:0 (ctx.AddLayer)
> �[1;35mDEBUG: �[0m[TRTorch Conversion Context] - Node input is an already converted tensor
> �[1;35mDEBUG: �[0m[TRTorch Conversion Context] - Node input is a result of a previously evaluated value
> �[1;35mDEBUG: �[0mFrozen tensor shape: [1, 64, 1000, 1000]
> �[1;35mDEBUG: �[0m[TRTorch Conversion Context] - Found IValue containing object of type Double(requires_grad=0, device=cpu)
> terminate called after throwing an instance of 'trtorch::Error'
>   what():  [enforce fail at core/util/trt_util.cpp:293] Expected aten_trt_type_map.find(t) != aten_trt_type_map.end() to be true but got false
> Unsupported Aten datatype
> ```
> 
> Maybe this %22 is a double value which might be causing the problem. If you have the source code, can you force this constant to be float, regenerate the torchscript and try ?
> There are other similar constants in your model as follows which are represented as explicit float constants unlike %22 tensor
> 
> ```
>  %13 : float = prim::Constant[value=0.20000000000000001]()
> ```

Yes, I tried to print the constant value in the script model using
```
script_model = torch.jit.load(path)
script_model.eval()
script_model.float()
print(script_model.forward.code_with_constants[1])
```
the output is
```
{'c0': tensor(0.2000, dtype=torch.float64), 'c1': tensor(2.)}
```

I also try to modify the costant value by
```
script_model.code_with_constants[1].c0 = script_model.code_with_constants[1].c0.float()
```
but it didn't change the type. So the only way is to modify the orignal python module definition? There this nothing can do to modify the constant type throuhg torchscript?

**Comment by halakoter** [comment]
> can you provide more of the log / the graph?

Can anyone tell me how to get the above log as @inocsin?

**Comment by peri044** [comment]
@inocsin Can you try with torch.fx https://pytorch.org/docs/stable/fx.html#direct-graph-manipulation ? 
I'm not sure if that would work but we can basically modify layers/add new layers etc. Hopefully we can modify these constant layers to the desired precision ?

**Comment by apivovarov** [comment]
Related issues:

**Comment by narendasan** [comment]
@apivovarov Using the following script I am able to run InceptionV3. Please open a new issue if there are still problems, I think the original issue from Jan 2021 has been addressed with `truncate_long_and_double`

```py
import torch
import torchvision
import torch_tensorrt as torchtrt

model = torch.hub.load('pytorch/vision:v0.13.0', 'inception_v3', pretrained=True)
model = torch.jit.script(model)
model.eval().cuda()


torchtrt.logging.set_reportable_log_level(torchtrt.logging.Level.Graph)

mod = torchtrt.ts.compile(
    model,
    inputs=[torchtrt.Input((1, 3, 300, 300))],
    truncate_long_and_double=True,
    torch_executed_ops=[
        "prim::TupleConstruct",
    ]
)

x = torch.randn((1, 3, 300, 300)).cuda()

print(mod(x))
```

**Comment by apivovarov** [comment]
Thank you! Can you double check that it works with shape `(1,3,299,299)` - which is inception_v3 input shape https://pytorch.org/hub/pytorch_vision_inception_v3/

**Comment by narendasan** [comment]
yes this input size works as well.
