### ISSUE TITLE
🐛 [Bug] Unable to import torch_tensorrt on Jetson Orin AGX Dev. Kit

### ISSUE THREAD

**Issue by bionictoucan** [pytorch/TensorRT#2700]
##  Bug Description

Trying to import `torch_tensorrt` on Jetson fails with odd import error after installation from .whl compiled on the same machine.

## To Reproduce

1. Start python
2. `import torch_tensorrt`

![IMG_0285](https://github.com/pytorch/TensorRT/assets/33138337/19fa3456-0b0f-42cb-8df5-0793bb2cba42)

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.4.0
 - TensorRT Version: 8.5.2.2
 - PyTorch Version (e.g. 1.0): 2.0.0
 - CPU Architecture: aarch64
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives: yes
 - Python version: 3.8
 - CUDA version: 11.4
 - GPU models and configuration: Jetson AGX Orin Dev. Kit
 - Any other relevant information: JetPack 5.1.2

## Additional context

I understand the current recommendation is to use v1.0.0 for Jetsons but this limits the what version of PyTorch can be used and I’d like to use features introduced in PyTorch 2.0.

**Comment by narendasan** [comment]
This is usually due to a version mismatch between the libtorch version used for compilation and the installed version of pytorch

**Comment by bionictoucan** [comment]
That's interesting, I got the PyTorch wheel [from NVIDIA directly](https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048), however I just noticed their 2.0.0 wheel is for JetPack 5.1 and 5.1.1 (not 5.1.2). I'll try building PyTorch from source in 5.1.2 to see if there's a difference between 5.1.1 and 5.1.2

**Comment by bionictoucan** [comment]
**UPDATE**: I managed to get this working by removing the `install_requires` in `setup.py`. Having the `install_requires` consistently replaces the PyTorch used to build `torch_tensorrt` with the `aarch64` wheel from pip which seems to have been causing the clash.
