### ISSUE TITLE
🐛 [Bug] scaled_dot_product_attention test in Torchscript failure

### ISSUE THREAD

**Issue by peri044** [pytorch/TensorRT#2716]
##  Bug Description

//tests/core/conversion/converters:test_scaled_dot_product_attention 
(C++ exception with description "0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":615, please report a bug to PyTorch. We don't have an op for aten::scaled_dot_product_attention but it isn't a special case.  Argument types: Tensor, Tensor, Tensor, Tensor, float, bool, )

## To Reproduce

1.
2.
3.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):
 - PyTorch Version (e.g. 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by mfeliz-cruise** [comment]
Probably a PyTorch version mismatch. I think the interface of scaled_dot_product_attention may have changed to add the %scale in 2.2.
