### ISSUE TITLE
❓ [Question] Can TensorRT load and run torch_tensorrt models directly? 

### ISSUE THREAD

**Issue by theNefelibata** [pytorch/TensorRT#2718]
Can TensorRT load and run torch_tensorrt models directly? I want to export my pytorch model and deploy it with TensorRT.

**Comment by narendasan** [comment]
Use the convert_x_to_engine APIs. They will produce a serialized engine that you can use directly with TRT. However they do not support hybrid execution with PyTorch so all ops must be supported in Torch-TensorRT at compile time

**Comment by theNefelibata** [comment]
> Use the convert_x_to_engine APIs. They will produce a serialized engine that you can use directly with TRT. However they do not support hybrid execution with PyTorch so all ops must be supported in Torch-TensorRT at compile time

where to find this API, Is there any documents?

**Comment by narendasan** [comment]
https://pytorch.org/TensorRT/py_api/torch_tensorrt.html?highlight=engine#torch_tensorrt.convert_method_to_trt_engine
