### ISSUE TITLE
❓ [Question] How should the CMakeLists look like for running .ts files in C++? 

### ISSUE THREAD

**Issue by DmytroIvakhnenkov** [pytorch/TensorRT#2759]
## ❓ Question

I am trying to load a .ts model in C++ on Jetson Orin NX. I am running on this container [https://github.com/dusty-nv/jetson-containers/tree/master/packages/pytorch/torch_tensorrt](), version:[r35.3.1].
```#include <torch/script.h> // One-stop header.
  #include <torch_tensorrt/torch_tensorrt.h>
  
  #include <iostream>
  #include <memory>
  
  int main(int argc, const char* argv[]) {
      torch::jit::Module module;
      try {
          // Deserialize the ScriptModule from a file using torch::jit::load().
          module = torch::jit::load("classificator_float.ts");
      }
      catch (const c10::Error& e) {
          std::cerr << "error loading the model\n";
          return -1;
      }
      std::cout << "ok\n";
  }
  ```
  However, I am struggling to make CMakeLists.txt which would properly include the tensorrt runtime. This is what I currently have:
  
  ```
  cmake_minimum_required(VERSION 3.12 FATAL_ERROR)
project(custom_ops)


execute_process(
    COMMAND python3 -c "import torch; print(torch.utils.cmake_prefix_path)"
    OUTPUT_VARIABLE PYTORCH_CMAKE_PREFIX_PATH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(CMAKE_PREFIX_PATH "${PYTORCH_CMAKE_PREFIX_PATH}")

find_package(Torch REQUIRED)

add_executable(example-app example-app.cpp)
target_include_directories(example-app PRIVATE "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/include")
target_link_libraries(example-app torch)

set_property(TARGET example-app PROPERTY CXX_STANDARD 17)
```
 
It builds without issues, however when I try to execute it I get:
![image](https://github.com/pytorch/TensorRT/assets/25930120/cce8809e-49b8-4b8d-9c96-1ec81a7daf15)

How should I modify CMakeLists.txt?

## What you have already tried

I have looked at these tutorials, but they do not have CMakeLists for running models compiled with TensorRT:

https://pytorch.org/tutorials/advanced/cpp_export.html
https://pytorch.org/TensorRT/getting_started/getting_started_with_cpp_api.html

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 2.0.0+nv23.5
 - TensorRT: 8.5.2.2-1
 - CPU Architecture: arm64
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): jetson-container
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.8.10
 - CUDA version: 11.4
 - GPU models and configuration: Jetson Orin NX

**Comment by narendasan** [comment]
You will also need to link `libtorchtrt.so` or `libtorchtrt_runtime.so`. Note that since there is no direct code dependency for this library, it must be linked with `-Wl,--no-as-neeed` so that it wont get optimized out by the compiler. More details can be found her:; https://pytorch.org/TensorRT/user_guide/runtime.html

**Comment by DmytroIvakhnenkov** [comment]
Thank you so much!
Adding this line did fix the problem :)

`target_link_libraries(example-app -Wl,--no-as-needed "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/lib/libtorchtrt.so")`
