### ISSUE TITLE
🐛 [Bug] DataLoaderCalibrator cache check

### ISSUE THREAD

**Issue by lebionick** [pytorch/TensorRT#2960]
Invalid check, so if cache_file is not None and use_cache is True it will raise an Exception.
https://github.com/pytorch/TensorRT/blob/main/py/torch_tensorrt/ts/ptq.py#L112

**Comment by peri044** [comment]
Thanks for catching this. https://github.com/pytorch/TensorRT/pull/2965 should resolve it.
