### ISSUE TITLE
❓  Cannot figure out the following error: AttributeError: module 'torch_tensorrt' has no attribute 'ptq'.

### ISSUE THREAD

**Issue by ImaanIbrar** [pytorch/TensorRT#3073]
## ❓ Question
I am encountering an AttributeError when trying to use the ptq module from Torch-TensorRT on google colab.
 I am attempting to run this line of code
calibrator = torch_tensorrt.ptq.DataLoaderCalibrator(...) 

## Environment
 - PyTorch Version (e.g., 1.0): 2.4.0+cu121
 - CUDA Version: 12.2
 -  Python version : 3.10.12
 -  torch_tensorrt version : 2.4.0

**Comment by narendasan** [comment]
It was moved to torch_tensorrt.ts.ptq since dynamo doesnt use this system. If you can point the location you are looking at in the docs we can correct it

**Comment by ImaanIbrar** [comment]
I tried that too, but I still get the same issue **AttributeError: module 'torch_tensorrt.ts' has no attribute 'ptq'**
perhaps an version mismatch?

I am referring to this guide:
The last section of the documentation "How to create your own PTQ application in Python" https://pytorch.org/TensorRT/user_guide/ptq.html.
