### ISSUE TITLE
🐛 [Bug] TS test_runtime_thread_safety failed

### ISSUE THREAD

**Issue by zewenli98** [pytorch/TensorRT#3082]
##  Bug Description

In TRT 10.3 upgrade, TorchScript `tests/cpp/test_runtime_thread_safety.cpp` failed due to the error:

[  FAILED  ] CppAPITests.RuntimeThreadSafety
[Torch-TensorRT - Debug Build] -
[Torch-TensorRT - Debug Build] - Cosine Similarity score: 1.000000
[Torch-TensorRT - Debug Build] - Acceptable Threshold: 0.990000
[Torch-TensorRT - Debug Build] -
[Torch-TensorRT - Debug Build] - Cosine Similarity score: 1.000000
[Torch-TensorRT - Debug Build] - Acceptable Threshold: 0.990000
[Torch-TensorRT - Debug Build] -
[Torch-TensorRT - Debug Build] - Cosine Similarity score: -0.017096
[Torch-TensorRT - Debug Build] - Acceptable Threshold: 0.990000
[Torch-TensorRT - Debug Build] -
[Torch-TensorRT - Debug Build] - Cosine Similarity score: 1.000000
[Torch-TensorRT - Debug Build] - Acceptable Threshold: 0.990000
[Torch-TensorRT - Debug Build] -
[Torch-TensorRT - Debug Build] - Cosine Similarity score: -0.010219
[Torch-TensorRT - Debug Build] - Acceptable Threshold: 0.990000
[Torch-TensorRT - Debug Build] -
[Torch-TensorRT - Debug Build] - Cosine Similarity score: 1.000000
[Torch-TensorRT - Debug Build] - Acceptable Threshold: 0.990000
[Torch-TensorRT - Debug Build] -
[Torch-TensorRT - Debug Build] - Cosine Similarity score: 1.000000
[Torch-TensorRT - Debug Build] - Acceptable Threshold: 0.990000
[Torch-TensorRT - Debug Build] -
[Torch-TensorRT - Debug Build] - Cosine Similarity score: 1.000000
[Torch-TensorRT - Debug Build] - Acceptable Threshold: 0.990000
[Torch-TensorRT - Debug Build] -
[Torch-TensorRT - Debug Build] - Cosine Similarity score: 1.000000
[Torch-TensorRT - Debug Build] - Acceptable Threshold: 0.990000
[Torch-TensorRT - Debug Build] -
[Torch-TensorRT - Debug Build] - Cosine Similarity score: 1.000000
[Torch-TensorRT - Debug Build] - Acceptable Threshold: 0.990000
tests/cpp/test_runtime_thread_safety.cpp:84: Failure
Value of: flag
  Actual: false
Expected: true

## To Reproduce
```
bazel test //tests/cpp:test_runtime_thread_safety --compilation_mode=dbg --test_output=all --test_timeout=8000 --jobs 4 --config=pre_cxx11_abi --cxxopt='-std=c++17'
```

**Comment by narendasan** [comment]
@zewenli98 can you rebase on main and test again? There were some fixes for the runtime recently

**Comment by zewenli98** [comment]
Thanks. I confirm this bug was fixed.
