### ISSUE TITLE
❓ [Question] JetPack 6.0

### ISSUE THREAD

**Issue by patrick-botco** [pytorch/TensorRT#3115]
## ❓ Question

i'd like to use torch_tensorrt w/ JetPack 6.0, but from `setup.py`, it seems like latest supported version is JetPack 5.0 https://github.com/pytorch/TensorRT/blob/main/setup.py#L147-L164

## What you have already tried
1. added JetPack 6.0 to setup.py, setting `JETPACK_VERSION` to 6.0.
2. downloaded bazelisk, manually added to PATH 
3. ran setup.py:
```bash
python setup.py bdist_wheel --jetpack-version 6.0 --use-cxx11-abi
```
4. tried creating a new WORKSPACE under `toolchains/jp_workspaces/WORKSPACE.jp60`, effectively copying and pasting `jp50` - but changing `libtorch` to be from Python 3.10. ran `bazel clean --expunge`, eventually ending with `ValueError: Can't find the directory of package torch_tensorrt: I looked in ./src/torch_tensorrt and ./torch_tensorrt`

potentially missing something obvious here. thank you!

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 2.4
 - CPU Architecture: ARM64
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): conda env, pip install
 - Build command you used (if compiling from source): setup.py w/ Bazel (through Bazelisk)
 - Are you using local sources or building from archives:
 - Python version: 3.10
 - CUDA version: 12.2
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @narendasan @zewenli98 (seeing a lot of your commits around setup.py and jp50 :))

**Comment by narendasan** [comment]
Jetpack 6.0 isnt supported well right now since Jetpack is still on TensorRT 8.6 and theres a lot of changes to 10.x. Id recommend using Torch-TensorRT v2.2.0's release branch, that on its own might clean up some issues you are hitting. You can also try using the build of Torch-TensorRT from inside the PyTorch iGPU NGC container and avoid needing to compile: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags (24.07-py3-igpu)

**Comment by patrick-botco** [comment]
thanks for the reply @narendasan 

if i build torch_tensorrt 2.2 id have to downgrade torch to 2.2 as well, correct (im currently using python 3.10 with pytorch 2.4)? is there backwards compatibility with 10.x?

**Comment by patrick-botco** [comment]
just to close this out; with some manual work, I was able to build HEAD of main natively on ARM64 and install it w/o any containers (JetPack 6.0, Python 3.10, PyTorch 2.4)
