### ISSUE TITLE
❓ [Question] When should I use Torch-TensorRT instead of TensorRT ?

### ISSUE THREAD

**Issue by EmmaThompson123** [pytorch/TensorRT#3192]
I generally use NVIDIA's TensorRT as the inference framework. I want to know the advantages and disadvantages of Torch-TensorRT compared to TensorRT, so that I can decide when to use Torch-TensorRT. I guess Torch-TensorRT might be simpler and more user-friendly. Also, have you tested and compared their inference speed and GPU memory usage amont?

**Comment by narendasan** [comment]
Some of the reasons to use Torch-TensorRT are:
1. You use PyTorch and want a PyTorch-like inference API
2. You want to avoid using 3rd party intermediate formats like ONNX
3. You want to use TensorRT for the majority of the network but one or two layers are not supported natively by TensorRT, Torch-TensorRT lets you run those in PyTorch  
4. You want to use advanced features like model refitting, quantization etc. in a more user-friendly way. 

The inference speed and GPU memory usage is near identical in most cases where the network is supported by both systems. In cases where torch-tensorrt is slower, that is considered a bug by us.
