### ISSUE TITLE
Can't build 2.5.0 with Jetpack 6.1 / CUDA 12.6; documentation is incorrect.

### ISSUE THREAD

**Issue by JC3** [pytorch/TensorRT#3278]
The documentation at https://pytorch.org/TensorRT/getting_started/jetpack.html states (at the bottom):

> Please make sure to build torch_tensorrt wheel file from source release/2.5 branch

However, the file _toolchains/jp_workspaces/MODULE.bazel.tmpl_ doesn't exist in this branch, and so the subsequent instructions for generating a _MODULE.bazel_ file are invalid. Also the default _MODULE.bazel_ in this branch does not work for this build. The documentation is not correct, and the provided workflow cannot be used to build TensorRT.

How do I build TensorRT 2.5.0 on a Jetson (ARM64, Jetpack 6.1 CUDA 12.6 PyTorch 2.5.0)?

Can't use 2.6.0 because there's no Jetson build of PyTorch 2.6.0, only 2.5.0.

**Comment by lanluo-nvidia** [comment]
@JC3 
Here is the  jetPack6.1 build PR: https://github.com/pytorch/TensorRT/pull/3211/files
Which has been merged to main only, what you can do is cherry pick the commits in this PR to release/2.5 branch.

**Comment by lanluo-nvidia** [comment]
meanwhile I will also cherry pick this into release/2.5 branch

**Comment by JC3** [comment]
@lanluo-nvidia Thanks for this. I was also able to get it to build after hacking on setup.py and MODULE.bazel for a bit, was about to report back here.

But that PR is very useful, thank you.

**Comment by lanluo-nvidia** [comment]
@JC3  just to let you know the PR has been cherry picked into release/2.5
https://github.com/pytorch/TensorRT/pull/3285

**Comment by lanluo-nvidia** [comment]
close it.
