### ISSUE TITLE
✨[Feature] Is there a plan to support more recent PTQ methods for INT8 ViT?

### ISSUE THREAD

**Issue by dedoogong** [pytorch/TensorRT#3316]
**Is your feature request related to a problem? Please describe.**

there is only traditional max, entropy calibrator but there are already so many PTQs like Adaround, Qdrop, FQ-ViT for int8 ViT PTQ.
wiil TRT support more recent PTQs for int8 ViT in future?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by narendasan** [comment]
This would be a question for [nvidia/tensorrt-model-optimizier ](https://github.com/NVIDIA/TensorRT-Model-Optimizer). We accept the quantization products of that tool. Not sure what their roadmap for these are.
