### ISSUE TITLE
🐛 [Bug] aten::add does not convert with dynamic batch

### ISSUE THREAD

**Issue by narendasan** [pytorch/TensorRT#365]
##  Bug Description

When using dynamic batch, `aten::add` dimension checks fail reporting: 

```
ERROR: [TRTorch Conversion Context] - %457 : Tensor = aten::add_(%456, %455, %3): broadcast dimensions must be non-negative
ERROR: [TRTorch Conversion Context] - Builder failed while analyzing shapes.
```
 

## To Reproduce

1. Run trtorchc on ResNet50 with dynamic batch size
1. `trtorchc tests/modules/resnet50_scripted.jit.pt /out/file.trt "[(1,3,224,224);(3,3,224,224);(5,3,224,224)]" -v`

## Expected behavior

Model converts properly 

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.7.1
 - CPU Architecture: x86
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): source [00f2d78b2768c7f65bffcff6ba0aa287838b2ca0]
 - Are you using local sources or building from archives: archives
 - Python version: python 3.6
 - CUDA version: 11.0
 - GPU models and configuration: TITAN V
 - Any other relevant information:

## Additional context

[log.txt](https://github.com/NVIDIA/TRTorch/files/6032297/log.txt)

**Comment by narendasan** [comment]
cc: @apbose

**Comment by narendasan** [comment]
@apbose any updates on this issue?

**Comment by apbose** [comment]
Hi @narendasan I tested this locally and the test passes now.

**Comment by narendasan** [comment]
Do we have a dynamic batch aten::add test?

**Comment by ncomly-nvidia** [comment]
bump @apbose to Naren's question

**Comment by apbose** [comment]
I am not sure exactly, but should not these test cases be included in the test_dynamic_fallback.cpp in the TensorRT/tests/cpp tests?

**Comment by peri044** [comment]
test_dynamic_fallback has testcases where the model has dynamic shapes and ops that fallback. 
This issue is quite old and is related to dynamic shape aten::add not being converted properly. There are dynamic batch test cases for aten::add now. https://github.com/pytorch/TensorRT/blob/master/tests/core/conversion/converters/test_element_wise.cpp#L69-L70 
We probably don't have an end-end dynamic batch model (full_compilation=True) testcase.

**Comment by Christina-Young-NVIDIA** [comment]
This now working, it just needs to be tested.

**Comment by apbose** [comment]
Closing the issue as it has been tested.
