### ISSUE TITLE
❓ [Question] Does TRTorch supports Ellipsis and None in Tensor.__getitem__? Any workaround?

### ISSUE THREAD

**Issue by ompugao** [pytorch/TensorRT#524]
## ❓ Question

I would like to skip the first batch dimension when I extract data.
While [torch2trt seems support this operation](https://github.com/NVIDIA-AI-IOT/torch2trt/blob/41d7f7aec47f4f840b167c25d1c69337cc0ff303/torch2trt/converters/getitem.py#L39), TRTorch seems not?
Any workaround?

## What you have already tried
Here is an example I would like to do.
```.py
import torch
import trtorch

class MyModule(torch.nn.Module):

    def __init__(self, ):
        super(MyModule, self).__init__()
        self.fc1 = torch.nn.Linear(10, 10)

    def forward(self, x, y):
        x = self.fc1(x)
        z = x[:, y > 0.5]
        return z


model = MyModule()
batchsize = 100
x = torch.randn((batchsize, 10))
y = torch.randn(10)

tracedmodel = torch.jit.trace(model, (x, y))
compile_settings = {
    "input_shapes": [
        [batchsize, 10],
        [10]
    ],
    "op_precision": torch.half, # Run with FP16
    "debug": True,
}
compiledmodel = trtorch.compile(tracedmodel, compile_settings)
```

```
Traceback (most recent call last):
  File "trtorch_indexing.py", line 30, in <module>
    compiledmodel = trtorch.compile(tracedmodel, compile_settings)
  File "/usr/local/lib/python3.6/dist-packages/trtorch/_compiler.py", line 73, in compile
    compiled_cpp_mod = trtorch._C.compile_graph(module._c, _parse_compile_spec(compile_spec))
RuntimeError: [enforce fail at ./core/conversion/var/Var_inl.h:37] Expected ivalue->isTensor() to be true but got false
Requested unwrapping of arg IValue assuming it was N2at6TensorE however type is None
```

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version: 1.8.1
 - CPU Architecture: AMD Ryzen 9 4900HS with Radeon Graphics
 - OS: Ubuntu 18.04
 - How you installed PyTorch: pip
 - Build command you used: --
 - Are you using local sources or building from archives: No
 - Python version: 3.6.9
 - CUDA version: 11.1.1
 - GPU models and configuration: GeForce RTX 2060
 - Any other relevant information:

**Comment by narendasan** [comment]
Theres two things going on here. 1. We dont currently support aten::index. We can add support for this. The next thing is there is a none that gets placed into a list with other tensors, so we need to expand our list construct implementation to handle that and make sure downstream this will work for other converters since they assume iirc that there are no nones in lists.

**Comment by narendasan** [comment]
Support for this case should be merged, reopen if still an issue
