### ISSUE TITLE
✨[Feature] torchtrtc should have the way to accept compile spec from command line

### ISSUE THREAD

**Issue by borisfom** [pytorch/TensorRT#537]
**Is your feature request related to a problem? Please describe.**
I can't supply compile spec to trtorchc now.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by narendasan** [comment]
Can you elaborate here? The CLI i think is lagging a bit but in theory we should be supporting all options in the compile spec as flags

**Comment by narendasan** [comment]
Something like a json or toml config file that has the args serialized

**Comment by ncomly-nvidia** [comment]
@borisfom is this issue still present with the latest APIs? Do you have a preference for CLI vs API?

**Comment by ncomly-nvidia** [comment]
Closing. @borisfom if still relevant, please let us know with more details & we will reopen.
