### ISSUE TITLE
✨[Feature] Dynamic shape support in Automatic fallback

### ISSUE THREAD

**Issue by peri044** [pytorch/TensorRT#552]
**Is your feature request related to a problem? Please describe.**
Support dynamic shapes in the input via automatic fallback.

**Describe the solution you'd like**
Currently the compilation fails when automatic fallback is enabled. Throw an error for this configuration or add support for dynamic shapes as a feature.

**Comment by ncomly-nvidia** [comment]
Closing in favor of #1376
