### ISSUE TITLE
✨[Feature] Look forward to a converter for torch.inverse

### ISSUE THREAD

**Issue by JuncFang-git** [pytorch/TensorRT#572]
**Is your feature request related to a problem? Please describe.**
A program can not be compiled with the "torch.inverse" operation.
![image](https://user-images.githubusercontent.com/76929740/129037944-2d679147-5ce7-40cf-a8f1-90dbc79323f1.png)

**Describe the solution you'd like**
Could you release this converter recently?

**Describe alternatives you've considered**
Or, could you give me some material like "inverse operation"，"converter building ", and so on?  I am not very familiar with cpp program, so, some detailed material is good for me.

**Comment by Christina-Young-NVIDIA** [comment]
To leave open until after holidays.
