### ISSUE TITLE
Wrap ScriptFunctions in modules to compile

### ISSUE THREAD

**Issue by narendasan** [pytorch/TensorRT#58]
Add a section to `_compiler.py` that wraps ScriptFunctions in Modules to compile the graph.

**Comment by lamhoangtung** [comment]
I would like to work on this. 

https://github.com/NVIDIA/TRTorch/blob/2fbbbc1c2cbe672a77aba7a0291059485f6ecc84/py/trtorch/_compiler.py#L135

In my understanding, TRTorch should be able to automatically wrap the function in a module and proceed with compiling the module. Do you have any other note for me @narendasan

**Comment by narendasan** [comment]
yeah, I am not entirely sure about the relationship between ScriptFunctions and ScriptModules. Heres how we wrap modules for Python coming from C++ for embedding engines https://github.com/NVIDIA/TRTorch/blob/2fbbbc1c2cbe672a77aba7a0291059485f6ecc84/py/trtorch/_compiler.py#L140
