### ISSUE TITLE
✨[Feature] Some operators need to be supported in Torch-TensorRT

### ISSUE THREAD

**Issue by ruoqianguo** [pytorch/TensorRT#766]
**Is your feature request related to a problem? Please describe.**

  There are some operators need to be supported in Torch-TensorRT. It is from a Video-Swin-Transformer model.
  - aten::index.Tensor(Tensor self, Tensor?[] indices) -> (Tensor)
  - aten::adaptive_avg_pool3d(Tensor self, int[3] output_size) -> (Tensor)
  - aten::Int.Tensor(Tensor a) -> (int)
  - aten::remainder.Tensor(Tensor self, Tensor other) -> (Tensor)
  - aten::div.Tensor_mode(Tensor self, Tensor other, *, str? rounding_mode) -> (Tensor)
  - aten::remainder.Scalar(Tensor self, Scalar other) -> (Tensor)
  - aten::roll(Tensor self, int[1] shifts, int[1] dims=[]) -> (Tensor)
  - aten::to.dtype_layout(Tensor(a) self, *, int? dtype=None, int? layout=None, Device? device=None, bool? pin_memory=None, bool non_blocking=False, bool copy=False, int? memory_format=None) -> (Tensor(a))

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ncomly-nvidia** [comment]
@guoruoqian does Swin-Transformer work with fallback enabled? Can you post the log if not?

**Comment by guoruoqian** [comment]
> @guoruoqian does Swin-Transformer work with fallback enabled? Can you post the log if not?

Hi @ncomly-nvidia, Video-Swin-Transformer doesn't work with fallback enabled.
We set compile settings as the following.
```
compile_settings.enabled_precisions = {torch_tensorrt::DataType::kFloat};
compile_settings.require_full_compilation = false;
compile_settings.truncate_long_and_double = true;
```
And I add a LOG_DEBUG("Runing analysis in progress " << seg_block) in [there](https://github.com/NVIDIA/Torch-TensorRT/blob/9eae269bc1d916ca672c973a17a37e2ed8e428eb/core/partitioning/shape_analysis.cpp#L42).
The output is [log_with_truncate.txt](https://github.com/NVIDIA/Torch-TensorRT/files/7947289/log_with_truncate.txt).

We set compile settings as the following.
```
compile_settings.enabled_precisions = {torch_tensorrt::DataType::kFloat};
compile_settings.require_full_compilation = false;
compile_settings.truncate_long_and_double = false;
```
The output is [log_without_truncate.txt](https://github.com/NVIDIA/Torch-TensorRT/files/7947298/log_without_truncate.txt)

**Comment by ncomly-nvidia** [comment]
@guoruoqian there are still outstanding ops here, right? I think we should leave this open for that + the fallback issues.

**Comment by ncomly-nvidia** [comment]
Still ops remaining

**Comment by ncomly-nvidia** [comment]
Reopening. Should be closed w/ aten::int

**Comment by dav-ell** [comment]
Is there any way we can also get support for 

```python
  aten::div(Scalar a, Scalar b) -> (float):
  Keyword argument rounding_mode unknown.
```

and / or:

```python
  aten::div.int(int a, int b) -> (float):
  Keyword argument rounding_mode unknown.
```

Code and logs attached.

[testdiv.py.txt](https://github.com/NVIDIA/Torch-TensorRT/files/8428891/testdiv.py.txt)
[logs_debug.txt](https://github.com/NVIDIA/Torch-TensorRT/files/8428886/logs_debug.txt)

**Comment by ncomly-nvidia** [comment]
Hi @dav-ell we absolutely can look into adding those operators into Torch-TRT! This issue is being used to track the operators for Video-Swin-Transformer specifically. Can you please file a new issue with this information and your use case / need?

Also, feel free to try & implement these ops yourself and submit a PR! We are always happy to get community contributions.

**Comment by ruoqianguo** [comment]
Video-Swin-Transformer will be supported once [#870](https://github.com/NVIDIA/Torch-TensorRT/pull/870) goes through.

**Comment by ruoqianguo** [comment]
@ncomly-nvidia  Sorry to open this issue again after so long. 
I failed converting Video Swin-Transformer with latest master code.  Because there are still some 'aten::Int' ops left after lowering graph.   I attached the log_full_compilcation file.
When i made the "aten::Int" operation to execute in Torch, it also failed.  I am trying to figure it out.  I attached the log_fallback file.
[log_full_compilation.txt](https://github.com/NVIDIA/Torch-TensorRT/files/8520070/log_full_compilation.txt)
[log_fallback.txt](https://github.com/NVIDIA/Torch-TensorRT/files/8520071/log_fallback.txt)

**Comment by ruoqianguo** [comment]
I provided a snippet code which is widely used in swin-transformer. In this code, "aten::Int" is failed in lowering. So i tried to make "aten::Int" execute in torch. When i traced the model and compiled it with torch-trt, it failed during compiling.  When i scripted the model and compiled it with torch-trt, it worked. 

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import torch_tensorrt as torchtrt
torchtrt.logging.set_reportable_log_level(torchtrt.logging.Level.Debug)

class Net(nn.Module):
    def __init__(self, window_size=7):
        super(Net, self).__init__()
        self.window_size = window_size
    
    def forward(self, x):
        B, H, W, C = x.shape
        x = x.view(B, H // self.window_size, self.window_size, W // self.window_size, self.window_size, C)
        windows = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, self.window_size, self.window_size, C)
        return windows

shape = [2, 14, 14, 5]
x = torch.randn(*shape).cuda()
py_net = Net(window_size=7).eval().cuda()
# script_net = torch.jit.script(py_net).cuda()
script_net = torch.jit.trace(py_net, (x, )).cuda()
print("torchscript graph: ", script_net.graph)

y = script_net(x)

# trtorch
compile_settings = {
    "inputs":  [
        torchtrt.Input(shape, dtype=torch.float),
        ],
    "enabled_precisions": {torch.float},
    "require_full_compilation": False,
    "truncate_long_and_double": True,
    "torch_executed_ops":["aten::Int"],
}

trt_ts_module = torchtrt.ts.compile(script_net, **compile_settings)
print("compiled")

trt_out = trt_ts_module(x)
print("torchscript results, ", y.size())
print("trt results, ", trt_out.size())
print("diff: ", torch.mean(torch.abs(trt_out - y)))
```
If we want to work around "aten::int", we need to provided a fixed `H W C`, like that:
```
class Net(nn.Module):
    def __init__(self, window_size=7, input_resolution=(14, 14, 5)):
        super(Net, self).__init__()
        self.window_size = window_size
        self.input_resolution = input_resolution
    
    def forward(self, x):
        H, W, C = self.input_resolution
        x = x.view(-1, H // self.window_size, self.window_size, W // self.window_size, self.window_size, C)
        windows = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, self.window_size, self.window_size, C)
        return windows
```
[script_log.txt](https://github.com/pytorch/TensorRT/files/9118983/script_log.txt)
[trace_log.txt](https://github.com/pytorch/TensorRT/files/9118985/trace_log.txt)
