### ISSUE TITLE
🐛 [Bug] nn.PReLU crashes torch_tensorrt.compile

### ISSUE THREAD

**Issue by styler00dollar** [pytorch/TensorRT#789]
##  Bug Description

Compiling model fails if `nn.PReLU` is used. It works fine with `nn.ReLU`.

## To Reproduce

Just run this code
```python
from torch import nn as nn
from torch.nn import functional as F
# https://github.com/xinntao/Real-ESRGAN/blob/master/realesrgan/archs/srvgg_arch.py
class test_class(nn.Module):
    def __init__(self, num_in_ch=3, num_out_ch=3, num_feat=64, num_conv=16, upscale=4):
        super(test_class, self).__init__()
        self.num_in_ch = num_in_ch
        self.num_out_ch = num_out_ch
        self.num_feat = num_feat
        self.num_conv = num_conv
        self.upscale = upscale

        self.body = nn.ModuleList()
        self.body.append(nn.Conv2d(num_in_ch, num_feat, 3, 1, 1))
        
        # prelu does not work, relu does
        activation = nn.PReLU(num_parameters=num_feat)
        #activation = nn.ReLU(inplace=True)
        self.body.append(activation)
        
        self.body.append(nn.Conv2d(num_feat, num_out_ch * upscale * upscale, 3, 1, 1))

    def forward(self, x):
        out = x
        for i in range(0, len(self.body)):
            out = self.body[i](out)
        return out

import torch
import torch_tensorrt
model = test_class()
example_data = torch.rand(1,3,256,256)
model = torch.jit.trace(model, [example_data])
print(model(example_data).shape)
model = torch_tensorrt.compile(model, inputs=[example_data], \
                enabled_precisions={torch.float}, truncate_long_and_double=True)
print(model(example_data.cuda()).shape)
```
```
python compact_tensorrt.py 
torch.Size([1, 48, 256, 256])
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 2: [pointWiseNode.cpp::computeOutputExtents::17] Error Code 2: Internal Error (Assertion nbDims == inputs[i]->extent.nbDims failed.)
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 2: [pointWiseNode.cpp::computeOutputExtents::17] Error Code 2: Internal Error (Assertion nbDims == inputs[i]->extent.nbDims failed.)
Traceback (most recent call last):
  File "compact_tensorrt.py", line 34, in <module>
    model = torch_tensorrt.compile(model, inputs=[example_data], \
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/_compile.py", line 97, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/ts/_compiler.py", line 119, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/conversion/converters/impl/conv_deconv.cpp:115] Expected orig_dims.nbDims > 2 to be true but got false
Unable to create convolution layer from node: %18 : Tensor = aten::_convolution(%input, %22, %23, %3, %3, %3, %5, %2, %4, %5, %5, %6, %6), scope: __module.body.2 # /usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py:442:0
```

## Expected behavior

Compile should not crash.

## Environment

 - Torch-TensorRT Version: 1.0
 - PyTorch Version: 1.10.0+cu113
 - OS: Manjaro + Docker (Nvidia TensorRT container 21.11-py3)

**Comment by p1x31** [comment]
I've encountered the same problem with converting [GridNet](https://arxiv.org/pdf/1707.07958.pdf) model

**Comment by narendasan** [comment]
@peri044 Can you take a look?

**Comment by styler00dollar** [comment]
Any update? My only solution is to convert the model to onnx and use onnx_tensorrt at this point, but I would like to switch to torch_tensorrt.

**Comment by yuezhuang1387** [comment]
I have encountered the same problem. Has it been solved？

**Comment by yuezhuang1387** [comment]
I have encountered the same problem. Has it been solved？@peri044

**Comment by p517332051** [comment]
这个也是相同的问题 #386 ，后面发现原因是prelu的weight和input纬度不相同造成底层构建tensorrt的prelu算子失败。 `底层实现的代码是在这里[https://github.com/NVIDIA/Torch-TensorRT/blob/master/core/conversion/converters/impl/activation.cpp](url)第84行～126行。
` {"aten::prelu(Tensor self, Tensor weight) -> (Tensor)",
             [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
               auto in = args[0].ITensor();
               auto slopes = args[1].unwrapToTensor();

               bool to_reshape = false;
               auto original_shape = in->getDimensions();
               if (slopes.numel() != 1 &&
                   !util::broadcastable(
                       in->getDimensions(),
                       util::toDims(slopes.sizes()),
                       /*multidirectional=*/false)) {
                 if (util::volume(in->getDimensions()) == util::volume(util::toDims(slopes.sizes()))) {
                   to_reshape = true;
                   LOG_DEBUG(
                       "Input shape is not broadcastable inserting shuffle layers to reshape to "
                       << util::toDims(slopes.sizes()));
                   auto in_shuffle = ctx->net->addShuffle(*in);
                   TORCHTRT_CHECK(in_shuffle, "Unable to create resize layer for aten::prelu input");
                   in_shuffle->setReshapeDimensions(util::toDims(slopes.sizes()));
                   in_shuffle->setName(
                       std::string("[Reshape in to " + util::toStr(util::toDims(slopes.sizes())) + " for broadcasting]")
                           .c_str());
                   in = in_shuffle->getOutput(0);
                 }
               }

               auto slope_tensor = tensor_to_const(ctx, slopes);
               auto new_layer = ctx->net->addParametricReLU(*in, *slope_tensor);
               new_layer->setName(util::node_info(n).c_str());
               auto out_tensor = new_layer->getOutput(0);

               if (to_reshape) {
                 auto out_shuffle = ctx->net->addShuffle(*out_tensor);
                 TORCHTRT_CHECK(out_shuffle, "Unable to create resize layer for aten::prelu output");
                 out_shuffle->setReshapeDimensions(original_shape);
                 out_shuffle->setName(
                     (std::string("[Reshape back to ") + util::toStr(original_shape) + std::string("]")).c_str());
                 out_tensor = out_shuffle->getOutput(0);
               }

               out_tensor = ctx->AssociateValueAndTensor(n->outputs()[0], out_tensor);
               LOG_DEBUG("Output shape: " << out_tensor->getDimensions());
               return true;
             }})`
 

将其修改成
`            {"aten::prelu(Tensor self, Tensor weight) -> (Tensor)",
             [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
               auto in = args[0].ITensor();
               auto slopes = args[1].unwrapToTensor();
               auto original_shape = in->getDimensions();

               std::vector<int64_t> InputArraysShape = slopes.sizes().vec();
//               for (int ii = 0;ii< original_shape.nbDims;ii++){
//
//               }
               if(InputArraysShape.size()!=original_shape.nbDims and InputArraysShape.size()==1){
                   std::vector<int64_t> slopes_new_shape = {original_shape.d[0],InputArraysShape[0]};
                   for(int ii=0;ii<original_shape.nbDims -2;ii++){
                       slopes_new_shape.push_back(1);
                   }
                   slopes = slopes.reshape(slopes_new_shape);
               }


               bool to_reshape = false;
               if (slopes.numel() != 1 &&
                   !util::broadcastable(
                       in->getDimensions(),
                       util::toDims(slopes.sizes()),
                       /*multidirectional=*/false)) {
                 if (util::volume(in->getDimensions()) == util::volume(util::toDims(slopes.sizes()))) {
                   to_reshape = true;
                   LOG_DEBUG(
                       "Input shape is not broadcastable inserting shuffle layers to reshape to "
                       << util::toDims(slopes.sizes()));
                   auto in_shuffle = ctx->net->addShuffle(*in);
                   TORCHTRT_CHECK(in_shuffle, "Unable to create resize layer for aten::prelu input");
                   in_shuffle->setReshapeDimensions(util::toDims(slopes.sizes()));
                   in_shuffle->setName(
                       std::string("[Reshape in to " + util::toStr(util::toDims(slopes.sizes())) + " for broadcasting]")
                           .c_str());
                   in = in_shuffle->getOutput(0);
                 }
               }

               auto slope_tensor = tensor_to_const(ctx, slopes);
               auto new_layer = ctx->net->addParametricReLU(*in, *slope_tensor);
               new_layer->setName(util::node_info(n).c_str());
               auto out_tensor = new_layer->getOutput(0);

               if (to_reshape) {
                 auto out_shuffle = ctx->net->addShuffle(*out_tensor);
                 TORCHTRT_CHECK(out_shuffle, "Unable to create resize layer for aten::prelu output");
                 out_shuffle->setReshapeDimensions(original_shape);
                 out_shuffle->setName(
                     (std::string("[Reshape back to ") + util::toStr(original_shape) + std::string("]")).c_str());
                 out_tensor = out_shuffle->getOutput(0);
               }

               out_tensor = ctx->AssociateValueAndTensor(n->outputs()[0], out_tensor);
               LOG_DEBUG("in: "<<in->getDimensions() );
               LOG_DEBUG("Output tensor shape: " << out_tensor->getDimensions());
               return true;
             }})`

上述修改主要功能是判断prelu输入和weight的维度是否一致，如果不一致则reshape成同一个纬度添加的代码段如下，其中original_shape是prelu输入的纬度，slopes是prelu的weight。
`               if(InputArraysShape.size()!=original_shape.nbDims and InputArraysShape.size()==1){
                   std::vector<int64_t> slopes_new_shape = {original_shape.d[0],InputArraysShape[0]};
                   for(int ii=0;ii<original_shape.nbDims -2;ii++){
                       slopes_new_shape.push_back(1);
                   }
                   slopes = slopes.reshape(slopes_new_shape);
               }`
