### ISSUE TITLE
❓ [Question] How do you override or remove evaluators 

### ISSUE THREAD

**Issue by DavidBaldsiefen** [pytorch/TensorRT#823]
## ❓ Question

I am trying to use YOLOv5 with Torch-TensorRT. When I load the model, I get the following error message (among others):
```

ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [layers.cpp::validate::2385] Error Code 4: Internal Error (%3264 : Tensor = aten::mul(%3263, %3257) # /home/.../yolov5/models/yolo.py:66:0: operation PROD has incompatible input types Float and Int32)
```

Thus I wanted to try to overload the `aten::mul` operator to support `float*int` and `int*float` operations, which fails (see below)

**(How) Is it possible to override or remove existing evaluators?**

## What you have already tried

I am using the following code:
```

static auto atenmul_evaluator =
    torch_tensorrt::core::conversion::evaluators::RegisterNodeEvaluators().evaluator(
        {c10::Symbol::fromQualString("aten::mul"),
         [](const torch::jit::Node *n, torch_tensorrt::core::conversion::evaluators::kwargs &args)
             -> c10::optional<torch::jit::IValue> {
             ROS_INFO("Custom Evaluator is being accessed!");

             if (args.at(n->input(0)).IValue()->isInt() && args.at(n->input(1)).IValue()->isInt()) {
                 auto a = args.at(n->input(0)).unwrapToInt();
                 auto b = args.at(n->input(1)).unwrapToInt();
                 return a * b;
             } else if (args.at(n->input(0)).IValue()->isDouble() &&
                        args.at(n->input(1)).IValue()->isDouble()) {
                 auto a = args.at(n->input(0)).unwrapToDouble();
                 auto b = args.at(n->input(1)).unwrapToDouble();
                 return a * b;
             } else if (args.at(n->input(0)).IValue()->isInt() &&
                        args.at(n->input(1)).IValue()->isDouble()) {
                 auto a = args.at(n->input(0)).unwrapToInt();
                 auto b = args.at(n->input(1)).unwrapToDouble();
                 return a * b;
             } else if (args.at(n->input(0)).IValue()->isDouble() &&
                        args.at(n->input(1)).IValue()->isInt()) {
                 auto a = args.at(n->input(0)).unwrapToDouble();
                 auto b = args.at(n->input(1)).unwrapToInt();
                 return a * b;
             } else {
                 TORCHTRT_THROW_ERROR("Unimplemented data type for aten::mul evaluator: "
                                      << args.at(n->input(0)).IValue()->type()->str());
                 return {};
             }
         },
         torch_tensorrt::core::conversion::evaluators::EvalOptions().validSchemas(
             {"aten::mul.int(int a, int b) -> (float)",
              "aten::mul.float(float a, float b) -> (float)",
              "aten::mul.int_float(int a, float b) -> (float)",
              "aten::mul.float_int(float a, int b) -> (float)"})});
```

But then I get the errormessage `Attempting to override already registered evaluator aten::mul, merge implementations instead`. Thus I want to try and find a way to override or remove the evaluator without recompiling Torch-TensorRT.

When I implemented the above only for `int_float` and `float_int` seperately, the output returned to the orignal errormessage from above, indicating that the new evaluator wasn't used.

**Comment by DavidBaldsiefen** [comment]
Hmm, I understand. I recompiled Torch-TensorRT with my new evaluators (and confirmed their existence using `torch_tensorrt::core::conversion::evaluators::getEvaluatorList()`), but the error message still remains for some reason.

```
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [layers.cpp::validate::2385] Error Code 4: Internal Error (%3264 : Tensor = aten::mul(%3263, %3257) # /home/.../yolov5/models/yolo.py:66:0: operation PROD has incompatible input types Float and Int32)
```

**Comment by narendasan** [comment]
Looks like this error is coming from the `aten::mul` converter and not the evaluator (should have looked at the initial error more closely). Likely what is happening is that `%3263` is a float tensor and `%3257` is probably a int tensor (it could also be a scalar, you can tell by looking them up in the graph dump in the debug log but I don't think you'd get this error for a scalar). Iirc TRT expects like types for element wise operations.

So in this case you could implement a custom converter and you should be able to override the aten::mul.Tensor in the library. 

https://github.com/NVIDIA/Torch-TensorRT/blob/b652045db168e9a51db55b10ed867a09c3185255/core/conversion/converters/impl/element_wise.cpp#L373

There is a utility to just cast an ITensor https://github.com/NVIDIA/Torch-TensorRT/blob/b652045db168e9a51db55b10ed867a09c3185255/core/conversion/converters/converter_util.cpp#L124

In the case of a PyTorch tensor you can use the PyTorch apis to cast.

@peri044 do you think we should just uniformly cast these cases until TRT supports it?

**Comment by ncomly-nvidia** [comment]
@peri044 bump. @narendasan we should bring up with TRT team in our sync Friday

**Comment by ncomly-nvidia** [comment]
This should be resolved in ToT - mixed dtype mul. Closing - please comment to reopen if not so.
