### ISSUE TITLE
↔ [Converter] Add support for aten::__derive_index in Torch-TensorRT

### ISSUE THREAD

**Issue by p1x31** [pytorch/TensorRT#834]
##

- **Function Schema**:
aten::__derive_index(int index, int start, int step) -> (int)
- **Original PyTorch API**:
- https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/runtime/register_prim_ops.cpp#L183

- **Relevant TensorRT Documentation**:

## Additional context

https://github.com/pytorch/pytorch/pull/48019

**Comment by narendasan** [comment]
What is the actual functionality here?  Is it like `start + index * step`?

**Comment by p1x31** [comment]
Yes. An error only occurs when using Torch-TensorRT in Python like [this](https://nvidia.github.io/Torch-TensorRT/tutorials/getting_started_with_python_api.html#). When compiling with torch.jit.script separately and passing TorchScript module to Torch-TensorRT everything works fine.

**Comment by Pikassik** [comment]
also faced this problem
