### ISSUE TITLE
❓ [Question] Speed problem about TRTorch and Torch-TensorRT - Device Compatibility Check

### ISSUE THREAD

**Issue by yuezhuang1387** [pytorch/TensorRT#854]
## Question1
I find the Torchscript model optimized by TRTorch 0.2.0 faster than TensorRT model(All models are Python API)，such as common ResNet series, RapVGG series models and so on, shouldn't the TensorRT model be the fastest? I want to know why does this happen.
>Torchscript model(optimized by TRTorch 0.2.0):
- torch 1.7.1+cu110
- trtorch 0.2.0
- TensorRT 7.2
- cuDNN 8.2
- GPU:Tesla T4
- CentOS Linux release 7.6.1810 (Core)
>TensorRT model(.trt):
- torch 1.7.1+cu110
- tensorrt 8.2.0.6
- cuDNN 8.2
- GPU:Tesla T4
-CentOS Linux release 7.6.1810 (Core)

## Question2
I found the inference speed of TorchScript model is different after using different versions of Torch-TensoRT(TRTorch) to optimize  with the same structure.
For the same structure ResNet series model, TorchScript model(optimized by TRTorch 0.2.0,torch 1.7.1-cu110,TensorRT 7.2 and cuDNN 8.2) is faster than TorchScript model(optimized by Torch-TensorRT 1.0.0,torch 1.10.1-cu113,TensorRT 8.0 and cuDNN 8.2), shouldn't the latest Torch-TensorRT 1.0.0 be faster ？I'm also very confused.
- GPU:Tesla T4
- CentOS Linux release 7.6.1810 (Core)
- input shape: (1,3,224,224)
Here are some of my test results.
![image](https://user-images.githubusercontent.com/61401199/152927186-6f3ac345-1913-4af5-b32d-0bf09ebfb6a9.png)

**Comment by ncomly-nvidia** [comment]
Between these two versions there was a constant time operation that was added to check compatibility of the current device with the compiled model. This is likely the overhead you are experiencing.

We are investigating if this can be mitigated for future inferences once the model is loaded.

**Comment by Christina-Young-NVIDIA** [comment]
Root cause is known, just needs a fix.

**Comment by ncomly-nvidia** [comment]
This device check cannot currently be mitigated safely. We are investigating options in TRT to mitigate this overhead.

**Comment by narendasan** [comment]
Explore using https://docs.nvidia.com/cuda/cuda-runtime-api/structcudaPointerAttributes.html#structcudaPointerAttributes to query data locations and assume current device is correct?

**Comment by laikhtewari** [comment]
https://developer.nvidia.com/blog/cuda-pro-tip-the-fast-way-to-query-device-properties/
