### ISSUE TITLE
❓ [Question] ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Biaocsu** [pytorch/TensorRT#858]
## ❓ Question

As I can't install `torch-tensorrt` for some reason in this method:`pip3 install torch-tensorrt -f https://github.com/NVIDIA/Torch-TensorRT/releases
`
I download `torch-tensorrt` from here `https://github.com/NVIDIA/Torch-TensorRT/releases/tag/v1.0.0`
using `pip install torch_tensorrt-1.0.0-cp36-cp36m-linux_x86_64.whl`

however when I `import torch_tensorrt`
here comes the error `ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory`

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0):1.10.2+cu113
 - CPU Architecture:
 - OS (e.g., Linux):linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):pip
 - Build command you used (if compiling from source): pip install 
 - Are you using local sources or building from archives:
 - Python version:3.6.2
 - CUDA version:11.3
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

tensorrt==8.2.1.8

**Comment by narendasan** [comment]
Is cuDNN in your LD_LIBRARY_PATH?

**Comment by Biaocsu** [comment]
> Is cuDNN in your LD_LIBRARY_PATH?

yes, I think so, As I checked `~/.bashrc` file, as below:
```
export PATH=/usr/local/cuda-11.3/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```

**Comment by IamExperimenting** [comment]
@narendasan even I'm facing the same problem. could you please provide us instruction to install torch_tensorrt step by step in Linux
