### ISSUE TITLE
🐛 [Bug] Can't install TorchTensorRT through pip (it installs version 0.0.0)

### ISSUE THREAD

**Issue by andreabonvini** [pytorch/TensorRT#859]
##  Bug Description

I installed all the dependencies correctly.
I'm using CUDA 11.5, CUDNN 8.3.1, TensorRT 8.2.3.0, PyTorch 1.10.2 with CUDA 11.3 support. However when I try to install TorchTensorRT through the following command:
`pip3 install torch-tensorrt -f https://github.com/NVIDIA/Torch-TensorRT/releases`
I get the following message:

```
# pip3 install torch-tensorrt -f https://github.com/NVIDIA/Torch-TensorRT/releases
Looking in links: https://github.com/NVIDIA/Torch-TensorRT/releases
Collecting torch-tensorrt
  Using cached torch_tensorrt-0.0.0.tar.gz (762 bytes)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: torch-tensorrt
  Building wheel for torch-tensorrt (setup.py) ... done
  Created wheel for torch-tensorrt: filename=torch_tensorrt-0.0.0-py3-none-any.whl size=1354 sha256=05a650bedd11cc2d3e883c66ed2ad56ec2410c4da2005c8b3222c596d5b6acc9
  Stored in directory: c:\users\novum\appdata\local\pip\cache\wheels\5e\38\da\78f7582f6cd9d87d0bfc2677516507fd8fd25a0f1701124aaf
Successfully built torch-tensorrt
Installing collected packages: torch-tensorrt
Successfully installed torch-tensorrt-0.0.0
```

Why is it installing version 0.0.0?
If I try to import `torch_tensorrt` in python this is what happens:
```
>>> import torch_tensorrt
TRTorch currently does nothing

```
## Expected behavior

It should install version 1.0.0, I guess.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): ...
 - PyTorch Version (e.g. 1.0): 1.10.2+cu113
 - CPU Architecture: x64
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Python version: 3.9.10
 - CUDA version: 11.5
 - GPU models and configuration: RTX3080

**Comment by andreabonvini** [comment]
The answer is: I can't install TorchTensorRT because Windows isn't supported. However, I can't even optimize my model by running the NGC docker image from WSL2 (as explained here #856). Then, I guess that the only way I could optimize my model for my specific hardware (RTX 3080) is to switch my PC to Ubuntu, optimize the model, and going back to WIndows? It doesn't exist any better solution?

**Comment by ncomly-nvidia** [comment]
Torch-TRT now has CMake support from the community. Check it out & let us know what you think! #1058

**Comment by aviadmx** [comment]
I'm on ubuntu and also fail to install from pip

**Comment by ncomly-nvidia** [comment]
GitHub changes broke the pip distro. please see: https://github.com/pytorch/TensorRT/issues/1371#issuecomment-1256760254
