### ISSUE TITLE
🐛 [Bug] Encountered bug when using Torch-TensorRT

### ISSUE THREAD

**Issue by wuyxiquanquan** [pytorch/TensorRT#900]
##  Bug Description

It can't create a `torch_tensorrt::ts::CompileSpec` instance, where it throws this bug: 
```
/usr/bin/ld: CMakeFiles/fuck_pytorch.dir/main.cpp.o: in function `main':
/workspace/fuck_pytorch/main.cpp:27: undefined reference to `torch_tensorrt::torchscript::CompileSpec::CompileSpec(std::vector<c10::ArrayRef<long>, std::allocator<c10::ArrayRef<long> > >)'
/usr/bin/ld: /workspace/fuck_pytorch/main.cpp:27: undefined reference to `torch_tensorrt::torchscript::compile(torch::jit::Module const&, torch_tensorrt::torchscript::CompileSpec)'
```
By the way, the documentation of [Torch-tensorrt C++ getting started](https://nvidia.github.io/Torch-TensorRT/tutorials/getting_started_with_cpp_api.html) didn't update code since the Torch-TensorRT V1.0.0 release.

## To Reproduce

1. CMake file: 
```
find_package(PythonInterp REQUIRED)
cmake_minimum_required(VERSION 3.13)
project(fuck_pytorch)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_PREFIX_PATH /workspace/libtorch)
find_package(Torch REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS} -D_GLIBCXX_USE_CXX11_ABI=0")

#include_directories(/workspace/torch_tensorrt/include /workspace/libtorch/include)
link_directories(/workspace/torch_tensorrt/lib)
add_executable(fuck_pytorch main.cpp)
target_link_libraries(fuck_pytorch "${TORCH_LIBRARIES}")
target_include_directories(fuck_pytorch PUBLIC /workspace/torch_tensorrt/include)
target_include_directories(fuck_pytorch PUBLIC /workspace/libtorch/include)
#target_link_directories(fuck_pytorch PUBLIC /workspace/torch_tensorrt/lib)
#set_property(TARGET fuck_pytorch PROPERTY CXX_STANDARD 11)
```
2. main.cpp
```
#include <torch/script.h> // One-stop header.
#include "torch_tensorrt/torch_tensorrt.h"


#include <iostream>
#include <memory>

using namespace std;

int main(int argc, const char* argv[]) {
  torch::jit::Module module;
  try {
    // Deserialize the ScriptModule from a file using torch::jit::load().
    module = torch::jit::load("/workspace/model/ssd_300_traced.jit.pt");
  }
  catch (const c10::Error &e) {
    std::cerr << "error loading the model\n";
    return -1;
  }

  std::cout << "ok\n";

  module.eval();
  module.to(at::kCUDA);
  auto in = torch::randn({1, 1, 32, 32}, {torch::kCUDA});
  std::cout << in.sizes();
  auto trt_mod = torch_tensorrt::ts::compile(module, torch_tensorrt::ts::CompileSpec(std::vector<c10::ArrayRef<int64_t>> {in.sizes()}));


//  auto out = trt_mod.forward({in});


}

```

## Expected behavior

successfully run.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages
 - Pytorch docker: 21.06
 - Torch-TensorRT Version : libtorchtrt-v1.0.0-cudnn8.2-tensorrt8.0-cuda11.3-libtorch1.10.0.tar.gz 
 - PyTorch Version: libtorch: libtorch-cxx11-abi-shared-with-deps-1.10.2+cu113.zip
 - CPU Architecture: amd64
 - OS (e.g., Linux): ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): libtorch
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.8
 - CUDA version: 11.3.1
 - GPU models and configuration: 3090
 - Any other relevant information:

**Comment by andreabonvini** [comment]
I think I had a similar issue the other day, I guess that using the `Pre-cxx11 ABI` version of libtorch (that you can download [here](https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.10.2%2Bcpu.zip)) may solve your problem.

**Comment by peri044** [comment]
Can you try following this https://nvidia.github.io/Torch-TensorRT/tutorials/getting_started_with_cpp_api.html#compiling-with-torch-tensorrt-in-c instead? 
```
auto trt_mod = torch_tensorrt::CompileGraph(mod, std::vector<torch_tensorrt::CompileSpec::InputRange>{{in.sizes()}});
```

**Comment by wuyxiquanquan** [comment]
> 

Can't find InputRange in Torch-TensorRT V1.0.0

**Comment by wuyxiquanquan** [comment]
> Can't find InputRange in Torch-TensorRT V1.0.0



> Can you try following this https://nvidia.github.io/Torch-TensorRT/tutorials/getting_started_with_cpp_api.html#compiling-with-torch-tensorrt-in-c instead?
> 
> ```
> auto trt_mod = torch_tensorrt::CompileGraph(mod, std::vector<torch_tensorrt::CompileSpec::InputRange>{{in.sizes()}});
> ```

Can't find InputRange in Torch-TensorRT V1.0.0

**Comment by narendasan** [comment]
The API was renamed to Input in 0.4.0
