### ISSUE TITLE
↔ [Converter] Add support for aten::atan2 in Torch-TensorRT

### ISSUE THREAD

**Issue by Njuapp** [pytorch/TensorRT#938]
##
Unsupported operator: aten::atan2(Tensor self, Tensor other) -> (Tensor)

- **Function Schema**:
 aten::atan2(Tensor self, Tensor other) -> (Tensor)

- **Original PyTorch API**:
  torch.atan2(input, other, *, out=None) → [Tensor]

- **Relevant TensorRT Documentation**:
  None
## Additional context

When using Fourier transformation in audio segmentation models, `torch.atan2` will be used. 
Because variable audio input lengths requires dynamic shape, fallback to pytorch would cause runtime error when creating example inputs by `partitioning::generateRandomInputs`. 
It reports 
> RuntimeError: Trying to create tensor with negative dimension -1: [1, 1, -1]

Therefore, we need  convertor for `torch.atan2` to successfully convert such models.

**Comment by narendasan** [comment]
cc: @ncomly-nvidia

**Comment by narendasan** [comment]
cc: @abose

**Comment by narendasan** [comment]
cc: @apbose
