### ISSUE TITLE
✨[Feature] LTS Releases and Backwards Support for Dependencies

### ISSUE THREAD

**Issue by chaoz-dev** [pytorch/TensorRT#946]
**Is your feature request related to a problem? Please describe.**
From our previous conversations offline, it appears that Torch-TensorRT releases currently follow PyTorch releases. However, there appears to be some ambiguity with regards to backwards support for older CUDA and TensorRT releases and other dependencies, and with how bug fixes will be backported to previous LTS releases; we should seek to maintain some backwards compatibility for older dependencies and support backporting bug fixes to LTS releases so that users need not upgrade constantly.

The current upgrade paradigm is problematic for the following reasons:
- Upgrading Torch-TensorRT releases (potentially) requires upgrading CUDA and TensorRT as well (in addition to PyTorch). This coupling may not be feasible (especially for larger projects), as these upgraded dependencies need to be evaluated for performance, issues, and bugs; there may be other requirements for keeping these dependent libraries at earlier releases, as well. Thus, it becomes a massive pain point to require upgrading several dependencies simultaneously (especially to very specific (minor) versions).
- CUDA and TensorRT may change APIs between (even minor) releases; this appears to be the case between TensorRT 8.0 and 8.4. This adds additional difficulty in updating dependent libraries or Torch-TensorRT itself (if Torch-TensorRT releases are not backwards compatible with dependent libraries). 
- Bug fixes may require minor version updates in both Torch-TensorRT and its dependencies, which require these libraries to be somewhat update-able independent of one another.

**Describe the solution you'd like**
Ideally, the master branch should seek to be fully backwards compatible with all dependent libraries up to some minimum version. This allows users to always pull the latest changes to test bug fixes or perform development with some assurance that their current dependencies are still valid and need not constantly be updated. Furthermore, this facilitates future upgrades to minor - and potentially even major - versions without immediately invalidating the dependencies of projects.

For LTS releases, we should seek to backport fixes onto that specific (major) release without requiring _any_ dependency upgrades (which should be streamlined by the aforementioned backwards compatibility). This guarantees that fixes can be applied easily and in isolation while minimizing the risk of introducing additional bugs and issues.  

**Describe alternatives you've considered**
Currently, pulling bug-fixes for Torch-TensorRT requires the user to update Torch-TensorRT; however, to update Torch-TensorRT, the user will likely have to update most dependencies, which is unfeasible for the aforementioned reasons.

**Additional context**
Note that new features (that may require new APIs) need not be backported here; we can request that users upgrade Torch-TensorRT for newer features. This request is mostly focused on _backporting bug fixes for features that should already work in previous releases_, as well as _maintaining backwards compatibility for previously working features_.

**Comment by ncomly-nvidia** [comment]
Great suggestion @chaoz-dev. As we discussed, we will be creating a static "legacy sw stack" that is supported by new versions of Torch-TRT for some period of time. The sw versions for this stack are still TBC, but likely will be tied to PyTorch LTS versions.

Note that this is different from LTS: LTS defines an old version of Torch-TRT that continues to get bug fixes. This is not currently on the roadmap.


What this means for your workflow: to get bug fixes & features will require updating Torch-TRT versions, but not dependencies like PyT & TensorRT _if_ you are using the legacy stack.

**Comment by ncomly-nvidia** [comment]
Closing in favor of #1009. The target is still v1.4. @chaoz-dev please add any more comments or feedback to the discussion.
