### ISSUE TITLE
🐛 [Bug] Encountered bug when using Torch-TensorRT

### ISSUE THREAD

**Issue by JHancox** [pytorch/TensorRT#970]
##  Bug Description

Documentation Error

## To Reproduce

The example given for CLI usage here:
[https://nvidia.github.io/Torch-TensorRT/tutorials/torchtrtc.html](https://nvidia.github.io/Torch-TensorRT/tutorials/torchtrtc.html)
has the .pt and .ts commands the wrong way round

## Expected behavior

It should be like this:
`torchtrtc tests/modules/ssd_traced.jit.ts ssd_trt.pt "[(1,3,300,300); (1,3,512,512); (1, 3, 1024, 1024)]@f16%contiguous" -p f16`
rather than this:
`torchtrtc tests/modules/ssd_traced.jit.pt ssd_trt.ts "[(1,3,300,300); (1,3,512,512); (1, 3, 1024, 1024)]@f16%contiguous" -p f16`

**Comment by narendasan** [comment]
Thanks for reporting this, we will fix this in the docs.

**Comment by JHancox** [comment]
Thanks @narendasan. That makes sense. Perhaps worth changing the output parameter to something that looks more like a trt file than a torchscript input e.g. .trt rather than .ts as IMHO this is a source of confusion.

**Comment by narendasan** [comment]
we could do something like .trt.ts perhaps, but this is a valid torchscript file and presumably a .trt file would be like a normal standard PLAN file from TensorRT

**Comment by JHancox** [comment]
It's the .ts extension that was the source of confusion for me - sounds like it ought to be a torchscript file, but if that is a convention then probably best to leave as is. Thanks anyhow - feel free to close.
