### ISSUE TITLE
🐛 [Bug] Failed to use stoi to get the engine ID in TRTEngine function

### ISSUE THREAD

**Issue by bowang007** [pytorch/TensorRT#982]
##  Bug Description

Got this  error: 
```
INFO: [Torch-TensorRT - Debug Build] - [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +132, now: CPU 0, GPU 540 (MiB)
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)
```

Debugged and found that it fails at this line: https://github.com/NVIDIA/Torch-TensorRT/blob/c95229144432d96f4bdaa71fb1d242242d42bc29/core/runtime/TRTEngine.cpp#L63 

## To Reproduce

 MaskRCNN model from detectron2. 

## Expected behavior

should figure out why we cannot find a number from this engine.

**Comment by narendasan** [comment]
@bowang007  I have a fix for this

**Comment by bowang007** [comment]
could you please share more details?

**Comment by narendasan** [comment]
We still have the issue where TensorRT is changing the names of our input bindings so leaving this open to track this issue.

**Comment by bowang007** [comment]
closing per #1167
