### ISSUE TITLE
🐛 [Bug] No type to cast for Uninitialized type

### ISSUE THREAD

**Issue by bowang007** [pytorch/TensorRT#983]
##  Bug Description

We are getting this kind of ivalue type https://github.com/pytorch/pytorch/blob/b34b192d6b97325c9f78e5995c48c8498ede34bd/aten/src/ATen/core/ivalue.h#L159, however, when it's used by a later subgraph in fallback shape analysis, there is no available types that we can cast to. 

For example, we have this subgraph:

```
  Graph: graph(%out_dict.1 : Dict(str, Tensor),
      %2 : Tensor,
      %attributes_manager_out.1 : Dict(str, Tensor),
      %outputs.1 : Dict(str, Tensor)):
```

The second input is a uninitialized type, which is taken as a tensor for usage, but we will get this kind of error if we convert it to tensor: 
```
terminate called after throwing an instance of 'c10::Error'
  what():  Expected Tensor but got Uninitialized
```

## Expected behavior
Find any available type that we can use to cast.

**Comment by bowang007** [comment]
this can be resolved by adding torch::jit::exception_elimination pass https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/remove_exceptions.cpp in lowering.

**Comment by Mark-M2L** [comment]
Thanks a lot for your reply. I have taken a look into it and have a question about this implementation. I am thinking of two ways of implementing the possible solution you suggest. The first is to create a scripted model using `torch.jit.script(model)` and then feed this scripted model to the code written in [](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/remove_exceptions.cpp) to generate a new graph. But in that case, could I create a scripted model again, which can be fed into PyTorch and then use torch_tensorrt to compile this scripted model?

The second way I'm thinking of, is to rewrite the code in [](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/remove_exceptions.cpp) to Python code such that we can directly remove the exceptions with Python. After removing the exceptions, we can feed this scripted model to the compiler of torch_tensorrt.

Would you suggest to use any of these implementations, or would you suggest something different?
