### ISSUE TITLE
❓ [Question] How do you add CUDA kernels used for implemented plugins ? 

### ISSUE THREAD

**Issue by david-PHR** [pytorch/TensorRT#987]
## ❓ Question

How do you add CUDA kernels used for implemented plugins ? I have developed my own implementation for several layers that are not supported yet by Torch-TensorRT.  I'm not familiar with the bazel compilation flow and i  would like to know how to compile .cu files in Torch-TensorRT. 

Current provided Torch-TensorRT plugins make calls to external libraries (cuDNN for example) but there is no example about how  to add a custom plugins that call CUDA kernels.
 
## Additional context

In addition it could be nice to have a clear way on how to get the PyTorch signature of the methods that we want to encapsulate.

Cheers

David

**Comment by narendasan** [comment]
Theres a few options. 
You can register converters and plugins at runtime to extend the compilers libraries. Here is an example on how to register a custom converter https://github.com/NVIDIA/Torch-TensorRT/tree/master/examples/custom_converters. Plugins just need to be registered with TensorRT, not specifically Torch-TensorRT so you can follow the standard plugin writing procedure there. Alternatively you can use the TorchTRT macro to do this for you. https://github.com/NVIDIA/Torch-TensorRT/blob/7330c484cab0de81f7b826409e45a0fd9e7e3ec1/core/plugins/plugins.h#L23 In this case you can use whatever method is most convenient to build your plugin + converter library. We use PyTorch's CUDA extension system which is pretty easy to use. 
The converter and plugins will self register on load. 

If you want to build your plugin into libtorchtrt_plugins.so:
The most bazelly option is to import cuda rules like these: https://github.com/narendasan/rules_cuda and compile the kernels as a target. These rules are experimental so there might be some things that dont work. Alternatively you can use https://github.com/bazelbuild/rules_foreign_cc to call out to a Makefile or something

**Comment by david-photoroom** [comment]
Thank you for the explanation !
Do you have some known examples that doesn't works with these experimental rules ?

**Comment by narendasan** [comment]
Its been a while since I looked at it but iirc, some specific code structuring is needed (separating kernel code from host code) and then you need to be a bit careful with the dependencies for kernel code. I think there should be some basic examples in that repo
